### ISSUE TITLE
[Feature request] Target of link

### ISSUE THREAD

**Issue by pitichampi** [bastienwirtz/homer#10]
Hello

I'm trying your great project and it seems pretty promising :)
I was wondering if it could be possible to have an option to open links in a new tab (target _blank) in an item configuration.
That's all :)

**Comment by bastienwirtz** [comment]
Hi @pitichampi!

Thanks for reaching out! I just pushed it on master (https://github.com/bastienwirtz/homer/commit/56c69e0d6bd7265afec6cd66a4875ebf6357ea7d), enjoy :)
