### ISSUE TITLE
Unable to use news as dynamic message by @JamiePhonic

### ISSUE THREAD

**Issue by AlexanderEDavis** [bastienwirtz/homer#102]
I have followed the instructions to set up the news as dynamic message trick by @JamiePhonic but it doesn't seem to work.

Config I have used is
`message:
  url: "https://10.0.0.2:1880/dashboard-endpoint"
  style: "is-danger"
  title: "Node Red"
  content: "Couldn't get dynamic data from Node Red!"`

When I go to https://10.0.0.2:1880/dashboard-endpoint I can see it works

**Comment by JamiePhonic** [comment]
Check the console in your browsers developer tools (in most browsers, tap F12) for any errors.
For example, Firefox throws this error in its console if your Homer page is secured with SSL, but your Node Red instance isnt:
![image](https://user-images.githubusercontent.com/4817698/86140960-6140bb80-bae9-11ea-8d00-e737eb63fdfe.png)

I can see your Node Red instance is secured with SSL, so it's likely a different issue. The above is just an example.

**Comment by AlexanderEDavis** [comment]
Found the issue, my node-red doesn't have a certificate

**Comment by AlexanderEDavis** [comment]
I've gone to resolve the HTTP(s) error but now I have another error

![image](https://user-images.githubusercontent.com/9097891/86148003-fa73d000-baf1-11ea-9f5c-fa6c2dd405e3.png)

I can access the dashboard endpoint still

**Comment by JamiePhonic** [comment]
Assuming you are running your Node Red instance behind a reverse proxy like HAProxy or Nginx, you will need to set the "Access-Control-Allow-Origin" Header.

In HAProxy, add `http-response set-header Access-Control-Allow-Origin * `  to either the backend that handles your node-red instance, or to your front end.

Use `*` to specify any domain, or add your domain as a full URL instead.

Read more here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin

**Comment by AlexanderEDavis** [comment]
Thanks, works fine now

**Comment by JamiePhonic** [comment]
> 
> 
> Thanks, works fine now

Good to know!
I've added a note about setting the `Access-Control-Allow-Origin` to the flow's notes section on nodered.org
