### ISSUE TITLE
[Suggestion] Versioning of Docker images

### ISSUE THREAD

**Issue by ikaruswill** [bastienwirtz/homer#107]
**Primer**
Hi, first off, thanks for this fantastic piece of work. 

I've been able to build a pretty SSO dashboard for my family to access my self-hosted apps. It's lightweight enough for me to host 1 homer instance for each user access group.

**Problem**
I realize that although the Github repository has versions, the Docker image does not have versioned tags, only `latest`. 
It became more apparent to me after facing #103, where `homer` worked flawlessly until the most recent image update, and I don't have any older image version to fallback on.

**Suggestion**
May I suggest implementing versioning on the Docker images since it seems that there are quite a significant number of people depending on the Docker images judging by the number of image pulls: `Pulls 1M+`.

It would be less than ideal if anyone's dashboard broke and remained broken while waiting for a fix, should a bug be introduced in an update. 

**Steps**
- I'm willing to help with a PR, though I'm afraid I'm not familiar with Docker Hub's Automated Builds. 
- Or if it's easier, I can maintain an `arm` + `arm64` fork with versioned tags on a cron build to keep it synchronized with master. (I don't have `amd64` machines for building on my CICD)

**Comment by bastienwirtz** [comment]
Hi @ikaruswill 

Totally agree, I should have done it before, sorry for that! I've just added the release tag [builds](https://hub.docker.com/r/b4bz/homer/tags): 

![2020-07-12-204057_668x691_scrot](https://user-images.githubusercontent.com/345559/87269080-f98f5680-c480-11ea-881c-fbe8101ac6ff.png)

I choose the "ubuntu-like" versioning: <year>.<month>.<increment>. 
Hope it helps!

**Comment by ikaruswill** [comment]
Hey @bastienwirtz, thanks for this, I just saw the versioned docker images. Will close this issue then.
Appreciate your work!
