### ISSUE TITLE
[Question] Is it possible to fetch services.items from an API endpoint??

### ISSUE THREAD

**Issue by JeanCHilger** [bastienwirtz/homer#109]
I would like to use HOMER to show a list of items that will be returned by an API made with Laravel.

Is possible to update the items from `services.items` in `config.yml` using such API? Or maybe use another file (e.g. `.html`) as the items list?

**Comment by fbartels** [comment]
Hi @JeanCHilger,

there is already the option `externalConfig` in Homer to load the configuration from another url. Its explained in https://github.com/bastienwirtz/homer/blob/d1b9dea28707772fd45b60feaeebbc9f8dd66746/docs/configuration.md

**Comment by bastienwirtz** [comment]
I'm closing this as it should be all right, but feel free to reopen it if needed.
