### ISSUE TITLE
Title font cuts off long letters like 'g' and 'y'

### ISSUE THREAD

**Issue by calvinbui** [bastienwirtz/homer#114]
Letters like `g` and `y` are cut off

![image](https://user-images.githubusercontent.com/3604363/88364777-61ba3280-cdc7-11ea-87e6-5ada659b54ec.png)

Changing the line-height seems to fix it

![image](https://user-images.githubusercontent.com/3604363/88364846-9201d100-cdc7-11ea-8310-f1bc8bd97e69.png)

![image](https://user-images.githubusercontent.com/3604363/88364826-83b3b500-cdc7-11ea-8a1c-b0117c841e44.png)

**Comment by bastienwirtz** [comment]
Hi @calvinbui! 
Thanks for the feedback!
I just fixed it in master, will be shipped in next release.
