### ISSUE TITLE
[Feature] Change default theme and layout from config

### ISSUE THREAD

**Issue by 33Fraise33** [bastienwirtz/homer#121]
Hi,

It would be nice to be able to change the default layout (collumns or rows) & default color scheme from the config file.

Every new device you open the page on will resort to the default settings while it might be easier to have a default in config.

**Comment by bastienwirtz** [comment]
Hi @33Fraise33! 
That would be nice, I'll look into it :+1:

**Comment by taigrr** [comment]
You can already set the theme in the config file, but I'm working on a PR to enable columns vs. rows right now.
