### ISSUE TITLE
[Feature] Easily allow change of favicon

### ISSUE THREAD

**Issue by 33Fraise33** [bastienwirtz/homer#122]
Hello,

Having the favicon match the logo in the header would be a nice adition. In the folder icons we have all the icons, but there are a lot of resolutions, so manually changing that is a lot of work.

**Comment by brandoncorry** [comment]
While not super easy, or built in - you can easily grab whatever logo you have changed to, and run it through this site: https://realfavicongenerator.net/ to generate all the assets and place them in \assets\icons

**Comment by bastienwirtz** [comment]
Hey @33Fraise33, 
Thanks for reporting this. The icon set as just been simplified: https://github.com/bastienwirtz/homer/tree/main/public/assets/icons
Also, as mentioned by @brandoncorry, there are a lot of great icon generator out there, another one is mentioned in the documentation: https://github.com/bastienwirtz/homer/blob/main/docs/configuration.md#pwa-icons

I'm closing the issue, feel free to reopen it if necessary :)

**Comment by auanasgheps** [comment]
Hello, I've got trouble in changing the PWA icon/.
I have used https://realfavicongenerator.net/, which successfullu changes the standard icon/favicon of the website.

However, when I want to add the website as shortcut, therefore a PWA, it shows the stock Homer icon. This happens on all platforms I tested: iOS, Android, Windows.

Apparently these tools don't make the following icons present in Homer:
- icon-any.png
- icon-any.svg
- icon-maskable.png

But even if I do replace them, **deleting** all original icons, it still shows the Homer logo. What am I doing wrong?

**Comment by Starker3** [comment]
I'm having a similar issue as @auanasgheps 
I've replaced the favicon and all other icon files in the /icons folder.
When loading homer in a new browser tab, the original homer favicon is originally loaded. Ctrl+F5 reloading the page causes the correct favicon to load.

However, this cannot be done on mobile, so adding the homer dashboard link as a bookmark on a mobile homescreen doesn't use the favicon or logo from the /icons folder.

**Comment by fbartels** [comment]
> When loading homer in a new browser tab, the original homer favicon is originally loaded. Ctrl+F5 reloading the page causes the correct favicon to load.

this is because these files get cached by the service worker

**Comment by k4j8** [comment]
@Starker3 I got custom icons working on mobile by copying `android-chrome-512x512.png` to `icon-any.png`.

```bash
$ npx vue-pwa-asset-generator -a {your_512x512_source_png} -o {your_output_folder}
$ cp android-chrome-512x512.png icon-any.png
```

**Comment by Starker3** [comment]
> @Starker3 I got custom icons working on mobile by copying `android-chrome-512x512.png` to `icon-any.png`.
> 
> 
> 
> ```bash
> 
> $ npx vue-pwa-asset-generator -a {your_512x512_source_png} -o {your_output_folder}
> 
> $ cp android-chrome-512x512.png icon-any.png
> 
> ```

Thanks for the tip. I already had all of the correct fav icons setup using a fav icon generator that correctly generates fav icons for all platforms)

The issue I had was that the service worker on the browser had the previously set fav icons cached. Clearing the service workers cache fixed the issue.

**Comment by auanasgheps** [comment]
> 
> 
> > @Starker3 I got custom icons working on mobile by copying `android-chrome-512x512.png` to `icon-any.png`.
> > ```shell
> > $ npx vue-pwa-asset-generator -a {your_512x512_source_png} -o {your_output_folder}
> > 
> > $ cp android-chrome-512x512.png icon-any.png
> > ```
> 
> Thanks for the tip. I already had all of the correct fav icons setup using a fav icon generator that correctly generates fav icons for all platforms)
> 
> The issue I had was that the service worker on the browser had the previously set fav icons cached. Clearing the service workers cache fixed the issue.

How have you fixed this on mobile?

**Comment by virtadpt** [comment]
Editing the HTML directly after the fact is also possible, though it gets wiped out with every update.
