### ISSUE TITLE
[Bug] PWA not working in Firefox

### ISSUE THREAD

**Issue by tpansino** [bastienwirtz/homer#124]
I'm trying to save the app as a PWA on my Pixel 3A XL, running Android 10 August security patch, using Firefox 68.11.0.

The PWA save icon shows up at the top of the browser as expected. Tapping it shows the save confirmation pop-up, however the Homer icon is missing. Tapping Save then does nothing except close the pop-up.

I'm happy to provide screenshots on request, however I suspect this will be easy to reproduce.

Edit: I'm not a frontend developer, but I have encountered issues with PWAs like this before, and it had something to do with the Vue configuration. Maybe we start by checking that?

**Comment by bastienwirtz** [comment]
Hi @tpansino, thanks for opening the issue, I will check that asap!

**Comment by bastienwirtz** [comment]
Hi @tpansino, 
Sorry for delay. That should be fixed thanks to @NotWoods's [great work](https://github.com/bastienwirtz/homer/pull/127), it will included in a tagged release soon.
