### ISSUE TITLE
Maskable icon and iOS icon are too big and transparent

### ISSUE THREAD

**Issue by NotWoods** [bastienwirtz/homer#126]
The current maskable icon is just a copy of the normal icon. Maskable icons need the important content to be within the inner 80% of the image, and should be opaque rather than transparent.

Currently the icon [looks like this on a home screen](https://maskable.app?demo=https://raw.githubusercontent.com/bastienwirtz/homer/master/public/assets/icons/android-chrome-maskable-512x512.png)

I think both the maskable icon and iOS icon would look better if the gradient was applied to the entire background, not just the donut outline.

**Comment by bastienwirtz** [comment]
Hey @NotWoods does this one is resolved with https://github.com/bastienwirtz/homer/pull/127 ?

**Comment by NotWoods** [comment]
Yup!
