### ISSUE TITLE
Container not reading from config.yml on restart

### ISSUE THREAD

**Issue by ImjuzCY** [bastienwirtz/homer#128]
Whenever I edit the config.yml, I have to stop, remove, and recreate the container for homer to reload the config. Simply restarting it will not update it. IMO it should reread config.yml every time on restart, instead of just once on creation of the container.

**Comment by hot22shot** [comment]
Hi, I've just installed it on docker (on a synology) and I have no issue modifying the config.yml, hitting F5 is enough to see any change.
