### ISSUE TITLE
Make navbar responsive (toggle into hamburger menu on mobile)

### ISSUE THREAD

**Issue by twolaw** [bastienwirtz/homer#13]
Instead of hiding on mobile, it would be interesting that navbar-menu toggles into navbar-burger.

Bulma documentation : https://versions.bulma.io/0.7.0/documentation/components/navbar/

**Comment by bastienwirtz** [comment]
Hi @twolaw!
Thanks for opening an issue. It would be nice to have a narbar-burger. I've some stuff I want to do before but I keep that in my todo list!

**Comment by bastienwirtz** [comment]
Hi there! just merged @traeblain's PR that bring the navbar-burger, enjoy!
