### ISSUE TITLE
Using SSL with Homer

### ISSUE THREAD

**Issue by jtovar43** [bastienwirtz/homer#130]
I was just wondering how I would go about adding SSL to the Dashboard. Thanks!

**Comment by fbartels** [comment]
Are you using the Docker image? If yes then you would/could add a reverse proxy to provide ssl. If you are just using the static assets then Homer is just like any other static website (choose your own webserver and secure it with ssl).

**Comment by jtovar43** [comment]
Thanks! I got it working with a reverse proxy. Didn't know you could do that.

**Comment by J7mbo** [comment]
Thanks @Alevsk . This still works in 2026. I don't want to "just use a reverse proxy" because I want true End-to-End L7 Encryption in my cluster and don't want to terminate at say Traefik. Appreciate you finding this!
