### ISSUE TITLE
White flash with dark theme

### ISSUE THREAD

**Issue by tborychowski** [bastienwirtz/homer#132]
When I switch on "Dark theme" and reload the page - there is a flash of white, because of this:
<img width="257" alt="Screenshot 2020-10-05 at 22 56 21" src="https://user-images.githubusercontent.com/392513/95136428-ff35c900-075d-11eb-9bab-547051a5ded9.png">

Can the `background-color` of `html` element be set to the same as the theme?

**Comment by bastienwirtz** [comment]
Hey @tborychowski 
Thanks for reporting this. Seems that `Bulma` set a default color on the `html` element, I just pushed a [commit](https://github.com/bastienwirtz/homer/commit/67fd101a38baf3e7634c494eb286a671685a76b6) to fix that, but I'm not entirely sure it solves your white flash issue. Let me know how it goes for you, 

Thanks!

**Comment by tborychowski** [comment]
Thanks for that. But I run this in a docker, so not exactly sure how to easily test this...

**Comment by simonporte** [comment]
I checked, the calculated property of background color, it is set as rgb(19,19,19), but there is a white flash.
To my understanding, this is expected behavior : as long as your browser ships with a white `about:blank` page there will be a white flash.
@tborychowski There is automated builds : when there is a commit on github, there is also a new image on docker hub

**Comment by tborychowski** [comment]
I just checked the latest build and you're right - the white flash is still there.

> as long as your browser ships with a white about:blank page there will be a white flash.

This part, however, is incorrect.
I have plenty of apps & websites that are dark (or can be set to dark, or use OS via `prefer-` media query) that do not flash.

Maybe the problem is the way Homer loads css & js?
e.g. if I disable js on Homer's page - there's the white page with `<noscript>` message.

I experimented a bit by changing the code inside the container directly, and the flash disappears, when I put sth. like this to the `index.html` in the `<head>` section:
```html
<style>
html, body { background: #111; }
:root {--background: #111; }
</style>
```
First line overwrites the the browser default colours, while second provides the css variable to the css that's using it.
The problem is that the css file that's using the variable is loaded before the variables are provided (loaded with javascript?).

**Comment by Caesar2011** [comment]
You could integrate css media querys to check which color scheme the user prefers on his system and set the pre-js setting accordingly.

**Comment by bastienwirtz** [comment]
@Caesar2011 that's pretty much what it already does, media queries are used to determine user preference, but colors are not hardcoded, it's defined in the yaml configuration file, parsed with js. 
I think I can hardcode dark colors to apply before the js is ready (the flash will still be there, but less noticeable), and see if I can do the color parsing more early in the javascript.
I'll look into it soon.
