### ISSUE TITLE
The `src` in the docker image `manifest.json` is wrong

### ISSUE THREAD

**Issue by jmlemetayer** [bastienwirtz/homer#133]
In the `manifest.json` file which is in the docker image the `src` have an extra `img/` path which does not exist in the real path which leads to a 404 error. Thus the app have no favicon.

Here is the error I get in chrome:
```
GET https://home.example.com/assets/img/icons/android-chrome-192x192.png 404

Error while trying to use the following icon from the Manifest: https://home.example.com/assets/img/icons/android-chrome-192x192.png (Download error or resource isn't a valid image)
```

The correct url is https://home.example.com/assets/icons/android-chrome-192x192.png (without the `img/`).

Here is the production `manifest.json`:
```
$ docker exec nostromo-docker_homer_1 cat /www/assets/manifest.json | jq .
{
  "name": "Homer Dashboard",
  "short_name": "Homer Dashboard",
  "theme_color": "#4DBA87",
  "icons": [
    {
      "src": "./img/icons/android-chrome-192x192.png",
      "sizes": "192x192",
      "type": "image/png"
    },
```

Also here is [the file in the `public` directory](https://github.com/bastienwirtz/homer/blob/master/public/assets/manifest.json):
```
{
  "name": "Dashboard",
  "short_name": "homer",
  "theme_color": "#3367D6",
  "icons": [
    {
      "src": "./assets/icons/android-chrome-192x192.png",
      "sizes": "192x192",
      "type": "image/png"
    },
```

**Comment by jmlemetayer** [comment]
Maybe related to #124 and #127.

**Comment by bastienwirtz** [comment]
Hi @jmlemetayer, 
Thanks for reporting this! That should be fixed thanks to @NotWoods's [great work](https://github.com/bastienwirtz/homer/pull/127), it will included in a tagged release soon.

I'm closing the issue, but feel free to reopen it if anything.
