### ISSUE TITLE
License not properly applied

### ISSUE THREAD

**Issue by taigrr** [bastienwirtz/homer#142]
The repo has a LISCENSE file, but the instructions at the bottom on how to apply the license to the project have not been followed.

> You should include a copy of the Apache License, typically in a file called LICENSE, in your work, and consider also including a NOTICE file.
> 
> To apply the Apache License to specific files in your work, attach the following boilerplate declaration, with the fields enclosed by brackets "[]" replaced with your own identifying information. (Don't include the brackets!) The text should be enclosed in the appropriate comment syntax for the file format. We also recommend that a file or class name and description of purpose be included on the same "printed page" as the copyright notice for easier identification within third-party archives.

This is probably not a huge deal, and if some legal issue came up the law would likely still come down on your side, but it's nice to cover your bases properly :smile:

**Comment by bastienwirtz** [comment]
Good catch @taigrr, thanks!
