### ISSUE TITLE
Feature Request: Click tag to filter

### ISSUE THREAD

**Issue by taigrr** [bastienwirtz/homer#148]
I think it would be nice if you could click on the tag for a service and have the filter automatically filter to all the tagged services.

Is this a feature others would find useful?

**Comment by taigrr** [comment]
@fbartels check it out!

**Comment by jo-me** [comment]
Check this out: https://github.com/bastienwirtz/homer/issues/165

Not 100% what you are suggesting, but with link items based on your tags, it is close ;)
