### ISSUE TITLE
config.yml file

### ISSUE THREAD

**Issue by goncaloCB** [bastienwirtz/homer#15]
I edit config.yml file but i can't see any changes. am i missing something ?

**Comment by bastienwirtz** [comment]
Hi @goncaloCB, 

That's probably the service worker cache, it's a known issue, I'll fix it soon. In the meantime try to clear your browser cache and if necessary force the service worker update (for exemple in Chrome: Go to dev tools > Application > service worker, and click on "Update" or "Unregister"). You can also try in private navigation. 

![2020-02-07-121032_970x285_scrot](https://user-images.githubusercontent.com/345559/74062333-e2fd4480-49a2-11ea-8399-11a0bbf6d4b6.png)

**Comment by yangkghjh** [comment]
Shift+F5, if you are using Windows.

**Comment by andrewwiebe** [comment]
Following as I would love to see this issue fixed.

**Comment by bastienwirtz** [comment]
Hi there!
@goncaloCB @andrewwiebe, just pushed a commit that remove the config file from the worker cache, it should help with this issue. Can you tell me if that's work for you?

**Comment by andrewwiebe** [comment]
For updating is it just a matter of overwriting everything and putting back our config file on top?

**Comment by andrewwiebe** [comment]
I overwrote my existing files with the update, with the exception of my config file and cleared the browser cache but am still having the issue. 

Where is code change that should correct this? I just want to make sure I have the correct files my server.

**Comment by bastienwirtz** [comment]
@andrewwiebe It's there: https://github.com/bastienwirtz/homer/commit/4b87511f28b2d7b8b85bb07ffe6c9909c141acd6#diff-8a5b5909f5b3ce1a25a1c499ab30da2cL9

Truth is, your worker.js is probably cached too. That because of the lack of build system (each new release should have unique ressource URL to avoid all of that, I plan to fix that soon).

**Comment by andrewwiebe** [comment]
Nope sorry, this was my fault made a stupid mistake when copying the files. It looks like it is working!

Thanks so much.

**Comment by bastienwirtz** [comment]
Cool! Thanks for the feedback @andrewwiebe!
