### ISSUE TITLE
Feature request : Secure Home dashboard access

### ISSUE THREAD

**Issue by Djf2884** [bastienwirtz/homer#157]
Just a request to see some authentication feature in order to secure link on the dashboard.

Thx you :)

**Comment by taigrr** [comment]
Put it behind NGINX, and use a reverse-proxy.

See also, #130

**Comment by ArbiterGR** [comment]
To add to this, Use authelia with nginx and you can even have 2fa!

**Comment by bastienwirtz** [comment]
Hi @Djf2884 !

There is no plan to add authentication into Homer. As pointed out by @taigrr & @ArbiterGR, there are a lot of solutions (like https://github.com/vouch/vouch-proxy) out there that will do the job. Homer is a pure static webapp, there is no database or any server logic.

**Comment by PartTimeDataScientist** [comment]
My setup with Traefik and Authelia works in principle but I have an issue that I think has to to with Homer being an SPA with caching. Everything works as expected on the 1st accees. If however I have accessed Homer once (e.g. from my internal lan which does not require authelia login) the 302 redirect to the authelia is not followed but the "You're offline friend" message is shown.

Did you experience something like this with nginx as well or is there something I could have misconfigured in my Homer config?

**Comment by sheeepdev** [comment]
Could anyone point me to setting up a reverse proxy for homer? I searched around but I don't really understand.

**Comment by petrleocompel** [comment]
@PartTimeDataScientist have you found any good solution for SPA problems ?

 I am in that state currently.
