### ISSUE TITLE
Docker image update

### ISSUE THREAD

**Issue by simonporte** [bastienwirtz/homer#158]
Hello,

It seems docker images are no longer build on docker hub, the latest image is 20 days old.

Can you update it ?

Thanks.

**Comment by jensihnow** [comment]
Same here, would appreciate a new docker image with latest. Thx!

**Comment by bramceulemans** [comment]
It seems the PiHole service feature is not yet in the Docker image.

**Comment by shamoon** [comment]
> It seems the PiHole service feature is not yet in the Docker image.

Ha yes I can't believe how long it took me to realize this is why its not working 😂

**Comment by bastienwirtz** [comment]
Hi there! 
My bad! there you go: https://github.com/bastienwirtz/homer/releases/tag/v20.11.28

:v:

**Comment by bramceulemans** [comment]
Thanks :)

**Comment by jensihnow** [comment]
Apparently latest tag did not move yet.
In case you would were looking for the Pi.Hole services extension you need to make sure to pull the tag and not latest.

**Comment by bastienwirtz** [comment]
Hi there, 
Good catch, It should be all good now! I forgot to update the docker build trigger branch name after rename this repo base branch from master to main.
Thanks!

**Comment by simonporte** [comment]
It should be good now :

![image](https://user-images.githubusercontent.com/32496803/101524643-7c620200-398a-11eb-9e19-7050c1d0a467.png)

Closing the issue.
Thanks.
