### ISSUE TITLE
Feature Request: Personal Items

### ISSUE THREAD

**Issue by dwlyles** [bastienwirtz/homer#168]
This has been great so far. I was looking to see if there is a way to add a small calendar and a open text location for small todo's or notes.

If this is already possible. Could someone point me into the direction that i should look at.

**Comment by bastienwirtz** [comment]
Hi @dwlyles! 
There is no feature like that right now, but if you have JS coding skills, It's possible to add custom service cards with custom logic and UI. Take a look [here](https://github.com/bastienwirtz/homer/tree/main/src/components/services), The PiHole service is a basic example of how to define a custom card. 
Regarding the UI, all [bulma elements](https://bulma.io/documentation/) are loaded & available is you need it. I need to add a section in the documentation to describe how to add custom services. 

Would it cover your needs?
If you want your custom services to be integrated to the code base, try to avoid adding more dependencies to the project (if we end up with many custom services loading their own library, we will have performances issues). 
Let me know if you need more information!

**Comment by dwlyles** [comment]
Thank you for that info. I'll definitely look into what i can. 
I'm not too skillful, so im sure i wont be adding too many dependencies.
