### ISSUE TITLE
White Bar at bottom when removing footer

### ISSUE THREAD

**Issue by mokshmridul** [bastienwirtz/homer#17]
Hi,

Thank you for the amazing work.

If i try to remove the footer by removing the below lines, the page ends up with a white bar the bottom when using the Dark Theme. How can i get rid of this bar?

File Modified : Index.html
Lines Removed:
````    <footer class="footer">
        <div class="container">
          <div class="content has-text-centered">
            <p>Created with <span class="has-text-danger">❤️</span> with <a href="https://bulma.io/">bulma</a>, <a
                href="https://vuejs.org/">vuejs</a>
              & <a href="https://fontawesome.com/">font awesome</a> // Fork me on <a href="https://github.com/bastienwirtz/homer"><i
                  class="fab fa-github-alt"></i></a></p>
          </div>
        </div>
      </footer>

**Comment by bwirtz** [comment]
Hey @mokshmridul did you find a solution? Just so you know, I plan to make the footer optional based on a key in the `config.yml` at some point!

**Comment by mokshmridul** [comment]
Hey @bwirtz Thanks for the comment. I did manage to find a solution by making the footer the same color as the rest of the page.

The idea of making it a key sounds great. In addition to that, may i also suggest that the tabs open in a new tab if possible?

**Comment by goliath888** [comment]
Is there any way to hide the footer completely? Even with the same color as the background, when you scrolldown, the footer is there and I did not find any way to remove it.

**Comment by bastienwirtz** [comment]
@mokshmridul, @goliath888 the footer is now a setting in `config.yml`: 
https://github.com/bastienwirtz/homer/blob/master/config.yml#L9

You can use any content, html enabled, or just set it to `false` to hide it entirely. Let me know if any troubles. Cheers!

**Comment by mokshmridul** [comment]
> @mokshmridul, @goliath888 the footer is now a setting in `config.yml`:
> https://github.com/bastienwirtz/homer/blob/master/config.yml#L9
> 
> You can use any content, html enabled, or just set it to `false` to hide it entirely. Let me know if any troubles. Cheers!

Just tried it, and it works great. Thanks a ton :)

**Comment by goliath888** [comment]
> @mokshmridul, @goliath888 the footer is now a setting in `config.yml`:
> https://github.com/bastienwirtz/homer/blob/master/config.yml#L9
> 
> You can use any content, html enabled, or just set it to `false` to hide it entirely. Let me know if any troubles. Cheers!

Already with it, thanks for the work!
