### ISSUE TITLE
Enter in empty search opens first item

### ISSUE THREAD

**Issue by jo-me** [bastienwirtz/homer#171]
When pressing the return button in an empty search field, the first item is opened.
I know it is a feature of the search that the first result is opened on pressing the return button, but with an empty box it feels kind of strange.

Is this on purpose?

**Comment by bastienwirtz** [comment]
Good catch @jo-me, that's not on purpose. I'll look into it. 
Thanks for reporting this :+1:

**Comment by bastienwirtz** [comment]
Fixed & released @jo-me, cheers :v:
