### ISSUE TITLE
Tag on a card is not indented correctly since version 20.11.28

### ISSUE THREAD

**Issue by CuBiC3D** [bastienwirtz/homer#173]
The tags on the card are indented to the right to see the color if the mouse does not hover over a card and get extended on hover.

This behaviour is is not there anymore since version 20.11.28 up to the latest (tested on Chrome and Firefox). The tag "preview" is not visible since the `.card` class now uses `overflow: hidden`.

It this an intended change or a bug? I think it is very useful to have this preview.

Yes, I am aware that I can use my own styling, but since this behaviour is still on screenshots and the demo page, I assume it is not intended.

![Screenshot from 2020-12-19 00-28-07](https://user-images.githubusercontent.com/4047015/102672456-1f87f800-4191-11eb-901a-7d28da9d1b6a.png)
![Screenshot from 2020-12-19 00-27-50](https://user-images.githubusercontent.com/4047015/102672458-20b92500-4191-11eb-86e9-527a449c49cc.png)

**Comment by bastienwirtz** [comment]
Hi @CuBiC3D, 
That's definitely a bug, thanks for reporting this! I'll look into it.

**Comment by bastienwirtz** [comment]
Fixed & released @CuBiC3D, cheers :v:
