### ISSUE TITLE
Weather service

### ISSUE THREAD

**Issue by Baitinq** [bastienwirtz/homer#180]
It would be really cool if there was a weather service in homer. I might get around implementing it one of these days but if anyone else has one already and is willing to share it would be extremely cool!

**Comment by dickwolff** [comment]
I second this suggestion, and I went on and created something. See the image below. Is this something you were looking for?

![image](https://user-images.githubusercontent.com/5620002/104301668-32f45d80-54c8-11eb-8f70-56af9bd02c30.png)

I used the OpenWeatherMap API and added a few configuration options (like api key, location, units). The image is retrieved from OWM based on the image code ([per documenration](https://openweathermap.org/weather-conditions#Icon-list)).

**Comment by bastienwirtz** [comment]
Hello! 

Nice idea! 
@dickwolff would you be open to share your implementation by submitting a PR to add the custom service to the collection?

**Comment by dickwolff** [comment]
Yeah sure! I'll open a PR and link this issue.

**Comment by dickwolff** [comment]
I've created an initial PR. Need to finish up some checks and I have one question about the URL which I would like your opinion on @bastienwirtz

**Comment by Baitinq** [comment]
@dickwolff this is exactly what i was looking for. Thanks for your work
