### ISSUE TITLE
Feature Request : Material Design icon

### ISSUE THREAD

**Issue by hot22shot** [bastienwirtz/homer#182]
Hi,

Great app ! I wonder if it would be possible to also use the icons from Material Design (https://materialdesignicons.com/) ?

Thx

**Comment by oldviking** [comment]
That would be really cool, because not every icon is free on the solution now.

**Comment by bastienwirtz** [comment]
Hi there,
Thanks for contributing! Having Material icons would be great, I will look into it. We should have an option to use different icon set (and avoid loading unused icon library). I'll keep you posted here!

Best

**Comment by dkgof** [comment]
It does kinda work already, if you add the webfont css from material design as a custom stylesheet in the config:

`stylesheet:
  - "https://cdn.jsdelivr.net/npm/@mdi/font@5.9.55/css/materialdesignicons.min.css"
`

And then you can use it for icons:

`icon 'mdi mdi-home`

**Comment by hot22shot** [comment]
It does indeed work !

**Comment by xbmcnut** [comment]
👍 Thank you. As a Home Assistant user I was much more comfortable using MDI. Works a treat. Noted that code should be this though:
```
icon: "mdi mdi-home"
```
