### ISSUE TITLE
Feature request: automatic darkmode switch

### ISSUE THREAD

**Issue by LeLunZ** [bastienwirtz/homer#183]
Thx for your homer! 
Tried it today for the first time. And I really love the design and functionality. 

I use MacOs with auto switch between day and night. 
Github etc. can automatically switch between the dark-lightmode.

Is this possible to implement as an option (config.yaml) or a function in the app?

**Comment by zkmusa** [comment]
I would also be very interested in this!

**Comment by virtadpt** [comment]
Funnily enough, I'd be interested in this, too.  I keep switching from light mode to dark mode depending on whether it's day or night.

**Comment by bastienwirtz** [comment]
Hi there, 

Thanks for the feedback! It's actually supposed to be automatic, unless you use the button to override it. But that make me realize that If you used the button once, there is no way to get back in auto mode! I will think about that. 
Could that be your case? Preferences are stored in local the browser local storage, can you try to clear the local storage to confirm the auto mode works? You can use the dev tool (see screenshot below), clear cache / app data or try in private nav.

![2021-02-15-220222_715x227_scrot](https://user-images.githubusercontent.com/345559/108024847-381e5e00-6fda-11eb-99c3-3cd7218670a1.png)

**Comment by pdevq** [comment]
Interesting problem. Here is an idea:

Change the button from a toggle to having three states: `auto`, `dark`, `light`. With `auto` being the default if nothing has been set in local storage. Clicks on the button iterate over the modes and save them into local storage. 

| Button                                                                                                                                               | Possible New Key                           | Keep Old Key                                       |
|------------------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------|----------------------------------------------------|
| <img alt="auto" src="https://user-images.githubusercontent.com/45507854/108156151-260def80-70ae-11eb-9ad4-8c23f52f338f.png" width="40" height="40">  | `mode: auto`<br>*(default if nothing set)* | `overrideDark: null`<br>*(default if nothing set)* |
| <img alt="dark" src="https://user-images.githubusercontent.com/45507854/108156153-260def80-70ae-11eb-8f03-6a79ffcdfef8.png" width="40" height="40">  | `mode: dark`                               | `overrideDark: true`                               |
| <img alt="light" src="https://user-images.githubusercontent.com/45507854/108156155-260def80-70ae-11eb-9242-bf4bed8ae125.png" width="40" height="40"> | `mode: light`                              | `overrideDark: false`                              |

**Comment by GaaH** [comment]
Since nobody seem to disagree with @pdevq’s proposal,  I made a pull request to fix this.
