### ISSUE TITLE
Reworking Docker script for Installation

### ISSUE THREAD

**Issue by t0xic0der** [bastienwirtz/homer#185]
The current Docker script lacks restart options.
```
docker run -p 8080:8080 -v /your/local/assets/:/www/assets b4bz/homer:latest
```

It is recommended to change it to the following.

```
docker run -d \
  -p 8080:8080 \
  -v homer-assets:/www/assets \
  --restart=unless-stopped \
  b4bz/homer:latest
```

or 

```
docker run -d \
  -p 8080:8080 \
  -v homer-assets:/www/assets \
  --restart=always \
  b4bz/homer:latest
```

to make it persist throughout server reboots.

**Comment by bastienwirtz** [comment]
Hi @t0xic0der, 
Thanks for the suggestion! There you go: https://github.com/bastienwirtz/homer/commit/9ba0d54e2213b2a4313a92390d5ce06dbf7b6a63

**Comment by t0xic0der** [comment]
Awesome. :smile:
