### ISSUE TITLE
[Feature Request] Multiple users

### ISSUE THREAD

**Issue by Razva** [bastienwirtz/homer#187]
I would be awesome if you could add the option of having multiple users, each of them having their own Dashboard.

**Comment by pdevq** [comment]
If #177 gets merged it could be used to achieve something in that manner. Using the main page (`http://localhost/`) as portal for all users and than each user page located at `http://localhost/#user1` etc. The exact details obviously still pending.

**Comment by bastienwirtz** [comment]
Hi there!

There is no user management, but the solution proposed by @pdevq can work, #177  has been merged, and it's now possible to defined multiple dashboard pages.  Could that work for you @Razva ?

Homer is (and will stay) a static webpage, with no database or any server logic. So I don't think anything else could be done for this use case.

**Comment by Razva** [comment]
Is there any way to at least add a simple password, even without a username and even if it's plain text or with basic encryption?

**Comment by mguaylam** [comment]
@Razva the login was addressed in another issue. There will be none. It's meant to be reversed proxied by NGINX or Træfik. Then, you can put a login front end like Authelia (I love it)

**Comment by Razva** [comment]
Ok so basically we can't add a simple password "login" option and we have to do it via the HTTP daemon. Still, would it be "impossible" to do it, or does it break any of Homer's principles?

**Comment by mguaylam** [comment]
@Razva I mean, i don’t even think that Homer supports TLS so any login would be insecure.

**Comment by Razva** [comment]
> @Razva I mean, i don’t even think that Homer supports TLS so any login would be insecure.

I totally agree, but at least it'll be more than nothing?

**Comment by pdevq** [comment]
> > @Razva I mean, i don’t even think that Homer supports TLS so any login would be insecure.
> 
> I totally agree, but at least it'll be more than nothing?

Homer is just a static website not a webserver (nginx, apache) and won't even function without the latter as modern browser don't play well with `js` and `file://` (CORS). TLS is done by the webserver you are connecting to. Homer is (are) just the static website files that you receive (via TLS if the webserver does it).

For prober auth you need a backend (e.g. the webserver) to handle the auth process. Homer is transferred as a whole and if it were to do any auth, one could simply modify the `js` locally to bypass it. While there are obfuscation techniques to make this harder, at the end this is a somewhat pointless endeavor and goes way beyond the scope of Homer as mentioned in #192.

As an idea for a makeshift user login via nginx:
Use the `${remote_user}`  environment variable set on auth by nginx and return the appropriate `yml` configuration based on the users name (e.g. `assets/config_user1.yml` or `assets/page2_user1.yml`)
```nginx
# the following is untested, use at own discretion
# this should match */assets/*.yml, work with subdir deployment and multipages with _someuser suffix
location ~ ^(.*/assets/[^\./]*)\.yml$ {
    # using basic auth via file
    auth_basic_user_file /etc/nginx/nginx_conf/htpasswd;
    # return user specific yml or default if it doesn't exist
    try_files $1_${remote_user}.yml$is_args$args
              $1.yml$is_args$args
              =404;
}
```

**Comment by Razva** [comment]
> If #177 gets merged it could be used to achieve something in that manner. Using the main page (`http://localhost/`) as portal for all users and than each user page located at `http://localhost/#user1` etc. The exact details obviously still pending.

For reasons described above this seems to be the best solution for this use case, plus login via nginx/apache.

**Comment by itsmejoeeey** [comment]
I recently solved this for myself, and wanted to put my solution out there in case it helps others.

**These instructions are only really helpful in setups that make sure of an authentication proxy, such as `oauth2-proxy`.** In my case `oauth2-proxy` is what will set the `REMOTE-USER` header that gets read by the `homer` webserver below.

Following @pdevq's suggestion to handle this at the webserver / reverse-proxy level, I instead mounted an altered `lighttpd` configuration into the `homer` container. This is great because it means this solution doesn't require implementing an additional web server.

`lighttpd.conf`
```
include "/etc/lighttpd/mime-types.conf"
include_shell "/etc/lighttpd/ipv6.sh"

server.port            = env.PORT
server.modules         = ( "mod_alias" )
server.username        = "lighttpd"
server.groupname       = "lighttpd"
server.document-root   = "/www"
alias.url              = ( env.SUBFOLDER => "/www" )
server.indexfiles      = ("index.html")
server.follow-symlink  = "enable"
server.feature-flags  += ( "server.clock-jump-restart" => 0 )

# THIS IS THE CUSTOM ADDITION
# Respond with different conf depending on request header / user
server.modules += ("mod_redirect", "mod_rewrite")
$HTTP["url"] =~ "^/assets/config.yml" {
    # Check if Authenticated by proxy
    $REQUEST_HEADER["REMOTE-USER"] =~ "bob" {
        url.rewrite-once = ( "^/assets/config.yml" => "/assets/config.bob.yml" )
    } else {
        url.rewrite-once = ( "^/assets/config.yml" => "/assets/config.everyone.yml" )
    }
}
```

Now the webserver can return a different `config.yml` file (either `./assets/config.bob.yml` or `./assets.everyone.yml`) depending on the contents of the `REMOTE-USER` request header.

My `docker-compose` is as follows:
```
homer:
    image: b4bz/homer:v24.04.1
    ports:
      - 8080:8080
    environment:
      - INIT_ASSETS=0
    volumes:
      - ./assets:/www/assets:ro
      - ./lighttpd.conf:/lighttpd.conf:ro
```
