### ISSUE TITLE
How to build HTML files?

### ISSUE THREAD

**Issue by alexislefebvre** [bastienwirtz/homer#189]
Hello, I just discovered this project and I'm wondering if it's possible to use Homer to build HTML files?

Something like this:

```
docker run -v $PWD/assets/:/www/assets -v $PWD/output/:/www/output b4bz/homer:latest build
```

It would compile the files then stop, and assets would be available in the `output/` directory, then my web server could serve them, without having to run the Homer server.

**Comment by pdevq** [comment]
Homer is not for building arbitrary HTML files. However if you're asking how to get the static files to use them for your webserver (or rebuild from source):

The `b4bz/homer` image already contains the prebuild website. It does not include any build tools. You could extract it:
```bash
docker run --rm -it -v $PWD/output:/output --entrypoint /bin/sh b4bz/homer:latest -c 'cp -r /www/. /output/'
```
But you're probably better off downloading one of the [releases](https://github.com/bastienwirtz/homer/releases) instead.

If you want to build from source (to modify homer) with a container you can do something like this:
```bash
# configure output directory and owner (e.g. 33:33 for www-data)
OUTPUT_DIR=$PWD/output
OWNER=$(id -u):$(id -g)
# clone homer
git clone https://github.com/bastienwirtz/homer.git && cd homer
# build homer and copy it to the output directory
docker run --rm -v $PWD:/app -v $OUTPUT_DIR:/tmp/output --workdir="/app" node:lts-alpine /bin/sh -c "
yarn install --frozen-lockfile
yarn build
cp -r /app/dist/. /tmp/output/
chown -R $OWNER /tmp/output"
```
Note that `homer/dist` and `homer/node_modules` will be owned by `root`. Alternatively run the container with `--user $OWNER`. This user has to be able to write into `homer` and `$OUTPUT_DIR` (create the directories beforehand and change the ownership).

**Comment by alexislefebvre** [comment]
Thanks a lot! I didn't needed to build from source, using the Docker image worked and is more convenient.

I added this step in #190

**Comment by bastienwirtz** [comment]
Hi there, 

As mentioned by @pdevq, static builds are provided exactly for that purpose.  This link : https://github.com/bastienwirtz/homer/releases/latest/download/homer.zip will always point to the latest version.

That being said, if you want to build it yourself, I would suggest to build from the source, it's literally 2 commands (`yarn install && yarn build`), and if you don't want to have yarn installed, you can use the [docker node](https://hub.docker.com/_/node/) to execute the commands.

Best,

**Comment by alexislefebvre** [comment]
Thanks, I prefer to use the Docker image because it requires less steps and it works without having to install anything else.
