### ISSUE TITLE
Enable Docker Hub builds

### ISSUE THREAD

**Issue by calvinbui** [bastienwirtz/homer#19]
Since https://github.com/bastienwirtz/homer/pull/12 is finished, could you enable Docker Hub builds for this project?

Information: https://docs.docker.com/docker-hub/builds/

**Comment by bwirtz** [comment]
Hi @calvinbui! Yes It's planned, I'll look into it soon :+1:

**Comment by bastienwirtz** [comment]
Hi @calvinbui! Yes It's planned, I'll look into it soon :+1:

**Comment by bastienwirtz** [comment]
There you go: https://hub.docker.com/r/b4bz/homer :)

**Comment by mokshmridul** [comment]
Hi,

I tried this on Docker, and the config.yaml mount is fine. However, I cant figure how to mount the assets / logos, and hence they show up with a 404 on the page.

**Comment by bastienwirtz** [comment]
@mokshmridul I updated the documentation, you shoud be able to do it with something like: 
```sh
docker run -p 8080:8080 -v /your/local/config.yml:/www/config.yml -v /your/local/assets/:/www/assets b4bz/homer:latest
```

Let me know if that works for you.

**Comment by mokshmridul** [comment]
> ```shell
> /your/local/assets/:/www/assets
> ```

This worked great. Thanks a ton.
