### ISSUE TITLE
Some fab icons not showing

### ISSUE THREAD

**Issue by DaFlowah** [bastienwirtz/homer#191]
**Expected Behavior**
All the fab icons should show up correctly under the navbar

**Current Behavior**
Only the GitHub one is showing (tested with GitHub, Google and Reddit)
![image](https://user-images.githubusercontent.com/33235583/108046355-6d5b9800-703c-11eb-8c0e-f25507679f7d.png)

**Possible Solution**
🤔

**Steps to Reproduce**
![image](https://user-images.githubusercontent.com/33235583/108046163-3a190900-703c-11eb-8792-b8d05d5bbf99.png)

**Context (Environment)**
Docker on DSM and Docker on OMV (in a different network)

**Comment by auanasgheps** [comment]
Looks like this issue is automagically solved with the latest update.

**Comment by DaFlowah** [comment]
I'm stupid: it was my adblocker. And I'm still on the previous version.
