### ISSUE TITLE
Feature request: secure access with login ?

### ISSUE THREAD

**Issue by Fabeuss** [bastienwirtz/homer#192]
Is it possible to add the possibility to secure the page with a login?

**Comment by bastienwirtz** [comment]
HI @Fabeuss, 

There is no login system (and never will, as Homer it's 100% static html) but there are several options to achieve that. The most common would be to use your webserver or reverse proxy to handle authentication. One popular option is https://github.com/vouch/vouch-proxy, but there are many other (mod_auth_openidc for apache, oauth2-proxy, ...)

Hope it helps!

**Comment by Fabeuss** [comment]
Ok thank you for your answer. Actually I use synology's reverse proxy but I haven't found anything to add security or login for my containers...I'll try to understand how vouch-proxy works. Thanks ;)
