### ISSUE TITLE
[FR] Support docker --user switch

### ISSUE THREAD

**Issue by JuniorJPDJ** [bastienwirtz/homer#193]
Hi!
I'd like to run whole container as another user and I saw you are using user switch in entrypoint.
This is how redis added support for this: https://github.com/docker-library/redis/blob/master/6.0/docker-entrypoint.sh

**Comment by bastienwirtz** [comment]
Hi there !
Thanks for reporting this. The docker file has been reworked to run as a non-root user, hope it works for you! feel free to give your feedback.
