### ISSUE TITLE
Bug: PiHole stats arent showing

### ISSUE THREAD

**Issue by quotengrote** [bastienwirtz/homer#194]
Hi,

im trying to get the PiHole stats in Homer but they arent showing.

## docker-compose / repo
* URL: http://git.mgrote.net/mg/docker-homer
```
version: '3'
services:
######## homer ########
  homer:
    container_name: "homer"
    image: b4bz/homer:latest
    restart: always
    environment:
      - TZ=Europe/Berlin
      - UID=1000
      - GID=1000
    volumes:
      - ./assets/:/www/assets
    ports:
      - 333:8080


######## Volumes ########
volumes:
  homer-vol:

```

## Error in Browser
![Download](https://user-images.githubusercontent.com/38253905/109419614-a85fb300-79ce-11eb-94b1-89d09f342252.png)

TIA and let me know if you need more logs.

**Comment by simonporte** [comment]
I did not have the time to look more at it but same for me.
In my case it works only when the page is run locally (127.0.0.1).
If I run it on docker on a distant machine it does not show anymore.
Same with AdGuard integration I did from PiHole one.
No idea why.

**Comment by bastienwirtz** [comment]
Hi :wave: 

Your PiHole & homer instance are hosted on 2 different domains, and you got a [CORS errors](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors).

PiHole & AdGuard information are loaded using an ajax request and fall into the CORS problem. By default Ajax request are only authorized on the same origin domain (including port). [this security policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) are usually adjusted using these HTTP headers: 
```
Access-Control-Allow-Origin: http://foo.example
Access-Control-Allow-Methods: POST, GET, OPTIONS
Access-Control-Allow-Headers: Content-Type
```

In your case the first one (`Access-Control-Allow-Origin`) should be enough, you have to add this header on the PiHole side, maybe on your PiHole reverse proxy? @simonporte same for AdGuard!

**Comment by eltiel** [comment]
I have the same issue but I'm not using any domains. My PiHole is running on a separate VM from Homer. Homer references PiHole via local LAN IP e.g. Homer is on 192.168.0.1, PiHole is on 192.168.0.2.

How would the HTTP header fix above be applied?

**Comment by nodecentral** [comment]
Just adding my name to the list, as I don’t see any pi-hole stats either..

FYI - I have homer running via Docker, and Pi-hole running on a VM, both are on the same network/subnet.

**Comment by crwallace2** [comment]
I was able to resolve this by adding my host for Homer to the list of authorized hosts on the pihole in the below file

/var/www/html/admin/scripts/pi-hole/php/auth.php

in that file is an array called $AUTHORIZED_HOSTNAMES and is prefilled with pi.hole and localhost. I added my custom domain there.

**Comment by nodecentral** [comment]
Thanks @crwallace2 

ok, I’m in there, and found the file and section you were referring to and added my iP.

````
function check_cors() {
    $setupVars = parse_ini_file("/etc/pihole/setupVars.conf");
    $ipv4 = isset($setupVars["IPV4_ADDRESS"]) ? explode("/", $setupVars["IPV4_ADDRESS"])[0] : $_SERVER['SERVER_ADDR'];
    $ipv6 = isset($setupVars["IPV6_ADDRESS"]) ? explode("/", $setupVars["IPV6_ADDRESS"])[0] : $_SERVER['SERVER_ADDR'];

    // Check CORS
    $AUTHORIZED_HOSTNAMES = array(
        $ipv4,
        $ipv6,
        str_replace(array("[","]"), array("",""), $_SERVER["SERVER_NAME"]),
        "pi.hole",
        "localhost",
        "192.168.1.222"
    );

```

**Comment by eltiel** [comment]
> 
> 
> I was able to resolve this by adding my host for Homer to the list of authorized hosts on the pihole in the below file
> 
> /var/www/html/admin/scripts/pi-hole/php/auth.php
> 
> in that file is an array called $AUTHORIZED_HOSTNAMES and is prefilled with pi.hole and localhost. I added my custom domain there.

It works! Thanks!

**Comment by nodecentral** [comment]
I found out that by entering ‘su root’, it allowed me the permissions to change the auth.php file.

So I now have a green dot on the pi-hole tile, but no stats being reported ?

Please could someone share their yaml entry for pi-hole ?

**Comment by crwallace2** [comment]
> > I was able to resolve this by adding my host for Homer to the list of authorized hosts on the pihole in the below file
> > /var/www/html/admin/scripts/pi-hole/php/auth.php
> > in that file is an array called $AUTHORIZED_HOSTNAMES and is prefilled with pi.hole and localhost. I added my custom domain there.
> 
> It works! Thanks!
> 
> Edit: Unfortunately, this file gets reset every time Pi-Hole is updated.

I think I found a way that will survive an update to pihole.  In the auth.php script on the pihole side it checks for an environment variable called VIRTUAL_HOST and adds it to the $AUTHORIZED_HOSTNAMES array.  I discovered (through lots of trial and error) that in the pihole webserver (lighttpd is the default pihole webserver) there is a external.conf file that you can modify to add your own custom config  It is located in /etc/lighttpd and is named external.conf (the lighttpd.conf includes anything added to the external.conf)

I added the below to the external.conf  (domain.com is a placeholder for my actual domain that homer is on and the quotes are in the file as shown for both the variable name and domain)

setenv.add-environment = (
  "VIRTUAL_HOST" => "domain.com"
)

I then removed my edit to the auth.php, and rebooted the pihole and it still worked pulling the information from homer. 

the header of the lighttpd.conf file indicates the below, so I am pretty sure this change to external.conf will survive a pihole update, but I had updated before I figured this out so I cannot test it right now.
###############################################################################
#     FILE AUTOMATICALLY OVERWRITTEN BY PI-HOLE INSTALL/UPDATE PROCEDURE.     #
# ANY CHANGES MADE TO THIS FILE AFTER INSTALL WILL BE LOST ON THE NEXT UPDATE #
#                                                                             #
#              CHANGES SHOULD BE MADE IN A SEPARATE CONFIG FILE:              #
#                         /etc/lighttpd/external.conf                         #
###############################################################################

**Comment by eltiel** [comment]
@crwallace2  
Can confirm that the method above works, but the same as in your case am unable to test whether it will survive an update as I currently have no pending updates.

**Comment by quotengrote** [comment]
> the header of the lighttpd.conf file indicates the below, so I am pretty sure this change to external.conf will survive a pihole update, but I had updated before I figured this out so I cannot test it right now.

Works for me, and survived a pihole update. thx

**Comment by adyanth** [comment]
Changing the AUTHORIZED_HOSTNAMES does work, but I believe when pihole is updated, those changes do not stay. I guess this should be an issue with Pi Hole rather than homer, since CORS is handled by the browser and there is nothing homer can do.

**Comment by adyanth** [comment]
https://github.com/pi-hole/docker-pi-hole/pull/867 and https://github.com/pi-hole/AdminLTE/pull/1822 should provide a way to add homer domain to CORS_HOSTS environment variable as so:

```yaml
    environment:
      VIRTUAL_HOST: pihole.domain.com
      CORS_HOSTS: homer.domain.com,homer.local
```

**Comment by quotengrote** [comment]
Solved it this way, stays after Updates.

https://git.mgrote.net/mg/ansible/src/branch/master/playbooks/service/pihole.yml

**Comment by adyanth** [comment]
Ah, a selfhosted git + CI/CD with ansible is always a solution. Nice!

**Comment by quotengrote** [comment]
Probably not, but could bind-mount the files.

**Comment by adyanth** [comment]
Yeah, gotcha.

**Comment by dbrennand** [comment]
Just ran into this issue. 

After adding the header `Access-Control-Allow-Origin: http://dash.net.domain.tld` I'm getting the following error:

`SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data`

Any suggestions on troubleshooting this?

**Comment by danzkigg** [comment]
Hey guys,
I've followed the suggestions here and I still can't get the stats to show in the Homer Dashboard.

Currently Homer runs in Docker and PiHole in a VM.
I've added the Homer's IP to the list of `$AUTHORIZED_HOSTNAMES` but I still get this error:

> expected ‘true’ in CORS header ‘Access-Control-Allow-Credentials’

**Comment by adyanth** [comment]
As mentioned above, https://github.com/bastienwirtz/homer/issues/194#issuecomment-855826258, setting `CORS_HOSTS` environment variable fixes the issue. For docker based installs, this is the normal environment. 

For lighttpd based installs on the host OS, this will be the FastCGI environment. For this, edit the file at `/etc/lighttpd/conf-enabled/15-fastcgi-php.conf` to add another environment to the `bin-environment` key, replacing `homer.domain.com` with your CORS required source domain:

```php
fastcgi.server += ( ".php" =>
        ((
                "bin-path" => "/usr/bin/php-cgi",
                "socket" => "/var/run/lighttpd/php.socket",
                "max-procs" => 1,
                "bin-environment" => (
                        "PHP_FCGI_CHILDREN" => "4",
                        "PHP_FCGI_MAX_REQUESTS" => "10000",
                        "CORS_HOSTS" => "homer.domain.com,homer.local"
                ),
                "bin-copy-environment" => (
                        "PATH", "SHELL", "USER"
                ),
                "broken-scriptfilename" => "enable"
        ))
)
```

Remember, this is a fix from the Pi-hole side, since the frontend/browser cannot do anything, it is not an issue with homer.

**Comment by tivolimeister** [comment]
Adding `Access-Control-Allow-Origin` to the PiHole `/etc/lighttpd/external.conf` did nothing for me.

What did in the end was to add the originating domain (`homer.home.arpa`) as a `VIRTUAL_HOST` in PiHole. In Docker just add an environment variable `VIRTUAL_HOST: "`homer.home.arpa".

@bastienwirtz 
Maybe add to the [Troubleshooting](https://github.com/bastienwirtz/homer/blob/main/docs/troubleshooting.md) page?

**Comment by greenerk** [comment]
Adding in my 2 cents here - I don't believe this is an issue that needs to be resolved at the Pi-Hole end.  I also have Pi-Hole running on a different device to Homer, but other dashboards pull out the stats just fine.  One example is [Heimdall](https://github.com/linuxserver/Heimdall):

![image](https://user-images.githubusercontent.com/56622533/172359595-a35aa360-4b5c-441f-9319-d3387227cf3f.png)

**Comment by bastienwirtz** [comment]
@greenerk the big diff is dashboard like Heimdall have a backend (server side component which does request without any CORS consideration). Homer cannot do that.

**Comment by robklingler** [comment]
For others experience the issue, wanted to confirm that I was able to address the issue as follows.  I'm running a standard PiHole installation on a Raspberry Pi OS Lite (at 10.0.0.2) and running Homer in a docker container on another Raspberry Pi (10.0.0.3). I was able to fix the issue with the following commands on the PiHole...

`sudo nano /etc/lighttpd/external.conf`

Adding the following text to external.conf:
  setenv.add-environment = (
  "VIRTUAL_HOST" => "10.0.0.3"
  )

And then restarting the lighttpd service with:
`sudo /etc/init.d/lighttpd restart`

I then reloaded Homer, and the PiHole statistics immediately started working.

**Comment by HolgerAusB** [comment]
In my case NONE of any special services are showing up on my homer! None of my three PiHoles and not my UptimeKuma. But I think it is because of the restrictions I made in my Firefox: containered fencing.

When testing with Edge intead, sometimes (!) I got the special data.

How gets homer the data from PiHole/UptimeKuma? Is this done by the Backend or is that just embedded data, so the Browser is fetching the parts from different sites?

**Comment by jhbsa** [comment]
This thread was super helpful. In my case, I have pihole running on a pi-zero (go figure) and Homer in an LXC container on Proxmox 7.  I found the external.conf VIRTUAL_HOST solution worked for a single hostname, but looking at the auth.php file, I see a much more appropriate environment variable to set for this: CORS_HOSTS  (which is expected to be a comma separated list) So as a concrete example of my final working solution here is my external.conf
`setenv.add-environment = (
"CORS_HOSTS" => "dashboard.foo.tld,dash.foo.tld"
)`

Hope this helps others as much as this thread helped me.

**Comment by federicociro** [comment]
What about if I am running PiHole directly on Debian? which variable represents VIRTUAL_HOST in the PiHole configuration?
