### ISSUE TITLE
Foreign chars do not work with message: (messagebox)

### ISSUE THREAD

**Issue by ehcelino** [bastienwirtz/homer#198]
I am trying to use the message: to write a message box to the user of the page, but I've noticed that foreign characters do not work. 
Example:

    message:
      style: "is-warning"
      title: "Atenção"
      icon: "fa fa-exclamation-triangle"
      content: "Este servidor está em construção. Serviços limitados no momento."
Will result in �� chars where the foreign characters are. Strangely, if I do this:

    content: "Este servidor est&aacute; em constru&ccedil;&atilde;o. Servi&ccedil;os limitados no momento."

The page will show the acute and tilde correctly. But not in "title:", only "content:".

**Comment by bastienwirtz** [comment]
Hi @ehcelino! 

I just checked on me local env using your first example, it seems ok on my side: 

![Screenshot_2021-03-08 Demo dashboard Homer](https://user-images.githubusercontent.com/345559/110423502-fec79400-8055-11eb-9fb1-f16852e0e067.png)

Can you check the encoding of the config file? Mine is `UTF-8`: 

```bash
$ file config.yml
config.yml: HTML document, UTF-8 Unicode text, with very long lines
```

Other than that, maybe the server or proxy that expose your page doesn't serve the correct encoding?

**Comment by ehcelino** [comment]
For some reason, my output is this:

    $ file config.yml
    config.yml: HTML document, ASCII text, with very long lines

**Comment by ehcelino** [comment]
I deleted the config.yml I was using and replaced it with the example from the repo, now it's working fine. 

    config.yml: HTML document, UTF-8 Unicode text, with very long lines

Thank you @bastienwirtz !!!
