### ISSUE TITLE
Feature Request: Grid Size Increase

### ISSUE THREAD

**Issue by willsmi1256** [bastienwirtz/homer#199]
It would be really cool if we could modify the dimensions of the grids. I'd love to do 4-6 columns  (I'm on a 3440x1440 monitor) instead of 3, even if that scaled the tiles down slightly, instead of being locked in to 3 columns in either view.

**Comment by Fabeuss** [comment]
I think you can :
[https://github.com/bastienwirtz/homer/blob/b6c667a129867db8c0f8aa29d12013b47e0c6516/docs/configuration.md](url)
Simply add that line in your config file : 
columns: "3" # "auto" or number (must be a factor of 12: 1, 2, 3, 4, 6, 12)

**Comment by willsmi1256** [comment]
Hey Fabeuss,

I saw that option when but when enabled, it shrinks down width of the tiles to keep a large pixel buffer on the left and right of the "table". Even on my monitor, they don't stretch out much and you can't read the full subtitle on the tile in either orientation. The below picture is on column: "4". Column: "6" makes them even narrower.

![image](https://user-images.githubusercontent.com/69473207/111012007-02faf680-8361-11eb-82d7-d873116763a5.png)

**Comment by Fabeuss** [comment]
Hi, Ok, sorry I know what you mean, you're right, it's true that it would be a point to improve for UW screens owners.

**Comment by willsmi1256** [comment]
Just realized this is covered under #106
