### ISSUE TITLE
darkhttpd: bind(port 8080): Address in use

### ISSUE THREAD

**Issue by nodecentral** [bastienwirtz/homer#205]
Hi

I’m trying to install Homer as a Container on my QNAP (via Virtualisation Station, which is its own front end to Docker). I’m assuming I get the ‘ darkhttpd: bind(port 8080): Address in use’ error because QNAP itself uses 8080 as it’s default but, I’ve updated the Docker compose to a new host and container port,  but I still get the same message ?

````
docker run -d \
  -p 3380:3380 \
  -v </your/local/assets/>:/www/assets \
  --restart=always \
	  b4bz/homer:latest
````

Any ideas ?

**Comment by Darathor17** [comment]
Hello, your command is wrong. Try `3380:8080` to edit container ports.

**Comment by nodecentral** [comment]
Hi, I still get the same error with that too, is there a way to change the container port so it’s not 8080 ?

**Comment by Darathor17** [comment]
Well changing the port will be breaking for everyone so probably not the best course of action ;)

When mapping 3380:8080 it means that the container port 8080 will be map to the host port 3380. So it should not conflict with any existing application using port 8080.

Assuming your config is:
```
docker run -d \
  -p 3380:8080 \
  -v </your/local/assets/>:/www/assets \
  --restart=always \
	  b4bz/homer:latest
```
You should not have any issue. I suggest you verify that previous container was deleted and rerun the command. You could run `docker container ls` and share the result here

**Comment by nodecentral** [comment]
sorry I should have been clearer I’m using host mode
````

docker run -d \
--net=host \
  -p 3380:8080 \
  -v /share/Container/homer/:/www/assets \
  --restart=always \
	  b4bz/homer:latest
````

**Comment by Darathor17** [comment]
OK I see!

Could you try without just to confirm it's working? Also may I ask why you want to run in host mode? (for a static app like homer there is no value IMO)

**Comment by nodecentral** [comment]
Hi, i can confirm it does work without host mode.

As to why I use host, I mainly do it to reduce the number of IP addresses I have to issue on my network.

**Comment by Darathor17** [comment]
OK good to know. If you want to use host-mode I see indeed only two options:

- Like you mention, ask @bastienwirtz to change the port to something different than 8080 in its project (not likely to happen)
- You could change port in the dockerfile and build the image yourself, that's probably the easiest

**Comment by nodecentral** [comment]
Thanks for that, I’ve never done the second one before - built my own image, where the best place to learn that ?

**Comment by Darathor17** [comment]
A very simple approach should be along those lines
````
git clone https://github.com/bastienwirtz/homer.git
cd homer
vi Dockerfile #Change 8080 to 3380
docker build -t homer-custom .
docker run <...> homer-custom
````

Going further I could suggest is to research (a) docker-compose (it will ease running containers) and (b) how to create a dockerfile (in this case, it already [exists](https://github.com/bastienwirtz/homer/blob/main/Dockerfile)). A good starting point could be [here](https://medium.com/@zhao.li/how-to-understand-building-images-with-docker-compose-24cbdbc0641f). 

Cheers and good luck!

**Comment by RixzZ** [comment]
It might be a good addition adding a non-required ENV variable to override the port.

Seeing the code seems like you already use a ENV variable on build time to do it, so checking the existence of other variable on the entrypoint.sh should be enough.

**Comment by fbartels** [comment]
> It might be a good feature adding a non-required ENV variable to override the port.

That is actually already the case. The port in the entrypoint comes from an environment variable, which only needs to be overridden at container start.

https://github.com/bastienwirtz/homer/blob/64f189c9dcfddb67261bec305b7fe4c85b9963b7/entrypoint.sh#L15

**Comment by Darathor17** [comment]
> > It might be a good feature adding a non-required ENV variable to override the port.
> 
> That is actually already the case. The port in the entrypoint comes from an environment variable, which only needs to be overridden at container start.
> 
> https://github.com/bastienwirtz/homer/blob/64f189c9dcfddb67261bec305b7fe4c85b9963b7/entrypoint.sh#L15

Thx for this! I should have read the `entrypoint.sh`!

Just for the sake of completion the correct answer is then:
```
docker run -d \
  -p 3380:3380 \
  -v </your/local/assets/>:/www/assets \
  -e PORT=3380 \
  --restart=always \
	  b4bz/homer:latest
```

**Comment by nodecentral** [comment]
Hi - just to confirm - with the above I can add ‘net=host’ ?

**Comment by Darathor17** [comment]
Tested on my installation, I'd say yes :) You can remove the `-p 3380:3380` directive since docker ignore it in host mode.


```
docker run -d \
  --net=host \
  -v </your/local/assets/>:/www/assets \
  -e PORT=3380 \
  --restart=always \
	  b4bz/homer:latest
```

**Comment by nodecentral** [comment]
Hi

I finally found time to work on this again and I added the new port environment variable but it didn’t work - I now get the following error.. :(

````
darkhttpd: bind(port 3380): Permission Denied
````

Any ideas ?

**Comment by nodecentral** [comment]
Fixed, tried a different port and it works, I can only assume that port was reserved by something, as it was not showing up as in use..

**Comment by fbartels** [comment]
Issue could be closed I would say
