### ISSUE TITLE
json to get external IP in message section failing

### ISSUE THREAD

**Issue by tupcakes** [bastienwirtz/homer#207]
I'm trying to get the external IP address to show in the messages section using json. however for some reason it's not getting it. I wasn't sure if this was a bug or by design (or that I just don't know what I'm doing)?

I'm using the service to get the "ip" property.
http://ifconfig.co/json

which returns:
```
{
  "ip": "123.123.123.123",
  "ip_decimal": 1289021378,
  "country": "United States",
  "country_iso": "US",
  "country_eu": false,
  "region_name": "some state",
  "region_code": "ST",
  "metro_code": 123,
  "zip_code": "12354",
  "city": "Some city",
  "latitude": 0.0,
  "longitude": 0.0,
  "time_zone": "America/somewhere",
  "asn": "AS00000",
  "asn_org": "my provider",
  "hostname": "my hostname",
  "user_agent": {
    "product": "Mozilla",
    "version": "5.0",
    "comment": "(Windows NT 10.0; Win64; x64; rv:87.0) Gecko/20100101 Firefox/87.0",
    "raw_value": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:87.0) Gecko/20100101 Firefox/87.0"
  }
}
```

![7PfbUFFasH](https://user-images.githubusercontent.com/6422631/114312665-08ab3f80-9ab9-11eb-9d41-6dfea47db3cb.png)

```
message:
  url: http://ifconfig.co/json
  mapping:
    content: 'ip'
  title: "External IP"
  content: "Could not get external IP"
```

I thought maybe it was something weird with the service I was using so I decided to try: ifconfig.me/all.json

which returns the property ip_addr, however I had the same result.

**Comment by ostgardh** [comment]
Try with https instead for http.........

**Comment by ostgardh** [comment]
I try with http and is not working.
But same site with https is ok..
🤨🤨

**Comment by tupcakes** [comment]
> 
> 
> I try with http and is not working.
> But same site with https is ok..
> 🤨🤨

it's working for you? ok I must be doing something wrong. what does your message declaration look like?

**Comment by ostgardh** [comment]
Hmm. 
This is strange.

**NOK**
  url: https://ifconfig.co/json
  mapping:
    content: 'ip'
  title: "TEST"
  content: "Message could not be loaded"

**NOK**
  url: http://ifconfig.co/json
  mapping:
    content: 'ip'
  title: "TEST"
  content: "Message could not be loaded"



**NOK**
  url: http://mysite.se/TEST_JSON/api.php?name=test
  mapping:
    content: 'value'
  title: "TEST"
  content: "Message could not be loaded"


**OK**
  url: https://mysite.se/TEST_JSON/api.php?name=test
  mapping:
    content: 'value'
  title: "TEST"
  content: "Message could not be loaded"

My site api.php is
{"status":200,"status_message":"Product Found","value":"Test test"}

**Comment by nodecentral** [comment]
Hi, slight variation on this, but is it possible to have the IP shown as part of one of the tiles, rather than as a message (in a similar way you can show pi-hole data, could you show IP information for the related tile device/application ?)

**Comment by tupcakes** [comment]
> 
> 
> Hi, slight variation on this, but is it possible to have the IP shown as part of one of the tiles, rather than as a message (in a similar way you can show pi-hole data, could you show IP information for the related tile device/application ?)

I haven't looked into that much yet, but from what I can tell that'd require writing a custom service handler. It might be possible, but I was hoping to do it with a simple json message.

**Comment by tupcakes** [comment]
> 
> 
> Hmm.
> This is strange.
> 
> **NOK**
> url: https://ifconfig.co/json
> mapping:
> content: 'ip'
> title: "TEST"
> content: "Message could not be loaded"
> 
> **NOK**
> url: http://ifconfig.co/json
> mapping:
> content: 'ip'
> title: "TEST"
> content: "Message could not be loaded"
> 
> **NOK**
> url: http://mysite.se/TEST_JSON/api.php?name=test
> mapping:
> content: 'value'
> title: "TEST"
> content: "Message could not be loaded"
> 
> **OK**
> url: https://mysite.se/TEST_JSON/api.php?name=test
> mapping:
> content: 'value'
> title: "TEST"
> content: "Message could not be loaded"
> 
> My site api.php is
> {"status":200,"status_message":"Product Found","value":"Test test"}

I wonder if it has something to do with the "user_agent" having sub elements. I can't see how that would cause a problem, especially if a mapping is declared, but it's the only thing I can think of.

**Comment by crwallace2** [comment]
When I try that with the source url of "https://ifconfig.co/json" it fails due to a CORS error (I don't really understand this stuff, but I ran into a similar issue with pihole stats).  I tried it using a different source url that provides the public ip and it works with no other changes.

url: https://api64.ipify.org/?format=json
mapping:
    content: 'ip'
refreshInterval: 600000
title: "Public IP"

The CORS error I see in chrome console is below when I use the ifconfig as the url 

> Access to fetch at 'https://ifconfig.co/json' from origin 'redacted homer host ip' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by tupcakes** [comment]
> When I try that with the source url of "https://ifconfig.co/json" it fails due to a CORS error (I don't really understand this stuff, but I ran into a similar issue with pihole stats).  I tried it using a different source url that provides the public ip and it works with no other changes.
> 
> 
> 
> url: https://api64.ipify.org/?format=json
> 
> mapping:
> 
>     content: 'ip'
> 
> refreshInterval: 600000
> 
> title: "Public IP"
> 
> 
> 
> The CORS error I see in chrome console is below when I use the ifconfig as the url 
> 
> 
> 
> > Access to fetch at 'https://ifconfig.co/json' from origin 'redacted homer host ip' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

That's interesting. I guess I'll just use the other one for now. 

I'm only vaguely familiar with cors policy. I'll see what I can find out about that.

Thanks.

**Comment by tupcakes** [comment]
So I ended up running an instance of ifconfig.co locally (they have a docker image). I had the same issue. It define you seems to be something with that service. See as there are plenty of options that work for showing the external ip, I'm going to close this.

**Comment by AustinSaintAubin** [comment]
Same issue with other external sites.

```
# config.yml
# Optional message
message:
  # XKCD
  url: "https://xkcd.com/info.0.json"
  icon: "fa fa-grin"
  mapping:
    title: 'title'
    content: 'alt'
  title: "XKCD Comic of the Day"
  content: "Content could not be loaded"
  refreshInterval: 100000000
```

**Comment by whiskywaffel** [comment]
none of these work:
```
message:
  #url: https://api.ip.sb/jsonip
  #url: https://ip.seeip.org/jsonip?
  #url: https://ifconfig.co/json
  url: https://api64.ipify.org/?format=json
  mapping:
    content: 'ip'
  title: "Internet Protocol Address"
  content: "Message could not be loaded"
```
`https://xkcd.com/info.0.json` isn't working either.




Inside the container i can curl to the addresses and am getting the correct resposes
![image](https://user-images.githubusercontent.com/37911718/122754794-65cf2880-d294-11eb-9d64-13137191bff2.png)
![image](https://user-images.githubusercontent.com/37911718/122754451-f8bb9300-d293-11eb-80bc-2c4b7b02c7d2.png)

Only url that works in the message box is the example in the config `https://api.chucknorris.io/jokes/random`

I really dont know where i can get more informations, the container log isn't returning any errors or warnings
![image](https://user-images.githubusercontent.com/37911718/122755254-06254d00-d295-11eb-994c-21c2bab356b8.png)
