### ISSUE TITLE
[FEATURE] Removal of the Top "Blue Bar" and option to retain the search, theme and view switch options without having the Page link option

### ISSUE THREAD

**Issue by mokshmridul** [bastienwirtz/homer#21]
Hi,

I wanted to make a few feature requests, namely:

1) Option to remove the following section from the page, and consequentially remove the entire blue bar which appears on the top part of the page

```
title: "Moksh's Homelab"
subtitle: "Homelab"
logo: "assets/logo.png"
 icon: "fas fa-skull-crossbones" Optional icon
footer: false
```

2) I would also like the option to retain the search, view switch and theme switcher to remain, even if no pages are referenced in the following section:

```links:
  - name: "Home Page"
    icon: "fab fa-github"
    url: "https://mokshmridul.in"
    target: '_blank' # optional html a tag target attribute
```

Thanks a ton

**Comment by DaPutzy** [comment]
You can do this:

    links: {}

to keep the bar without links in it.

**Comment by bastienwirtz** [comment]
Hi @mokshmridul! Thanks for the feedback!
The header hiding is on it's way here: https://github.com/bastienwirtz/homer/pull/26 :+1:

**Comment by mokshmridul** [comment]
> Hi @mokshmridul! Thanks for the feedback!
> The header hiding is on it's way here: #26 👍

WOW !!

Thanks a ton mate, looking forward to the merge :)

**Comment by bastienwirtz** [comment]
@mokshmridul took a bit more time than expected and have been moved in another pull request, but it's still coming: https://github.com/bastienwirtz/homer/pull/26! Stay tuned!

**Comment by mokshmridul** [comment]
> @mokshmridul took a bit more time than expected and have been moved in another pull request, but it's still coming: #26! Stay tuned!

Thank you so much mate

Looking forward to this change :)

**Comment by bastienwirtz** [comment]
Hello @mokshmridul, It has been merge, hope that works for you!

**Comment by mokshmridul** [comment]
> Hello @mokshmridul, It has been merge, hope that works for you!

Hi, Thank you so much for this. Ill check and close this thread once the docker file gets udpated.

Thank you once again.
