### ISSUE TITLE
Issues adding link to app running on alternate port

### ISSUE THREAD

**Issue by whittick88** [bastienwirtz/homer#215]
my url is configured as such: `url: '192.168.0.100:7878'` However when clicking the associated icon it takes me to `192.168.0.100:8080/192.168.0.100:7878` I'm sure this is me doing something wrong, but can't figure out what. Any pointers would be appreciated.

**Comment by Simon-the-Sorcerer** [comment]
Have you tried to include the protocol? 

pls try `url:  'http://192.168.0.100:7878'`

**Comment by whittick88** [comment]
This did the trick, and honestly I should have thought of this myself! Thanks @Simon-the-Sorcerer
