### ISSUE TITLE
Help with installation, can't configure ports successfully (ERR_CONNECTION_REFUSED)

### ISSUE THREAD

**Issue by MetallicAchu** [bastienwirtz/homer#218]
Hi,

I've been trying to docker install homer using this configuration:
`docker run -d \
  -p 6620:80 \
  -v /my/path/here:/www/assets \
  --restart=always \
  b4bz/homer:latest`

nginx is listing to port 80 on my server:

`# sudo lsof -i -P -n | grep LISTEN | grep nginx`

(I replaced my IP with xxxxxxxxxxxx)
nginx      50005            root   13u  IPv4  141509      0t0  TCP xxxxxxxxxxxx:80 (LISTEN)
nginx      50005            root   14u  IPv4  141510      0t0  TCP 127.0.0.1:80 (LISTEN)
nginx      50005            root   15u  IPv4  141511      0t0  TCP xxxxxxxxxxxx:443 (LISTEN)
nginx      50005            root   16u  IPv4  141512      0t0  TCP 127.0.0.1:443 (LISTEN)
nginx     102671           nginx   13u  IPv4  141509      0t0  TCP xxxxxxxxxxxx:80 (LISTEN)
nginx     102671           nginx   14u  IPv4  141510      0t0  TCP 127.0.0.1:80 (LISTEN)
nginx     102671           nginx   15u  IPv4  141511      0t0  TCP xxxxxxxxxxxx:443 (LISTEN)
nginx     102671           nginx   16u  IPv4  141512      0t0  TCP 127.0.0.1:443 (LISTEN)
nginx     102672           nginx   13u  IPv4  141509      0t0  TCP xxxxxxxxxxxx:80 (LISTEN)
nginx     102672           nginx   14u  IPv4  141510      0t0  TCP 127.0.0.1:80 (LISTEN)
nginx     102672           nginx   15u  IPv4  141511      0t0  TCP xxxxxxxxxxxx:443 (LISTEN)
nginx     102672           nginx   16u  IPv4  141512      0t0  TCP 127.0.0.1:443 (LISTEN)

And I currently have this containers running on docker:
`docker ps`
CONTAINER ID   IMAGE                          COMMAND                  CREATED         STATUS         PORTS                                             NAMES
ba827233a3ae   b4bz/homer:latest              "/bin/sh /entrypoint…"   3 minutes ago   Up 2 minutes   8080/tcp, 0.0.0.0:6620->80/tcp, :::6620->80/tcp   recursing_raman
1e0b951ac16c   photoprism/photoprism:latest   "/entrypoint.sh phot…"   3 days ago      Up 2 minutes   0.0.0.0:2342->2342/tcp, :::2342->2342/tcp         photoprism
1ecf9cf6bb36   mariadb:10.5                   "docker-entrypoint.s…"   3 days ago      Up 2 minutes   3306/tcp                                          mariadb

From what I understand, if I configured homer to be 6620->80 it should listen to port 6620 and forward it to port 80 on my machine, which is nginx server, right?
But for some reason, docker lists 8080/tcp with this package.
I used docker-compose to install photoprism and configured ports to be 2342:2342 and I can access them from my browser with no problem, and it doesn't list 8080 (maybe that's the problem?), but homer isn't working for some reason.

Can anyone guide me on what to check?
Thanks!

BTW should I copy anything to the local folder? I have these:
`homer# dir`
additionnal-page.yml.dist  config.yml.dist             custom.css.sample   icons          tools
config.yml                 config.yml.dist.sample-sui  docker-compose.yml  manifest.json

**Comment by bastienwirtz** [comment]
Hi @MetallicAchu !

The server inside the container listen on 8080, and you can't change it to 6620 without rebuilding the image. If you set it back to `-p 8080:80` it should work!

Everything needed in the mounted folder is automatically installed. You just have to edit the `config.yml` to get started !

**Comment by crwallace2** [comment]
> Hi @MetallicAchu !
> 
> The server inside the container listen on 8080, and you can't change it to 6620 without rebuilding the image. If you set it back to `-p 8080:80` it should work!
> 
> Everything needed in the mounted folder is automatically installed. You just have to edit the `config.yml` to get started !

I think you reversed it here, the container port is on the right, and the host port is on the left.  they could do the below to forward the host port 6620 to container port 8080

-p 6020:8080

**Comment by neilwoodwards** [comment]
I'm actually struggling to make this work on port 80:8080. It just does not load at all. Put it back to 8080:8080 and it loads.
Homer doesn't seem to like Port 80 (Host)
