### ISSUE TITLE
Getting flashed when I open Homer

### ISSUE THREAD

**Issue by epicylon** [bastienwirtz/homer#222]
Hey, quite similarly to issue #132 there's a brief, painfully white flash before the dashboard loads. 

I'm on v21.03.2, and use Vivaldi 3.8.

Everything's in dark mode, Homer is the only page that flashes me.

**Comment by bastienwirtz** [comment]
HI there, 

I'm closing this one as it's a #132 duplicate. I might be able to improve that but the way it works (loading theme & color pref from the yaml file), add some latency to the colors to apply (time fetch & parse the yaml file)
