### ISSUE TITLE
Question : Run terminal commands / scripts (Command Line Tasks)

### ISSUE THREAD

**Issue by nodecentral** [bastienwirtz/homer#227]
Hi

is there a way to create a button/tile on the Homer Dashboard that could run a predefined terminal command or script ?

**Comment by bastienwirtz** [comment]
Hi @nodecentral! 

It's not possible to run command or script because Homer is just static HTML/CSS. There is no server side, so all we can do is ajax request to some endpoint. If you have some sort of server / endpoint allowing you to run commands, we could add a tile for that. 
Maybe something like https://jacobsalmela.com/2020/09/15/introducing-sampo-a-bash-api-server-that-runs-your-shell-scripts/ ? (just done a quick search, might not be what your looking for).

**Comment by fbartels** [comment]
Although rather designed for non-human interaction, maybe https://github.com/adnanh/webhook could be interesting as well.

Maybe a service for Homer could be developed that can call could make a predefined call (incl. headers) instead of opening a link

**Comment by bastienwirtz** [comment]
Nice find @fbartels. That looks exactly what @nodecentral is looking for :)

**Comment by nodecentral** [comment]
Hi all, many thanks for giving me some ideas, and @fbartels I like the webhook s route, I just need to know how to do it all. Seeing as I’m running the Docker instance of Homer, does the following approach seem right ?

1) Access Homer via the Docker command line and install webhook
````
docker run -ti homer /bin/bash
apt-get install webhook
````
2) Create the shell/bash script you want to use/execute, and use a text editor to add your required script/commands into that .sh file
````
touch /var/scripts/testabc.sh
`````
3) Next create a webhook yaml ?
````
touch /var/webhook/testing123.yml
````
Open/edit that testing123.yml to look something like the following..
````
- id: redeploy-webhook
  execute-command: "/var/scripts/testabc.sh"
  command-working-directory: "/var/webhook"
````
4) Make your shell script accessible via a url.
````
/path/to/webhook -hooks testing123.yml -verbose
````
Which will make that shell/bash script run when you request the following url 
````
http://yourserver:9000/hooks/testabc-webhook
````

Does the above sound about right ?

**Comment by fbartels** [comment]
> Seeing as I’m running the Docker instance of Homer, does the following approach seem right ?

No, that is unnecessarily complicated. The way with less maintenance would be to have both homer and webhook in a docker compose file and just speak over the network with it. :8888 for homer and :9000 for webhook for example. Bonus points for strapping a reverse proxy infront to not have to remember ports.

**Comment by nodecentral** [comment]
Hi @fbartels 

> > The way with less maintenance would be to have both homer and webhook in a docker compose file and just speak over the network with it. :8888 for homer and :9000 for webhook for example. Bonus points for strapping a reverse proxy infront to not have to remember ports.

How exactly would having the two together look within a Docker compose, the Docker run command I had was as follows?.
````
docker run -d \
--net=host \
  -p 3380:8080 \
  -v /share/Container/homer/:/www/assets \
  --restart=always \
	  b4bz/homer:latest
````

**Comment by fbartels** [comment]
There is a handy tool at https://www.composerize.com/ that can convert docker run commands into composer definitions (which you would then still need to merge into a single file. With your command above it could be:

```
version: '3.3'
services:
    homer:
        network_mode: host
        ports:
            - '3380:8080'
        volumes:
            - '/share/Container/homer/:/www/assets'
        restart: always
        image: 'b4bz/homer:latest'
```

Although the network_mode and the port definition kind of cancel themselves out. You should use one or the other.

Below that you could add the following:

```
    webhook:
        ports:
            - '9090:9090'
        volumes:
            - '/share/Container/webhook/:/hooks'
        image: 'actual-webhook-container'
```

**Comment by Emilaia** [comment]
I'm interested on doing something similar.

I have homer hosted on a raspberry pi, and am interested on adding "shutdown" and "reboot" buttons to the dashboard for the pi, given how it doesn't come with physical buttons.

Some people have done this on docker by [using named pipes](https://stackoverflow.com/a/63719458), which is basically just a process that listens for files added to an empty folder, which is added as a volume to the docker container. Although as mentioned, it's not possible to just inject custom code for me to tell homer to make a file with x text after a button is clicked.

So I got interested when webhooks and ajax were mentioned, it still isn't part of homer right? Or is there an example around?

**Comment by bastienwirtz** [comment]
Hi @Emilaia, 
Sorry for the very late reply. Homer is just a front end, it cannot do this kind of thing. But it could call some backend service to do it. I personally don't know about this kind of API but it may exists. I'm closing this issue, feel free to reopen it if needed :)
