### ISSUE TITLE
Handle how service workers/front end operates

### ISSUE THREAD

**Issue by adyanth** [bastienwirtz/homer#229]
I have a public instance of homer running behind cloudflare access, which redirects the user to a sign in page before the user can access the resource behind a domain. 

Now the issue is that, since the service worker handles the home page, the redirect happens for the `/config,yml` URL which causes the redirection, and once signed in, I end up getting a download for the `config.yml` rather than being redirected to the home page. But once I am logged in, if I visit the homer instance, it is just fine.

I would suggest to use the keepalive URL for Connectivity Checker `?alive` to be called before the `config,yml` which hopefully should redirect to the correct domain,.

I guess even in #226 a similar behaviour is seen. But for this, I guess if the connectivity check status code is 3xx or 401/403, I would suggest a page reload with `location.href = location.href` to correctly redirect after timeout.

CC: @bastienwirtz

**Comment by adyanth** [comment]
I think #186 fixes this too.
Can confirm with better clarity soon.

**Comment by adyanth** [comment]
It does not. Just had the config.yml downloaded after auth.

**Comment by bastienwirtz** [comment]
HI there, 

It's a known issue and I'll work on it soon. I'm centralizing discussion in #232 and closing this one.
