### ISSUE TITLE
Google Analytics?

### ISSUE THREAD

**Issue by eburgueno** [bastienwirtz/homer#242]
Hello! I came across this project from the Awesome Self-Hosted list, and I really like it.

Is there any way to integrate Google Analytics? I saw you have `workbox-google-analytics` in your yarn.lock, but I'm not sure if that's relevant, nor how to add the gtag to the site.

Thank you!

**Comment by hulmgulm** [comment]
The idea behind HOMER is to allow you to create your personal home page. Why would you want to include Google Analytics in your personal home page?

**Comment by eburgueno** [comment]
Because it could be used for more than a personal homepage? How about a simple launcher of internal apps in a SME? Or perhaps you want to make a public "my favorites" site and want to track its usage? Maybe you're just playing with GA and want to understand how you can visualise user behaviour flows? Plenty of possible reasons.

**Comment by bastienwirtz** [comment]
HI there, 

I understand your need but I will not add support specifically for google analytics, because there a plenty of other analytics tools. 
What we can do is offer a way to add a javascript tag to the page. I will think about it. Thanks for the suggestion.

**Comment by iambricegg** [comment]
Hello @bastienwirtz.
Is there a follow-up to this proposal?

We use Homer Dashboard as an application portal in our school and I want to integrate it with Umami Analytics to understand the usage made by users.

Thanks in advance.

**Comment by xX-MrN0b0dy-Xx** [comment]
Hi @bastienwirtz !
I love this project and I am currently using it but I would like to add the Matomo tracking Javascript to the head of the pages generated because some services I am self-hosting are also used by friends and relatives.
Is there any feature any follow-up?
