### ISSUE TITLE
Server status icon

### ISSUE THREAD

**Issue by grandmastermarco** [bastienwirtz/homer#256]
I would love to see an option included to see if hosts / servers / services are offline / online.
E.g. There could be an option in the config.yml to activate status indicator in front of the service.
An idea would be a simple indicator similar to this one: [https://community.spiceworks.com/how_to/2254-how-to-show-server-status-on-your-portal](url)
Sadly i do not understand enough of coding to contribute.
I hope that others would find a feature like this helpful and can contribute. Thanks!

**Comment by tamaskan** [comment]
isn't that already in there ? just add type: "ping" to the item

**Comment by grandmastermarco** [comment]
Thanks for the info. I searched again in the documentation and found the ping info in ‚custom services‘.
Sadly there is a mistake in the documentation and i dont understand how to use ping - do you need to exclude subtitle like e.g. PiHole?
#249 describes the problem. Thanks for the help anyway.
