### ISSUE TITLE
Error starting another page

### ISSUE THREAD

**Issue by pvklink** [bastienwirtz/homer#264]
Hi when i start the default link "another page", i get an error. (#additionnal-page)
The rest of the dashboard works GREAT !

Error: Not Found: [object ReadableStream]

this is my docker compose file
dashboard:
    image: b4bz/homer:latest
    container_name: dashboard
    restart: unless-stopped
    ports:
    - "5000:8080"
    volumes:
    - "/home/pi/pvkmenu/volumes/dashboard:/www/assets"
    environment:
    - UID=1000
    - GID=1000

ths is my config.yml part

links:
  - name: "Wiki"
    icon: "fas fa-book"
    url: "https://www.wikipedia.org/"
  # this will link to a second homer page that will load config from additionnal-page.yml and keep default config values as in config.yml file
  # see url field and assets/additionnal-page.yml.dist used in this example:
  - name: "another page!"
    icon: "fas fa-file-alt"
    url: "#additionnal-page"

**Comment by tomdaley92** [comment]
I too am getting this error with the default configuration

**Comment by bastienwirtz** [comment]
Hello, 

Sorry for the delay! 
Did you create (or rename the [exemple](https://github.com/bastienwirtz/homer/blob/main/public/assets/additional-page.yml.dist)) the additionnal-page.yml config file? for the page to load, the config must exists. 

I'm closing this issue, feel free to reopen if needed.
