### ISSUE TITLE
Question - Spacing between rows

### ISSUE THREAD

**Issue by samcro1967** [bastienwirtz/homer#265]
Is there any way to add spacing between the rows so they are not touching?

**Comment by Barokai** [comment]
Create a custom stylesheet with the needed css adaptoins and embed it like mentioned here: https://github.com/bastienwirtz/homer/blob/main/docs/configuration.md

**Example step by step**
Copy custom.css.sample and rename it to custom.css
edit and add your desired css (just and example to achieve 5px spacing below the cards)
```
body #app .card-content {
  margin-bottom: 5px;
}
```

Add the stylesheet to your config.yml
```
stylesheet:
  - "assets/custom.css"
```

Refresh

**Comment by samcro1967** [comment]
Awesome.  Worked as expected.  Thank you and appreciate all of your work on this project!

**Comment by Barokai** [comment]
you're welcome :)
PS: this isn't my work - it's the great work of @bastienwirtz and the other contributors, I just wanted to help you as i saw this issue and thought i'll try to help
