### ISSUE TITLE
Custom Services - Generic template to get live information / status via a http get request?

### ISSUE THREAD

**Issue by nodecentral** [bastienwirtz/homer#266]
Hi, 

Is there a generic template or something I can use as a custom service for a number of my Homer tiles ?

https://github.com/bastienwirtz/homer/blob/3a8fa151f46c28274a418aa284c12fe71a827e95/docs/customservices.md

For example, within my home automation system, I have the ability to use a http request  to find out the status of specific power sockets that systems are plugged into. Some will return 0 (zero) or 1, other ‘on’ or ‘off’.  I’d like it to poll that url periodically to see if it’s on or off and have that information appear on the tile..

Also I can make other calls to such a ping an IP address, obtain cpu temperature, ram details etc.  You name it, if it’s a registered device on the system I can request various attributes about it.

**Comment by bastienwirtz** [comment]
Of course. To use a custom service you just have to add an item in your service list with the additionnal `type` property. You have an example near the end of the configuration sample o this page https://github.com/bastienwirtz/homer/blob/main/docs/configuration.md#supported-services (Pi-Hole).
