### ISSUE TITLE
Search keyword

### ISSUE THREAD

**Issue by IGProd** [bastienwirtz/homer#269]
Hi,

Is that possible to search applications using keyboard directly
for example if i want to search for plex i tape letter p instead of click on search bare and tape plex or / 
Thank you

**Comment by robinschneider** [comment]
I like the idea of an auto search.
I already have a PR to be able to set a custom hotkey, as soon as this PR is merged (or rejected) I will submit a PR for this feature.

**Comment by Yassine2217** [comment]
> I like the idea of an auto search.
> I already have a PR to be able to set a custom hotkey, as soon as this PR is merged (or rejected) I will submit a PR for this feature.

Thank you

**Comment by bastienwirtz** [comment]
Hi there!

Why not, it sounds handy. @robinschneider your PR should be merged soon, I just have to take some time to test it but it seems fine.

Thnaks.

**Comment by jhonDoe15** [comment]
Hallo @robinschneider are you still working on this feature perhaps? would very much like to see it but not so great with Vue

> I like the idea of an auto search. I already have a PR to be able to set a custom hotkey, as soon as this PR is merged (or rejected) I will submit a PR for this feature.

**Comment by robinschneider** [comment]
@jhonDoe15 Sure I can do that.
