### ISSUE TITLE
(Idea) Reuse Search Bar For Custom Search Providers

### ISSUE THREAD

**Issue by Emilaia** [bastienwirtz/homer#273]
I like homer a lot, and it is currently my "new tab" for any browser I use, but I just thought the only thing it lacked was a regular online search bar.

I was thinking it may be possible to reuse the current search bar that you can focus when pressing `/`, to also be used with custom search engines (some call these providers), so that it can easily be used for when you want to search something online.

Let me show you an example setup, followed by the specifics of how this could work.

### Example Configuration

The configuration could be with a yaml, and be something like this:

```yaml
providers:
   - name: "Google"
     prefix: "g"
     url: "https://www.google.com/search?q=<q>" #where <q> would be just a wildcard to replace the escaped query with.
     logo: "my-logo" # or "assets/my-icon.svg"
     target: "__blank" # optional
``` 

### Example Execution

Now as to the specifics of how would could work, you first use `/` to focus into the search bar, and then you type out a provider prefix (for this example `g`), followed by a `space`, so the searchbar textbox at this stage has `g(space)` as its value. 

Given how `g` matches the provider prefix for Google, the magnifying glass in the search bar changes to that provider's icon as confirmation you are going to search on that engine. 

You type in your query, press enter, the query is converted, escaped and added to the configuration url, and you are redirected to the final search url.

### Things To Consider

1. I understand this comes with the conflict of distinguishing an online search and entries search, and I originally wanted the keystroke flow to be `/` (search bar focus) + `/<prefix><space><query>`, basically the same as above, only that you click the `/` key twice, so that the textbox would end up with `/g(space)`, but `/` won't be registered in the search box, as it's used to focus on it on the first place. But to be honest, if you type in something like `g(space)` and expected a single app or website, there's something odd with your configuration in the first place, so I don't think the `g(space)` idea is that flawed.
2. We are looking for exact prefix matches, so it could be possible to have `g` and `gg` as prefixes without conflict.
3. It is always possible to make this function for a separate search bar with optional auto focus.
4. Some people might want to control how the query is converted, let's say you want to convert `<q>` into `<a>`, `<b>` and `<c>`, and then have them return in the shape of: `?c=<c>&b=<b>&a=<a>` (just for an extreme example). I could only think of this being solved with a custom script/script path option, but as the website it's static this'll be unlikely, and only leaves room for a target regex + a replace regex. Though I just mainly wanted to expose this edge case, a regular escape should work for almost everything. 
5. You may have noticed there was a name field that went unused throughout the explanation, that's mainly because I only added it so that whoever is configuring the yaml can remember what it was for at a glance. However, dashboards like SUI, would use this name to provide a button that opens a modal listing all your options and their prefixes for in case you forget, so there is some potential application to it. But it isn't actually part of the core functionality, so you can simply ignore it if needed.

Don't know if this will eventually be considered for implementation or not, but regardless, thanks for giving it a look, and hope you have a nice day.

**Comment by robinschneider** [comment]
How about double press your hotkey and then have your google search? Would be easier to implement and also I would prefer to press my hotkey twice instead of the prefix.

**Comment by Emilaia** [comment]
> How about double press your hotkey and then have your google search? Would be easier to implement and also I would prefer to press my hotkey twice instead of the prefix.

I think providing a way to bind your own keyboard shortcuts has the potential to complicate things, for the person that has to make it. 

The specific idea you're proposing of double clicking a key isn't outrageous, but if more optional modules are added down the line, it could mean that you have to constantly toggle listening for hotkeys on and off. Like, if you were using the search bar to filter items, you wouldn't want that query to accidentally trigger a hotkey, those type of scenarios would need to be taken care of every time. And if you later want to add other modules/cells that could also benefit from hotkeys, not you'd have to check for conflicts for that as well. So enabling custom hotkeys in general, not specifically for this module, could lead to maintenance hell.

If the end goal is end goal is to type in an online search fast, the best would be to have a selectable default search provider, so without typing a keyword, you could search on Google by default for example. And if on top of that you allow for this new bar to be optionally auto focusable, every time you open a new tab, you could immediately just type your google query, no focus command, no keyword.

But the reason I didn't propose this from the get go, was just to reuse what was already there. Just wanted to wait for the dev to give their point of view eventually.

**Comment by AfricanHipp0** [comment]
Hey @Emilaia and @DanielSchetritt were either of you able to get this to work? I can't seem to get it to not use default search, which then prevents the trigger to use google
