### ISSUE TITLE
[FEATURE] Support for Font Awesome Pro

### ISSUE THREAD

**Issue by bacco007** [bastienwirtz/homer#28]
Feature Request - Support for Pro level Font Awesome icons (incl. light and duotone icons)

It would be good to be able to use some of the FA Pro icons (as a Pro licence holder)

**Comment by traeblain** [comment]
Use of Font Awesome Pro in open-source efforts is currently prohibited by the license. 

But honestly, I don't know why you cannot have it work for your personal dashboard?  I don't have a license, but you only need to house the Pro Fonts in the 'webfont' directory and provide the Font Awesome Pro CSS (assuming it's provided, I don't have a license to know) on this [line in the HTML file](https://github.com/bastienwirtz/homer/blob/2cf93f388130134d8ff9cf1af7535e21cafc207f/index.html#L10).

As I understand the license, this is going to have to be done by the license holder and not this project...I could 100% be wrong though, just going off what I have read.

**Comment by bastienwirtz** [comment]
Hi there,

I agree with @traeblain, it's not suitable for the project but can be done with little modifications.
