### ISSUE TITLE
v21.09.01 not tagged in docker hub

### ISSUE THREAD

**Issue by neographophobic** [bastienwirtz/homer#285]
The latest release, v21.09.01 has not been tagged in Docker Hub. Would it be possible to get the version tagged in addition to the latest tag?

**Comment by bastienwirtz** [comment]
HI, @neographophobic, 
there was an interruption in the auto build, but you can jump directly to the v21.09.0**2** tag.

**Comment by neographophobic** [comment]
Thanks for all of your work. That works for me.
