### ISSUE TITLE
Add support for OctoPrint

### ISSUE THREAD

**Issue by robinschneider** [bastienwirtz/homer#287]
Add support for OctoPrint with the current status of the 3D printer via OctoPrint HTTP API.

**Comment by bastienwirtz** [comment]
Hey @robinschneider, 

I like this idea, I'm adding that to my todo list!
Thanks!

**Comment by robinschneider** [comment]
@bastienwirtz I have it almost finished, I will create a PR at the weekend

**Comment by FriendlyNGeeks** [comment]
I added pull request for octoprint awaiting aproval. Not to step on your toes @robinschneider. I just really need this service added to the master as i continue to build out my home lab

**Comment by FriendlyNGeeks** [comment]
I went ahead and created the pull request if anyone else finds this issue please comment so maintainer can pull #324

**Comment by FriendlyNGeeks** [comment]
@bastienwirtz has this service ready to go... look for it in the next update.
