### ISSUE TITLE
fas fa with "-" dont work

### ISSUE THREAD

**Issue by BornToBeRoot** [bastienwirtz/homer#288]
Hi,

i am not able to use icon like `fas fa-hard-drive`. It seems like all icons with a second `-` don't work.

Greetings
BornToBeRoot

Edit: i use this url to search for icons: https://fontawesome.com/v6.0/icons

**Comment by robinschneider** [comment]
You used the fontawesome 6 icons, but you have to use the fontawesome 5 icons instead.
The equivalent of your icon would probably be `fa-hdd`.

Here you can search them https://fontawesome.com/v5.0/icons

**Comment by BornToBeRoot** [comment]
OK Thanks. I will test it.

**Comment by bastienwirtz** [comment]
Yes, only fa icon v5 are supported at the moment.
