### ISSUE TITLE
Columns and label size

### ISSUE THREAD

**Issue by Zerobian** [bastienwirtz/homer#294]
Hi,

I like the app really much, simple and lightweight.
I couldn't figure out, how to get more than three columns working. Space on left and right is sufficent for five.
Also I would like to know how to shrink the label for each entry. When I use a page for Weblinks, I only need the name. Is there a chance to customize this via an option?

Thanks and best regards
Sven

**Comment by fbartels** [comment]
Hi @Zerobian,

there is a columns option in the config.yml to configure the amount of rows. To make it fill your full screen you probably need to override the css however.

**Comment by Zerobian** [comment]
You're right, I had an older config file. Feature has been added afterwards.
