### ISSUE TITLE
Default to column view?

### ISSUE THREAD

**Issue by wesparish** [bastienwirtz/homer#295]
Is it possible to default to multi-column view vs single-column view and dark-mode vs light-mode?

Currently, I get the view I'm looking for if I click the center icon in the top navbar. Unfortunately, this doesn't persist across browsers or computers.

![image](https://user-images.githubusercontent.com/4511903/134665098-809c615f-b1fa-441f-b6e5-a65e77ec82d6.png)

**Comment by bastienwirtz** [comment]
Hello @wesparish !

It's already reported on #200 and I will work on it asap. I'm closing this one because of the duplicate.
Thanks!
