### ISSUE TITLE
Theme and Layout Default

### ISSUE THREAD

**Issue by Reznorzo** [bastienwirtz/homer#30]
Thanks for the great work first of all !

Is it possible to set the default theme (to dark) and the default layout at all ?
I've been digging around, but can't see where I could set this.

**Comment by traeblain** [comment]
First, the layout and dark mode is stored in localStorage so it should be persistent once changed.

If you want to change the defaults, dive into the `app.js` file:

Change the following values first on [line 7](https://github.com/bastienwirtz/homer/blob/46fd4f4da18ed505264181cfa8f6a776abef9e2f/app.js#L7):

```js
    vlayout: false
```
Next on [line 8](https://github.com/bastienwirtz/homer/blob/46fd4f4da18ed505264181cfa8f6a776abef9e2f/app.js#L8):

```js
    isDark: true
```

**Comment by Reznorzo** [comment]
Thanks for that.
Obviously I didn't dig hard enough !
