### ISSUE TITLE
New built-in theme

### ISSUE THREAD

**Issue by bastienwirtz** [bastienwirtz/homer#305]
Homer supports [built-in themes](https://github.com/bastienwirtz/homer/blob/main/docs/development.md#themes), based on [bulma](https://bulma.io/documentation/). 

It could be great to add some more. Before starting to work on a theme, please open an issue to describe your idea, link your inspiration if any, and discuss about it.  Themes are supposed to be mobile friendly and light & fast to load.

**Comment by fbartels** [comment]
https://github.com/WalkxCode/Homer-Theme was posted on Reddit yesterday

**Comment by N0Klu3** [comment]
@bastienwirtz Any word on this?
