### ISSUE TITLE
VueJS warning when rendering multiple service groups in list mode

### ISSUE THREAD

**Issue by Aryess** [bastienwirtz/homer#312]
Because services uses their sub-group index as a key, and are all displayed in the same div, if there are multiple groups, some services end up having the same key.

![Screenshot from 2021-10-12 11-49-08](https://user-images.githubusercontent.com/3518172/136872652-cefbf8a5-ff81-41c5-b794-cd54ac8740a9.png)

This is only a warning, and doesn't currently impact rendering, but still worth fixing.

**Comment by Aryess** [comment]
#313

**Comment by bastienwirtz** [comment]
This one has been fixed for a while. Thanks for reporting it!
