### ISSUE TITLE
Any way to use images in place of icons?

### ISSUE THREAD

**Issue by andrewwiebe** [bastienwirtz/homer#32]
I would love to be able to use an image in place of font awesome icons in places. A lot of things that I want to link to do not have icons on font awesome.

Thanks for great job btw!

**Comment by mselchow** [comment]
You can do this by using `logo: "path/to/logo.png"` in place of the `icon: "fas fa-logo-here"` configuration in your config.yml. I'm using a combination of both with no trouble.

**Comment by leggewie** [comment]
time to close?

**Comment by andrewwiebe** [comment]
Sorry should have closed this a long time ago. My mistake.
