### ISSUE TITLE
Background Modifications or Custom CSS

### ISSUE THREAD

**Issue by krousenick** [bastienwirtz/homer#322]
Hello!

Can you please add the variables below to be picked up in the CSS or allow custom CSS to be read into the config.yml to fully modify the background. Thank you very much in advance for your consideration!

background-repeat: 
background-attachment:

**Comment by D4rkiii** [comment]
You can define a custom css file if you need to override some styling.
Just add this line to your yml file.

stylesheet:
   - "assets/themes/mycustomstyling.css"

**Comment by bastienwirtz** [comment]
Hey @krousenick ! 

As suggested by @D4rkiii, you can use the custom css to add the suggested properties. 
I'm closing the issue, feel free to reopen it if you need.
