### ISSUE TITLE
Run entire container as non-root user not possible because of chown in entrypoint.sh script

### ISSUE THREAD

**Issue by ElleshaHackett** [bastienwirtz/homer#325]
I have issues with line 14 and 15 in entrypoint.sh because I try to change the user of the docker container entirely and that is currently not possible without some strange hackarounds. See the following commands and results with a default setup:

`docker exec home whoami`
`root`

`docker exec home top`
````
  PID  PPID USER     STAT   VSZ %VSZ CPU %CPU COMMAND
   35     0 root     R     1580   0%   1   0% top
    1     0 homer    S      784   0%   0   0% darkhttpd /www/ --no-listing --por
````

So the darkhttpd process is running as homer user but the the container isn't. I tried simply this to build this Dockefile to make the whole container run as another user.

````
FROM b4bz/homer:latest

ENV USER homer
ENV UID 8000
ENV GROUP homer
ENV GID 8000

RUN addgroup -S ${GROUP} -g ${GID} && adduser -D -S -u ${UID} ${USER} ${GROUP}
USER homer
````

But the last line will fail because ./entrypoint.sh contains chmod entries that will be executed by the homer user instead of the root user. I think this should be done earlier in the Dockerfile of this project rather than in an sh script to prevent this.

**Comment by ElleshaHackett** [comment]
I fixed it by simply overwriting the ENTRYPOINT and skipping the sh script entirely. Which will probably break things at some point. For now it's my workaround.

My Dockerfile:

````
FROM b4bz/homer:latest

ENV USER homer
ENV UID 8000
ENV GROUP homer
ENV GID 8000

RUN addgroup -S ${GROUP} -g ${GID} && adduser -D -S -u ${UID} ${USER} ${GROUP} && sed "s/chown -R/\#chown -R/g" /entrypoint.sh
USER homer

ENTRYPOINT [ "darkhttpd", "/www/", "--no-listing", "--port", "8080"]
````

This does run the whole container as a non-root user and not just the darkhttpd.

`docker exec homer whoami`
`homer`

`docker exec homer top`
````
  PID  PPID USER     STAT   VSZ %VSZ CPU %CPU COMMAND
   21     0 homer    R     1576   0%   0   0% top
    1     0 homer    S      784   0%   1   0% darkhttpd /www/ --no-listing --por
````

**Comment by git-noise** [comment]
Hello,

I also ended up just removing the chown operation from the entrypoint. I think it should be alright as files have a default 755 permission and are not meant to be writable I believe. It also allows to drop capabilities and mount file as read-only for further security. However it indeed means rebuilding the image manually.

Best,

**Comment by chris400** [comment]
AFAIK most containers run everything as root. If you want more security, you run docker rootless. Using multiple UIDs in the container breaks things.
=> I am suggesting to only use the user root _inside_ the container.

**Comment by grantland** [comment]
Setting `UID` and `GID` environment variables seems to work for me:

https://github.com/bastienwirtz/homer/blob/b6c667a129867db8c0f8aa29d12013b47e0c6516/docker-compose.yml#L13-L15

**Comment by bastienwirtz** [comment]
Hi there ! 
Thanks for reporting this. The docker file has been reworked to run as a non-root user, hope it works for you! feel free to give your feedback.

**Comment by alexbergsland** [comment]
Anyone ending up here from Homer suddenly not working anymore ;)

Change
```
environment:
  - UID=1001
  - GID=1001
```
to
```
user: 1001:1001
```
as per new compose file example: https://github.com/bastienwirtz/homer/blob/main/docker-compose.yml

**Comment by wormvortex** [comment]
> Anyone ending up here from Homer suddenly not working anymore ;)
> 
> Remove
> 
> ```
> environment:
>   - UID=1001
>   - GID=1001
> ```
> 
> and add
> 
> ```
> user: 1001:1001
> ```
> 
> as per new compose file example: https://github.com/bastienwirtz/homer/blob/main/docker-compose.yml

Perfect! Was wondering why mine had stopped working.

**Comment by bastienwirtz** [comment]
@alexbergsland @wormvortex I thought it wasn't breaking change, So sorry for that :(

**Comment by alexbergsland** [comment]
> @alexbergsland @wormvortex I thought it wasn't breaking change, So sorry for that :(

No worries, easy fix.
Thanks for keeping this project up.
