### ISSUE TITLE
Path to Radarr API changed in v3

### ISSUE THREAD

**Issue by jeff47** [bastienwirtz/homer#327]
I believe there needs to be an update to the Radarr integration.  In Radarr v3, the API path has changed.
/radarr/api/health? becomes /radarr/api/v3/health?  and so on.

**Comment by Panzer1119** [comment]
I just tested it and Radarr v3 accepts requests to both /api/... and /api/v3/...

**Comment by bastienwirtz** [comment]
Hi there :wave: 

The documentation seems to use the version (`v3`) in paths, which seems like a good idea to ensure compatibility. We might want to check Sonarr as well. 
I don't have a Radarr instance to make the modification and check if the custom service still works, @twolaw maybe?

**Comment by pamoman** [comment]
Hi there 👋

What is the eta for support of the /api/v3 endpoint in Radarr, Sonarr and Lidarr?  In the config.yml you can specify the endpoint manually but it adds /api to the end, wouldn't it be better to let the user provide the entire endpoint i.e endpoint: 192.168.1.100:8081/api/v3.

Just want to say that I'm really impressed with the web app so far, just what I was looking for.  Would be great if you could add service api stats for Sabnzbd and Readarr too.

**Comment by AtActionPark** [comment]
Hi!

It seems that the legacy api has now been deprecated.With the latest Radarr image, Im getting 404s on the calls without /v3

**Comment by crwallace2** [comment]
I just confirmed that RADARR has removed the legacy API endpoint with their latest release 4.0.4.5922.

**Comment by bastienwirtz** [comment]
Hi there, 

The v3 API support is now merged and included in the latest release. Enjoy!
