### ISSUE TITLE
Any way to secure access via login? Also Calendar? 

### ISSUE THREAD

**Issue by N0Klu3** [bastienwirtz/homer#328]
Is there any way you can add a login option?

Mainly as mine is open to the world via a domain name, as i want to use this for my home page wherever I am. 
But I'd also like to add some sort of login page so that its not just 100% open to the elements. 

Lastly is there a way to integrate into something like Google Calendars and start to make this a proper full on home page with everything needed and like 1 stop shop. 

I'd like the calendar so I can share with the wife and so on.

**Comment by robinschneider** [comment]
You can use something like traefik basic auth https://doc.traefik.io/traefik/v2.0/middlewares/basicauth/ or authelia with 2FA https://github.com/authelia/authelia

**Comment by N0Klu3** [comment]
Yeah I setup Basic Auth via HAProxy
