### ISSUE TITLE
No icon in Chrome bookmark bar

### ISSUE THREAD

**Issue by broizter** [bastienwirtz/homer#33]
There is no icon when you bookmark Homer and place it in your bookmark bar in Chrome. I included YouTube in the bookmark to the left to clarify what a normal website does when you bookmark it.

https://imgur.com/a/CSgmjd8

**Comment by bastienwirtz** [comment]
Hi @broizter!

The bookmark icon should be the favicon, can you check if you still have a `favicon.png` file in your `assets` directory? The path is hardcoded here: https://github.com/bastienwirtz/homer/blob/master/index.html#L8 so any change in the filename or extension will make the icon disapear.

**Comment by broizter** [comment]
That fixed it! My mistake for deleting it without realising.
