### ISSUE TITLE
Vulnerabilitys in Homers BusyBox Version

### ISSUE THREAD

**Issue by geekblog-dev** [bastienwirtz/homer#332]
I did run trivy over the repository. It found 20 Vulnerabilitys(2 Critical 18 High).

I didn't have the time to check them all, if required I can post the CVEs that have been Found by trivy.

Are we already aware of these "vulnerabilitys" or is it more of a false positive?

Maybe is there a plan to update the BusyBox Version?

**Comment by bastienwirtz** [comment]
Hello @geekblog-dev !

Thanks for pointing this out. The docker base image have been updated, the busybox vulnerability should be fixed.
I'm closing the issue, but feel free to re-open if anything.
