### ISSUE TITLE
Internet explorer compatibility [I am sorry]

### ISSUE THREAD

**Issue by PovilasID** [bastienwirtz/homer#335]
Hello,

I used homer a quick dashboard to list out tools on a server and some of my coworkers machines default browser is internet explorer.
Homer now does not support IE by falling to show any content at all:

> ⚠️ Error loading configuration 
> 
> ReferenceError: 'fetch' is undefined

Is there a plan to support IE? 

P.S. I know. I know but people are hard to change I hope mandatory Win11 update will solve this.

**Comment by miarn** [comment]
IE is unsupported as of next year, is used by almost no-one, and is a terrible browser.

**Comment by PovilasID** [comment]
Hey @bastienwirtz,

Got it. I will make a static html page with some links :/
Some of my co-workers are nearing the end of their career and they will not switch or upgrade. 
I know its a terrible browser, it just so happens that some legacy software uses it (meaning the security vulnerabilities are a feature) and some... elderly people will not switch. 
Can you add a 'This is an unsupported browser' warning? I could put a link to some static asset in it.
