### ISSUE TITLE
Suggestion: Remove the automatic addition of url() with background-image.

### ISSUE THREAD

**Issue by olerap** [bastienwirtz/homer#343]
Hi Bastien,

First of all I would like to thank you for the amazing work to the self-hosted community.
I personally love homer and believe there are many like me.

Today I wanted to change the background of homer to a gradient, but it didn't work. I tried to add `background-image:  (linear-gradient(90deg,#5c2483,#0095db)` to my config.yml but Homer automatically added url(x) to the css. How could this be resolved?

Kind regards,

Ole

**Comment by knuurr** [comment]
Still actual. Minor thing but how frustrating.

**Comment by JamieMcH** [comment]
1. Copy `src/assets/app.scss` from the repo to `assets/custom.css` in your container.

2. Uncomment the following in your config.yml file:
```yml
stylesheet:
  - "assets/custom.css"
```

3. Edit the following section of your new `custom.css` file:

*Original*
```yml
#app{height:100%;background-color:var(--background)}
```

*New*
```yml
#app{height:100%;background:var(--background)}
```

4. Set your gradient using:
```yml
colors:
  light:
    background: "linear-gradient(90deg, #5c2483, #0095db)"
```

**Comment by bastienwirtz** [comment]
Hello there, 

The custom.css solution proposed by @JamieMcH is the way! it can covers any need of customization. It has been added to [the documentation](https://github.com/bastienwirtz/homer/blob/main/docs/theming.md#additional-stylesheets). Thanks!
