### ISSUE TITLE
Replace Font Awesome with Fork Awesome?

### ISSUE THREAD

**Issue by virtadpt** [bastienwirtz/homer#346]
Font Awesome is nice, but it has a limited icon set unless you buy a license for the latest version, patch Homer, and rebuild.  [Fork Awesome](https://forkaweso.me/Fork-Awesome/), on the other hand, does not have this limitation and is considered open source ([even by the FSF](https://www.gnu.org/licenses/license-list.html#SILOFL), for folks who care about that sort of thing).  The icon set is significantly less limited at the outset and is even self-hostable.  Maybe it would be worth considering changing over to it?

**Comment by JuryA** [comment]
+1

**Comment by taita2104** [comment]
+1

**Comment by ledicjp** [comment]
+1

**Comment by svenEsven** [comment]
+1

**Comment by bastienwirtz** [comment]
Hi there! 

I wasn't aware of Fork Awesome, It sounds like a good choice. Is it the same icon class ? Is it going to break everyone's icons?

**Comment by virtadpt** [comment]
[This page](https://forkaweso.me/Fork-Awesome/whats-new/) on the Fork Awesome website says "We paid special attention not to change unicode codepoints for the existing icons, nor changed the CSS class names or icon names from Font Awesome 4.7. Though we added a few more icons and made the process of contributing to this project much easier."

[The examples page](https://forkaweso.me/Fork-Awesome/examples/) shows what appear to be compatible CSS class names.

I'm not trying to be a jerk (if I'm coming across that way, I apologize, that was not my intention), I'm trying to show what I found in the hopes that, if I'm wrong someone will correct me.

**Comment by bastienwirtz** [comment]
All right. 

@Skaronator @Simon-the-Sorcerer, why all the :-1: ?

**Comment by bastienwirtz** [comment]
Font awesome claim to have [1,748 icons free & open source icons](https://fontawesome.com/search?m=free) available, while Fork awsome seem to have [796 icons](https://forkaweso.me/Fork-Awesome/icons/) :thinking:

**Comment by Skaronator** [comment]
@bastienwirtz There are [Github Reactions](https://docs.github.com/en/rest/reference/reactions) to avoid unnecessary comments. The "+1" comments create a lot of noise in my mailbox.

**Comment by Simon-the-Sorcerer** [comment]
> @Skaronator @Simon-the-Sorcerer, why all the -1 ?

To educate people to use the "+1". :-)

**Comment by xf-** [comment]
@bastienwirtz yeah, but font awesome has a lot of sponsored icons from company's e.g. Amazon pay and also redundancy with 6 bridges and additional similar stuff for maps. If somebody wants no footer line, it isn't CC license complaint.

**Fork awesome**
800 Icons without redundancy should be fine and more open source icons like the GNU or MariaDB/Postgres. Open source projects a lot of people use on and maybe want to link in Homer. Font Awesome has no PRs or Icons requests anymore. It is only easy to get a commercial icon/sponsorship into free library.
