### ISSUE TITLE
Anonymous volume defined in Dockerfile blocks copying config.yml

### ISSUE THREAD

**Issue by scot-t** [bastienwirtz/homer#347]
**Issue**
The homer Dockerfile [specifies an anonymous volume][1], which prevents modifying any files under that node in subsequent steps [ref][2]

As far as I can tell (eg [this article][3]) this line could be safely removed and would make configuring homer containers simpler. Is this possible?

**Context**
I'm running homer in a container with docker compose, deployed to a remote host using docker contexts. This makes passing the configuration from my repo as a bind mount difficult. I would like to copy config to the image as a build step. Currently I just copy it to `/www/config.yml` and let [this workaround][4] take care of it.

[1]: https://github.com/bastienwirtz/homer/blob/main/Dockerfile#L32
[2]: https://docs.docker.com/engine/reference/builder/#notes-about-specifying-volumes
[3]: https://boxboat.com/2017/01/23/volumes-and-dockerfiles-dont-mix/
[4]: https://github.com/bastienwirtz/homer/blob/main/entrypoint.sh#L8

**Comment by bastienwirtz** [comment]
Hi there, 

The Dockerfile does not include a volume instruction anymore :+1: 

Thanks,
