### ISSUE TITLE
Add clear button to search bar

### ISSUE THREAD

**Issue by andrewwiebe** [bastienwirtz/homer#35]
Hello,

Would love to see a clear button on the search bar to clear an active search. Even better would be a keyboard shortcut to focus the search bar and another to clear the search.

Thanks

**Comment by bastienwirtz** [comment]
Hey @andrewwiebe! 

That's a very cool idea, thanks! Not only it's a good idea, but @jozefs implemented it, and it just got merged! You should be able to update and use it.
