### ISSUE TITLE
Question: Possible to add a widget from the web interface

### ISSUE THREAD

**Issue by UmanGarbag** [bastienwirtz/homer#350]
Hello Bastien,

Is it possible to add a feature in the roadmap, the purpose is add/delete/change widget since the web interface ?

I would like ta add this feature, but my experience in web programming is very limited. (Can you have some ressource for implement this feature ?)

Thanks you

**Comment by UmanGarbag** [comment]
Add a new a widget or modify the css from the web interface. This would allow users not to manipulate a yaml file

**Comment by bastienwirtz** [comment]
Hi @UmanGarbag ! 

It's not possible to add this feature, as Homer is a **static** homepage, build with only client javascript. To modify the config file you would need a server component which is exactly what Homer try to avoid. There is a lot of other very good dashboard with configuration editor out there, you should easily find an alternative if you want. 
Also, you can use an other tool to manipulate / manage the yaml configuration file (I use Ansible and a jinja template).
