### ISSUE TITLE
ARMv6 support

### ISSUE THREAD

**Issue by d4rklynk** [bastienwirtz/homer#352]
I tried to install homer with docker on raspberry zero W but it didn't work.
I search on docker hub and there's no version of it. Is there a workaround to install on Rpi Zero ?

**Comment by bastienwirtz** [comment]
Hey @d4rklynk, 

The ARMv6 build is available on the latest tag and will be version tagged in the next release.
I'm closing the issue but feel free to reopen if anything :)
