### ISSUE TITLE
Offline message improvement request

### ISSUE THREAD

**Issue by afreiberger** [bastienwirtz/homer#359]
https://github.com/bastienwirtz/homer/blob/f3b3b89b7c037584a2c3ad463b9d0322d28f0f89/src/components/ConnectivityChecker.vue#L5

"You're offline friend" seems mildly informal and not specifically accurate.

I think it would be helpful if this noted that the client can't reach the server, as I'm most definitely online, but maybe my homer server is offline, disconnected from my current network, or my vpn is dead.  I'd rather see this noted as "Server <ip address or dns name> is unreachable."

However, if you'd like to keep the original message, I suggest adding a comma for grammatical improvement.

"You're offline, friend."

**Comment by florian-obradovic** [comment]
How can we disable "You're offline friend" and disable caching.
Especially when you roam between networks (internal / external) with different DNS records pointing to Homer...
