### ISSUE TITLE
Remote Item, Service

### ISSUE THREAD

**Issue by ipedrazas** [bastienwirtz/homer#361]
Perhaps what I’m going to describe can be done already using the current services but I couldn’t figure out how to do it.

I don’t think my use case is very common: I have a few apps that I connect to using a VPN and having the external IP in the subtitle helps me not having to remember them 😄 What I do is to have an endpoint in `Node Red` that checks the external IP of the application/VPN and returns a json that contains a service item with the IP in the subtitle.
In reality, the service doesn’t care what the content of the returned service item is, it just fetches it from a remote location.

I thought that the `Generic` service could do it, but if it does, I’ve failed to find the correct configuration.

Anyway, I’ve created a new service that I call `Remote`.  Not sure if you’re interested on it, but I’m happy to send the PR with it.

If this can be done already and someone could point me to the right doc/config, I’ll be more than happy to send a PR to the docs to make it more obvious. 🙌

**Comment by bastienwirtz** [comment]
Hi @ipedrazas ! 

It's not possible to do that with the Generic service (or any other service). 
It does sounds a bit too specific, I'm gonna close the issue but I'll keep it in mind if this need comes up in the future. Thanks for your proposition !
