### ISSUE TITLE
Ping reports URLs are offline that are working

### ISSUE THREAD

**Issue by dimo414** [bastienwirtz/homer#362]
Notably, the [example](https://github.com/bastienwirtz/homer/blob/main/docs/customservices.md#ping) doesn't appear to work:

```
$ diff -u config.yml.dist config.yml
--- config.yml.dist     2022-01-19 01:25:18.226569416 -0800
+++ config.yml  2022-01-22 17:16:46.671787583 -0800
@@ -82,3 +82,9 @@
         subtitle: "Another application"
         tag: "app"
         url: "#"
+      - name: "Awesome app"
+        type: Ping
+        logo: "assets/tools/sample.png"
+        subtitle: "Bookmark example"
+        tag: "app"
+        url: "https://www.reddit.com/r/selfhosted/"
```

Reports r/selfhosted is offline:

![Screenshot of demo Homer page with Ping example added](https://user-images.githubusercontent.com/1885701/150660898-e2a16a81-b2cc-4ddf-a326-f9fa84f9a6c0.png)

I've tried a number of different URLs, including remote websites, local services, and services on the same machine, but all fail _except_ `http://same-machine.lan:9001/admin`, which is one of the URLs for reaching my pi-hole install running in a separate container. Other URLs, such as http://pi.hole:9001/admin` or even its IP address `http://192.168.1.20:9001/admin`, both of which resolve in my browser, report as offline.

I saw #249 mentions a "CORS issue" though I don't totally follow what that is or when it's a concern, but I assume that issue shouldn't apply for the provided example URL, right? I also left a comment in 2fba043575 which seemed odd to me.

@stubbfel FYI

**Comment by stubbfel** [comment]
@dimo414 

Sry, but also for the url from example (the response from the server),  the  "CORS-Header" (Access-Control-Allow-Origin *) is missing.

API-Endpoints set mostly this header, e.g https://api.github.com/zen

See the header from the http response
 https://websniffer.cc/?url=https://api.github.com/zen

**Comment by dimo414** [comment]
At a minimum it'd be good to clarify the documented example doesn't work, then. What is required for a URL to work?

**Comment by stubbfel** [comment]
@dimo414 There is no requirement for the url themself. 
The server/endpoint have to add "Access-Control-Allow-Origin: *" to the response headers.

https://github.com/bastienwirtz/homer/blob/main/docs/troubleshooting.md
