### ISSUE TITLE
Bad performance on chromium based mobile browsers

### ISSUE THREAD

**Issue by Keltere** [bastienwirtz/homer#368]
Hi. I've discovered that homer dashboard is stuggering on any chromium based mobile browsers while on Firefox and Samsung browser it doesn't.

[Here is a video](https://drive.google.com/file/d/1-2-HXNT3FrhYgF8RKLQPnBV_zvuuZ1XO/view?usp=drivesdk) 

Browsers stuggering: chrome, edge, brave, bromine, kiwi, vivaldi
Not stuggering: Firefox, Samsung browser

**Comment by iamrony777** [comment]
Hmm i had same problem with Brave Browser too , infact i was configuring my dashboard and brave was crashing repeatedly , then i moved to Firefox now its fine

**Comment by bastienwirtz** [comment]
Hi there, 

A lot has changed recently, including a major upgrade of Homer's base framework (vuejs2 -> vuejs3). Let me know if you still experience this issue.

**Comment by iamrony777** [comment]
Yeah, it's working fine

**Comment by bastienwirtz** [comment]
All right I'm closing the issue, feel free to reopen is anything
