### ISSUE TITLE
Multiple Tags?

### ISSUE THREAD

**Issue by kimdre** [bastienwirtz/homer#372]
Hi,

Is it possible to apply multiple tags to a single service in the dashboard?

**Comment by Roundaround** [comment]
Hi @kimdre, at the moment it's not possible to specify multiple tags. The main reason for this is that there's limited space on the cards, and making a consistent style with a potentially open-ended list of child elements is a non-trivial task.

One potential solution would be to allow specifying tags and aliases that simply don't render on the card, but work when searching. This could open the door to more advanced search-based categorization for large dashboards. Would this work for you, or do you specifically need multiple visual tags?

**Comment by kimdre** [comment]
As long as I can find them in the search bar I would be totally fine with that 👌😄
Or maybe just hide the additional tags behind a "..." Or "show more" could also be solution that could work

**Comment by GRMrGecko** [comment]
I think the idea is a keywords array with different keywords that can be searched for. For an example, OPNsense could have the keywords vpn, router, vlan, network added to it so when I come to the dashboard and am thinking "What was it that I used to setup the VPN?" I could just search VPN and OPNsense would popup.
