### ISSUE TITLE
AdGuard Home CORS error

### ISSUE THREAD

**Issue by saschabrockel** [bastienwirtz/homer#384]
Hey there. I don't know why Adguard Home has the status unknown in my Homer instance but the browser logs show the following:
```
Access to fetch at 'http://192.168.178.29:3000/control/status' from origin 'http://192.168.178.29:8081' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
main.js?attr=6WkYTvBwPS9lR6oVtv9WdyWc0x6tzySEgkBBJyuyCQaZ8Mev479ldh0qW8byHKyd:2671          GET http://192.168.178.29:3000/control/status net::ERR_FAILED 200
fetchCallImpl @ main.js?attr=6WkYTvBwPS9lR6oVtv9WdyWc0x6tzySEgkBBJyuyCQaZ8Mev479ldh0qW8byHKyd:2671
window.fetch @ main.js?attr=6WkYTvBwPS9lR6oVtv9WdyWc0x6tzySEgkBBJyuyCQaZ8Mev479ldh0qW8byHKyd:2673
(anonymous) @ service.js:34
e @ service.js:15
(anonymous) @ AdGuardHome.vue:65
f @ runtime.js:63
(anonymous) @ runtime.js:294
(anonymous) @ runtime.js:119
r @ asyncToGenerator.js:3
c @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
e @ AdGuardHome.vue:64
created @ AdGuardHome.vue:58
re @ vue.runtime.esm.js:1863
Un @ vue.runtime.esm.js:4235
t._init @ vue.runtime.esm.js:5022
a @ vue.runtime.esm.js:5168
cn @ vue.runtime.esm.js:3304
init @ vue.runtime.esm.js:3133
h @ vue.runtime.esm.js:6022
d @ vue.runtime.esm.js:5969
(anonymous) @ vue.runtime.esm.js:6560
t._update @ vue.runtime.esm.js:3963
r @ vue.runtime.esm.js:4081
rr.get @ vue.runtime.esm.js:4495
rr.run @ vue.runtime.esm.js:4570
Xn @ vue.runtime.esm.js:4326
(anonymous) @ vue.runtime.esm.js:1989
fe @ vue.runtime.esm.js:1915
Promise.then (async)
ae @ vue.runtime.esm.js:1942
ve @ vue.runtime.esm.js:1999
er @ vue.runtime.esm.js:4418
rr.update @ vue.runtime.esm.js:4560
t.$forceUpdate @ vue.runtime.esm.js:3984
l @ vue.runtime.esm.js:3668
(anonymous) @ vue.runtime.esm.js:3690
(anonymous) @ vue.runtime.esm.js:336
Promise.then (async)
An @ vue.runtime.esm.js:3713
an @ vue.runtime.esm.js:3219
hn @ vue.runtime.esm.js:3455
dn @ vue.runtime.esm.js:3374
t._c @ vue.runtime.esm.js:3512
w @ Service.vue?e937:1
t._render @ vue.runtime.esm.js:3569
r @ vue.runtime.esm.js:4081
rr.get @ vue.runtime.esm.js:4495
rr @ vue.runtime.esm.js:4484
Nn @ vue.runtime.esm.js:4088
Or.$mount @ vue.runtime.esm.js:8459
init @ vue.runtime.esm.js:3137
h @ vue.runtime.esm.js:6022
d @ vue.runtime.esm.js:5969
b @ vue.runtime.esm.js:6097
d @ vue.runtime.esm.js:5998
b @ vue.runtime.esm.js:6097
d @ vue.runtime.esm.js:5998
b @ vue.runtime.esm.js:6097
d @ vue.runtime.esm.js:5998
b @ vue.runtime.esm.js:6097
d @ vue.runtime.esm.js:5998
b @ vue.runtime.esm.js:6097
d @ vue.runtime.esm.js:5998
b @ vue.runtime.esm.js:6097
d @ vue.runtime.esm.js:5998
(anonymous) @ vue.runtime.esm.js:6560
t._update @ vue.runtime.esm.js:3963
r @ vue.runtime.esm.js:4081
rr.get @ vue.runtime.esm.js:4495
rr.run @ vue.runtime.esm.js:4570
Xn @ vue.runtime.esm.js:4326
(anonymous) @ vue.runtime.esm.js:1989
fe @ vue.runtime.esm.js:1915
Promise.then (async)
ae @ vue.runtime.esm.js:1942
ve @ vue.runtime.esm.js:1999
er @ vue.runtime.esm.js:4418
rr.update @ vue.runtime.esm.js:4560
vt.notify @ vue.runtime.esm.js:730
set @ vue.runtime.esm.js:1055
ir.set @ vue.runtime.esm.js:4644
(anonymous) @ App.vue:194
f @ runtime.js:63
(anonymous) @ runtime.js:294
(anonymous) @ runtime.js:119
r @ asyncToGenerator.js:3
c @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
c @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
t @ App.vue:176
(anonymous) @ App.vue:167
f @ runtime.js:63
(anonymous) @ runtime.js:294
(anonymous) @ runtime.js:119
r @ asyncToGenerator.js:3
c @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
t @ App.vue:166
re @ vue.runtime.esm.js:1863
Un @ vue.runtime.esm.js:4235
t._init @ vue.runtime.esm.js:5022
a @ vue.runtime.esm.js:5168
cn @ vue.runtime.esm.js:3304
init @ vue.runtime.esm.js:3133
h @ vue.runtime.esm.js:6022
d @ vue.runtime.esm.js:5969
(anonymous) @ vue.runtime.esm.js:6560
t._update @ vue.runtime.esm.js:3960
r @ vue.runtime.esm.js:4081
rr.get @ vue.runtime.esm.js:4495
rr @ vue.runtime.esm.js:4484
Nn @ vue.runtime.esm.js:4088
Or.$mount @ vue.runtime.esm.js:8459
56d7 @ main.js:19
c @ bootstrap:89
0 @ app.d9f9cac1.js:1
c @ bootstrap:89
n @ bootstrap:45
(anonymous) @ bootstrap:267
(anonymous) @ app.d9f9cac1.js:1
Show 71 more frames
AdGuardHome.vue:66 TypeError: Failed to fetch
    at fetchCallImpl (main.js?attr=6WkYTvBwPS9lR6oVtv9WdyWc0x6tzySEgkBBJyuyCQaZ8Mev479ldh0qW8byHKyd:2671:25)
    at window.fetch (main.js?attr=6WkYTvBwPS9lR6oVtv9WdyWc0x6tzySEgkBBJyuyCQaZ8Mev479ldh0qW8byHKyd:2673:55)
    at a.<anonymous> (service.js:34:14)
    at a.e (service.js:15:10)
    at a.<anonymous> (AdGuardHome.vue:65:1)
    at f (runtime.js:63:40)
    at Generator._invoke (runtime.js:294:22)
    at Generator.next (runtime.js:119:21)
    at r (asyncToGenerator.js:3:20)
    at c (asyncToGenerator.js:25:9)
toolbarContentscript.js:113 {"message":"The message port closed before a response was received."}
```

![image](https://user-images.githubusercontent.com/33376463/154877029-02700420-4a4c-4df0-a3ee-de44967f68dc.png)

Any ideas on how to fix it? Another question is why Radarr and Sonarr are not showing anything for me. No color not blue or yellow or anything. But if I call them not out of my local network and instead by my subdomain dash.xyz.com it shows errors for both.

**Comment by bastienwirtz** [comment]
Hi there, 

Did you check this page: https://github.com/bastienwirtz/homer/blob/main/docs/troubleshooting.md  ? Your `AdGuard` service must be configured (request header) to accept request from Homer if the domain or port is different.

Hope it helps!

**Comment by Redmega** [comment]
@saschabrockel There's some relevant code/discussion in this issue: https://github.com/bastienwirtz/homer/issues/289#issuecomment-1038199009

**Comment by JordyEGNL** [comment]
![image](https://user-images.githubusercontent.com/65036298/165562621-e008e2b1-1e00-4430-a880-3618852d5dc7.png)
This is what worked for me using Nginx proxy manager

**Comment by DanielPiccoli** [comment]
> ![image](https://user-images.githubusercontent.com/65036298/165562621-e008e2b1-1e00-4430-a880-3618852d5dc7.png) This is what worked for me using Nginx proxy manager

2.34 is your adguard?
what did you configure on the first tab of the redirect ? (domain names) the IP ?

**Comment by JordyEGNL** [comment]
> what did you configure on the first tab of the redirect ? (domain names) the IP ?

![image](https://user-images.githubusercontent.com/65036298/166463225-b1eb6a8c-19ae-4749-ac65-74db3caa3239.png)
AdGuard is hosted on another device, thats why I specified an IP instead of container name

**Comment by Neeham** [comment]
@JordyEGNL I believe what @DanielPiccoli is asking is the information under the "Details" tab. More specifically he is wondering what have you put for Domain Names. Was it the IP? The IP with port? or an actual sub domain.

@DanielPiccoli Did you got it working? :P

**Comment by DanielPiccoli** [comment]
> @JordyEGNL I believe what @DanielPiccoli is asking is the information under the "Details" tab. More specifically he is wondering what have you put for Domain Names. Was it the IP? The IP with port? or an actual sub domain.
> 
> @DanielPiccoli Did you got it working? :P

No, I did not get it working

here is my setup

10.0.0.1 Edgemax router > Port forward inbound 80/443 to 10.0.0.5
10.0.0.4 is my adguard (outbound traffic DNS / filter)
10.0.0.5 is my NGINX Reverse proxy. 9using it as a reverse proxy only at the moment)

10.0.0.6 - HOMER

10.0.0.8 - service 1 - exposed externally as domain1.something.com
10.0.0.9 - service 2 - exposed externally as domain2.something.com

issue is trying to go from 10.0.0.6 (HOMER) to 10.0.0.4 > between these 2 IPs, internally (dockers) I have the CORS problem.
My nginx is only acting as an external reverse proxy, so my question was also trying to understand how to make the necessary configuration changes to make it work as intended.

any help on this matter is appreciated - Any configuration changes I can make on adguard service ? if yes, how ?

**Comment by DanielPiccoli** [comment]
perfect, got it working now

**Comment by JordyEGNL** [comment]
> perfect, got it working now

Cool! I think I will add a PR with a small tutorial on how to do this with nginx
