### ISSUE TITLE
[Request] Update to Font Awesome 6.0

### ISSUE THREAD

**Issue by tivolimeister** [bastienwirtz/homer#388]
Should be a one-liner or two.

**Comment by bastienwirtz** [comment]
Hi @tivolimeister, 

I'm actually considering switching to [Fork Awesome](https://forkaweso.me/Fork-Awesome/icons/), after @virtadpt suggested it in  https://github.com/bastienwirtz/homer/issues/346. 
Would that work for you?

**Comment by tivolimeister** [comment]
Looks like a better alternative.
