### ISSUE TITLE
希望能有一个按钮切换内网和外网的地址

### ISSUE THREAD

**Issue by leonyff** [bastienwirtz/homer#39]
我把有些服务转发到了外网。
我希望能够设置两个地址, 在主页可以有一个按钮,切换内网和外网的地址
Thank you！

**Comment by trolologuy** [comment]
> 我把有些服务转发到了外网。
> 我希望能够设置两个地址, 在主页可以有一个按钮,切换内网和外网的地址
> Thank you！

Thanks to deepl translation, the issue apparently:
> I forwarded some services to the extranet.
> I'd like to be able to set two addresses, with a button on the home page to switch between intranet and extranet addresses.

**Comment by bastienwirtz** [comment]
Hi there!

Sorry to have left you unanswered! 
@leonyff you should be able to use the dashboard on any network, that would be a matter of webserver / proxy configuration. For example you could have a vhost listing on 2 network interfaces.
