### ISSUE TITLE
Web page doesn't refresh, only updates in incognito mode

### ISSUE THREAD

**Issue by daurpam** [bastienwirtz/homer#392]
I'm trying to update my own homer web page using an automated  git script. It works without problems and it restart the docker container everytime I've made changes in code. 

The problem is when trying to browse the page doesn't update even refreshing it, but if I open an incognito tab loads perfectly showing  new changes.

How can I search the cache config inside de docker image o override to force webpage to refresh automatically?

Thanks

**Comment by andvg** [comment]
You should try to hard-refresh non-incognito tabs.
e.g. on chrome mac: cmd+shift+r
on chrome win: ctrl + F5

**Comment by daurpam** [comment]
It doesn't work, I've tried (obviously)

**Comment by Roundaround** [comment]
Given that this is a static webpage solution, this is working as intended by caching the content. In fact, this isn't even a caching solution provided by Homer or Docker - it's built in to your browser.

I have however noticed that sometimes a hard reload might not be enough to bypass the browser cache. If you're actively developing your dashboard and you run into this issue, you have two basic options:

1.  Add a URL parameter to the web address every time you want to force a reload, i.e. `http://192.168.1.50?cachebust=4`. Change/increment the number each time and your browser will load the page fresh.
2. Explicitly clear the cache for the site in your browser's settings, then do a hard reload. In Chrome, you can shortcut this by opening Dev Tools (`Ctrl+Shift+I` on Windows and Linux), then right clicking the reload button on the top right and selecting "Empty cache and hard reload".

**Comment by SHU-red** [comment]
Oh man!
I was struggling so hard why the changes did not apply.

Ctrl + F5 worked for me in Vivaldi on Linux

Thanks for the awesome work!
