### ISSUE TITLE
Portainer CORS Policy API block

### ISSUE THREAD

**Issue by traliotube** [bastienwirtz/homer#397]
Hi, when I added my  #Portainer API key to homer dashboard, this is the error

![image](https://user-images.githubusercontent.com/69894187/158556339-e7e9a2f6-67bd-4a81-9958-7a8323968899.png)

**Access to fetch at 'https://portainer.bunnylab.tk/api/endpoints' from origin 'https://bunnylab.tk' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.**

Here's my config.yml

      - name: "Portainer"
        logo: "https://avatars.githubusercontent.com/u/22225832?s=280&v=4"
        url: "https://portainer.bunnylab.tk"
        type: "Portainer"
        apikey:    ###"****"

I know this is a duplicate to https://github.com/bastienwirtz/homer/issues/296 but still, I dunno the solution to this yet.

**Comment by Roundaround** [comment]
See https://github.com/bastienwirtz/homer/blob/main/docs/troubleshooting.md. There's not a great one-click solution to it yet, but I do have #396 open discussing adding a better workaround for CORS-related issues
