### ISSUE TITLE
New Portainer service does not work

### ISSUE THREAD

**Issue by JordyEGNL** [bastienwirtz/homer#403]
Homer version:
 - Latest from docker as of 19 march
 Portainer version:
 - 2.11.1

Homer config:
![image](https://user-images.githubusercontent.com/65036298/159125882-1ed103df-db27-446a-8a12-68e35b878f0f.png)

**Comment by StinkyTACO** [comment]
i noticed this aswell

**Comment by Roundaround** [comment]
Could you provide the error message from Chrome dev tools? I suspect it will be a CORS issue. See https://github.com/bastienwirtz/homer/blob/main/docs/troubleshooting.md

**Comment by JordyEGNL** [comment]
> Could you provide the error message from Chrome dev tools? I suspect it will be a CORS issue. See https://github.com/bastienwirtz/homer/blob/main/docs/troubleshooting.md

![image](https://user-images.githubusercontent.com/65036298/159157698-7512031b-5108-4983-9509-4069ea372328.png)
![image](https://user-images.githubusercontent.com/65036298/159157771-40c57746-f6ca-45b9-a3eb-9f11fec3d919.png)

It says so, but I have added the CORS * header in Caddy.
![image](https://user-images.githubusercontent.com/65036298/159157753-778bd971-7cfc-4104-adf1-18d2e45adb4d.png)

**Comment by Roundaround** [comment]
My best guess is there's something going on in your Caddy layer. I've never used it myself so unfortunately I can't really point you in the right direction. Is there a way to log traffic handled by Caddy? Could potentially be something more useful there.

**Comment by jleseane23** [comment]
Adding to this.

I'm using cors-container. Using that, I was able to get Pi-Hole to work. But it's not working in Portainer version 2.11.1. I get a CORS error as well. 

- name: "Portainer"
        logo: "assets/icons/portainer.png"
        subtitle: "Container management"
        tag: "internal"
        url: "http://[server]:9000"
        endpoint: "http://[cors-container]:3000/http://[server]:9000"
        type: "Portainer"
        apikey: "ptr_D1+R[API]"

**Comment by StinkyTACO** [comment]
so how would one get this working ?

**Comment by bastienwirtz** [comment]
Hum :thinking:, I don't have a portainer setup to troubleshoot that. 
@Zareix Any idea ?

**Comment by Zareix** [comment]
Hey, I had a similar problem with portainer in some case the preflight was block due to how portainer HTTP(S) responses are handled.
I'm not using caddy but NGINX so I added the following to handle everything : 
```
if ($request_method ~* "(GET|POST)") {
      add_header "Access-Control-Allow-Origin"  *;
}

if ($request_method = OPTIONS ) {
      add_header "Access-Control-Allow-Origin"  *;
      add_header "Access-Control-Allow-Methods" "GET, POST, OPTIONS, HEAD";
      add_header "Access-Control-Allow-Headers" "Authorization, Origin, X-Requested-With, Content-Type, Accept,X-Api-Key";
      return 200;
}
```
The idea is that when the requested method is an "OPTIONS", we need to add the cors headers + allow method "OPTIONS/GET/POST" + authorize the "X-API-KEY" header (used by portainer api)

**Comment by Zareix** [comment]
However I'm not sure exactly why this is happening in our case, and if it is a bug or not with portainer tbh

**Comment by espilioto** [comment]
I had a CORS issues as well.
My portainer 2.11.1 instance (everything, actually) is behind Traefik, resulting in successful insomnia/postman requests but errors similar to yours from browsers.

Adding Homer's url to an allow origin list plus these headers fixed my issues:
- accessControlAllowOriginList: https://homerurl.goes.here
- accessControlAllowCredentials: true
- accessControlAllowHeaders: ["x-api-key, Origin, X-Requested-With, Content-Type, Accept, Authorization, JSNLog-RequestId, activityId, applicationId, applicationUserId, channelId, senderId, sessionId"] (most of these are unrelated to this, you should at least need Authorization)
- accessControlAllowMethods: GET,OPTIONS,PUT
- accessControlMaxAge: 100

(again, please note that this is my config and you might not need all of this, so you should remove stuff you don't need for security reasons)

No idea how to configure Caddy, but this should get you somewhere.
Another Traefik pitfall that made me lose my mind was that I forgot to apply the middleware containing those headers to the secure router 😢 
Not sure if Caddy has something similar, but if your endpoint is secured and you are positive that your config is correct it might be a similar issue.

Good luck!

**Comment by svenflender** [comment]
Hi all,
is there a solution other then use a proxy like nginx between?
Best Regards

**Comment by StinkyTACO** [comment]
> Hey, I had a similar problem with portainer, in some cases the preflight http method failed due to portainer not allowing X-Api-Key header somehow (or not the right way ?) and not allowing cors in preflight.
> 
> I'm not using caddy but NGINX so I added the following to handle everything :
> 
> ```
> if ($request_method ~* "(GET|POST)") {
>       add_header "Access-Control-Allow-Origin"  *;
> }
> 
> if ($request_method = OPTIONS ) {
>       add_header "Access-Control-Allow-Origin"  *;
>       add_header "Access-Control-Allow-Headers" "Authorization, Origin, X-Requested-With, Content-Type, Accept,X-Api-Key";
>       return 200;
> }
> ```
> 
> The idea is that when the requested method is an "OPTIONS", we need to add the cors headers + authorize the "X-API-KEY" header (used by portainer api). And when it's a GET/POST, only add the cors headers
> 
> Edit : If interested, here is how I used it in Nginx Proxy Manager <img alt="Screenshot 07-04-2022 at 22 44 29@2x" width="525" src="https://user-images.githubusercontent.com/29818713/162295894-5c4d51ec-9234-4c5b-b532-0b320bc8fa6e.png">

where would I add this in the nginx proxy manager ?
i tried advanced but that did not work

**Comment by Zareix** [comment]
> where would I add this in the nginx proxy manager ? i tried advanced but that did not work
@StinkyTACO 

Oups, I put the wrong screenshot, just updated it.
You need to create a new location with the same url/port with "/" (root) for the path. Then add all the above config in there.

**Comment by Roundaround** [comment]
@svenflender No, your only option is to put some kind of proxy between them. It doesn't necessarily have to be a full blown web server like nginx - you can write a simple proxy server/api in whatever language you prefer. Eventually we hope to add some better documentation and maybe even a first-party solution to this. See #396 for more info

**Comment by JordyEGNL** [comment]
> 

thanks this worked for me!
