### ISSUE TITLE
Icon color per tile

### ISSUE THREAD

**Issue by dmyoung9** [bastienwirtz/homer#406]
I've just figured out that we can change the background color per-tile (#153), and it appears we can also set the color for *all* icons (#307), but I'm wondering about changing the icon color *per-tile*.

For what it's worth, the icons I'm using are from the MDI set, using a custom stylesheet (#182).

Would this be possible?

**Comment by bastienwirtz** [comment]
Hello, 

From the yaml config, groups and individual tile can have a `class` attribute, which you can use to change the icon color of a whole group at once or a single tile.
