### ISSUE TITLE
qBittorrent custom service

### ISSUE THREAD

**Issue by espilioto** [bastienwirtz/homer#411]
Hey guys, I'm planning on creating a custom service for qBittorrent soon.

I noticed that its API only uses cookie-based authentication, and since I'm not a js guy I wanted to hear some opinions/best practices on how to implement some sort of persistency between requests, ideally without adding dependencies to the project.

For example, would localStorage be a good fit?
If so, how should it be used within the context of this project?

Thanks!

**Comment by bastienwirtz** [comment]
Hello, 

This as been [implemented and merged](https://github.com/bastienwirtz/homer/pull/540). Enjoy :)
