### ISSUE TITLE
Homer Site Title & Subtitle

### ISSUE THREAD

**Issue by XxAcielxX** [bastienwirtz/homer#413]
Hello,

I'm using Homer Dashboard (the homer.zip) and like it a lot as it is simple to setup and use, but there is one thing I'm unable to change & fix.

Before the site is actually loaded up or when I send someone my domain url, the title doesn't reflect the one I have set in the yml file.

Here is an example of it:
![Screenshot_20220331-120212~2](https://user-images.githubusercontent.com/21063358/160999082-798d4d7f-a744-4178-a66a-da082c90c4f3.jpg)

In my case it should be, "**Aciel Server | Dashboard**". How can this be fixed, kindly guide on this.

Regards~

**Comment by fbartels** [comment]
Hi @XxAcielxX,

without looking into this too deep i would say these are the default values that are used before the yaml config is loaded. To override these you either need to modify the html files after extracting them, or add a commit on top of the latest source and build it yourself.

**Comment by XxAcielxX** [comment]
Yes, I had to look through multiple files to finally figure it out. Needed to edit `index.html` which holds these info.

It can be edited for the zip version, but for docker container one, we will need mount point access to edit `index.html` & `favicon.ico` etc.

Kindly add this info to the guide section of the installation, so others don't have to go through such headache.

**Comment by Roundaround** [comment]
Your workaround is not really something I'd feel comfortable putting in the docs, since it is in essence a bit of a hack. Either way, I'm glad you found a solution that worked for you!

**Comment by victorcampeanu** [comment]
I also think this should be exposed as a setting. When someone sees this link it seems like my nickname is Homer (true story)

**Comment by virtadpt** [comment]
> Hi @XxAcielxX,
> 
> without looking into this too deep i would say these are the default values that are used before the yaml config is loaded. To override these you either need to modify the html files after extracting them, or add a commit on top of the latest source and build it yourself.

Editing the generated HTML files prior to deployment is how I've been doing it.  Editing the YAML config file is insufficient.
