### ISSUE TITLE
Set Homer as default page for new tabs in Brave

### ISSUE THREAD

**Issue by vitobotta** [bastienwirtz/homer#415]
Hi! I set Homer as default page for new tabs in Brave using the "New Tab Override" extension, but for some reason it doesn't work with Homer only and the page stays blank. It works with any other page. Any idea of why it wouldn't work with Homer? I would like my dashboard to be the default page when starting the browser and opening new tabs. Thanks!

**Comment by virtadpt** [comment]
I don't know if this still works or not, but here's a howto for setting your homepage: https://browserpulse.com/how-to-change-brave-browser-default-homepage/

**Comment by vitobotta** [comment]
I found another extension that works, [New tab redirect](https://chrome.google.com/webstore/detail/new-tab-redirect/icpgjfneehieebagbmdbhnlpiopdcmna) so problem solved. Thanks ! :D
