### ISSUE TITLE
Feature request: Add support for Simple Icons

### ISSUE THREAD

**Issue by loganmarchione** [bastienwirtz/homer#416]
[Simple Icons](https://simpleicons.org/) is an icon set for brands (e.g., Nike, Plex, Ansible, etc...) as opposed to Font Awesome, which has only a limited number of brands.

Simple Icons has [SVG icons](https://github.com/simple-icons/simple-icons), as well as a [font pack](https://github.com/simple-icons/simple-icons-font) (like Font Awesome). 

I don't know any Vue, but I'm guessing this `fa-fw` [from this line](https://github.com/bastienwirtz/homer/blob/31027f479157640bf8f3eafee443a182215176d5/src/components/services/Generic.vue#L19) would mess this request up, since Simple Icons doesn't use `fa-fw`. Their example is below.
```
<i class="si si-nike"></i>
```

**Comment by Roundaround** [comment]
I don't think it's likely we'll be adding something like this given that we wouldn't use any of the icons in the base app, and not everyone will even want to use them (personally I wouldn't), so it'd bloat the binary size for only a subset of users.

If you want, you could load their webfont on your own dashboard as a custom css file and use the icons yourself that way. You could even get cheeky with replacing the service card image with an icon using ::before or ::after css selectors. Let me know if you need any help!
