### ISSUE TITLE
Move/Center Service

### ISSUE THREAD

**Issue by FlyingPersian** [bastienwirtz/homer#417]
Hi
I have 4 services in total. The first one is quite long, the others about half the size. Right now I have three services per row. Is it possible to move the 4th service, which is in the 2nd row, right below the 2nd service of the first row? Those two services are about as long as the first one, so I wouldn't have to scroll to see the 2nd row. There is more than enough space below the 2nd service of the first row.

I hope it's understandable what I want :D 

Greetings

**Comment by espilioto** [comment]
Why not just set the layout to 4 columns?

If that's not acceptable, messing around with css sounds like the way to go.

**Comment by FlyingPersian** [comment]
> Why not just set the layout to 4 columns?
> 
> If that's not acceptable, messing around with css sounds like the way to go.

How do I set it to 4 columns? Didn't see anything in the wiki or config regarding that.

**Comment by espilioto** [comment]
https://github.com/bastienwirtz/homer/blob/main/docs/configuration.md?plain=1#L27

**Comment by FlyingPersian** [comment]
Thanks, I did not see that!
