### ISSUE TITLE
Truncate text to avoid overflow of card content

### ISSUE THREAD

**Issue by trolologuy** [bastienwirtz/homer#42]
When the "**name**" or "**subtitle**" defined in the _config.yml_ are too long, the text is overflowing from the card component or causing some unwanted line breaks.
Example below: 

![Screenshot_2020-04-24 Demo dashboard Homer](https://user-images.githubusercontent.com/16886290/80191725-67607a80-8616-11ea-908c-f0bad82bf594.png)

Would it be possible to add the functionality to automatically truncate the text?
For example with [this component](https://github.com/furey/vue-trunquee) ?

(BTW great project ;) )

**Comment by traeblain** [comment]
Bulma actually takes care of this with CSS.  There's already a PR ( #18 ) for it although it needs some work.

@bastienwirtz Thoughts on cleaning this up?

**Comment by bastienwirtz** [comment]
Hi there! 
Definitely, there you go: https://github.com/bastienwirtz/homer/commit/45d38d122645164cc384d379c170e0fdec447f77 ! 

Thanks for opening the issue @trolologuy and for the tips @traeblain!

**Comment by trolologuy** [comment]
Thanks a lot for the fast fix ! Have a nice day :) 
And if there are some easy issues or documentation / translation tasks with which you need help let me know.
