### ISSUE TITLE
"No ESLint configuration found"

### ISSUE THREAD

**Issue by OfficialCRUGG** [bastienwirtz/homer#420]
Hey! Just tried to set this up on my server. Installed NodeJS 16, globally installed yarn, cloned the repo, ran `yarn install`, ran `yarn build`. The last one returns an error though and fails:

```
 ERROR  Failed to compile with 1 error                                                           1:13:27 PM

Syntax Error: Thread Loader (Worker 0)
No ESLint configuration found in /var/www/main/src.


You may use special comments to disable some warnings.
Use // eslint-disable-next-line to ignore the next line.
Use /* eslint-disable */ to ignore all warnings in a file.
 ERROR  Build failed with errors.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Did I do anything wrong on my end? Is this a known issue? How would I fix it?

**Comment by Roundaround** [comment]
Hm, I can't seem to replicate. Can you try again on the latest commit?

Also what is the output of the following commands?

```sh
which node
node --version
which yarn
yarn --version
```

**Comment by bastienwirtz** [comment]
Hello, 

The project build config moved quite a bit since the VueJS 3 upgrade, this issue should not be possible anymore. I'm closing this, but feel free to reopen if necessary :)
