### ISSUE TITLE
Ping flags as Offline if response isn't 200 

### ISSUE THREAD

**Issue by HeyItsJono** [bastienwirtz/homer#425]
Even when using a CORS proxy, if an endpoint returns a non-200 response when Pinged, the service is flagged as Offline. I was wondering if there could be an option to only flag a service as offline if there is no response from the service, since many of my services (Plex, Jellyfin, Nextcloud, etc.) return non-200 responses to Ping's HEAD request even when they are up and running.

**Comment by SmartPhoneLover** [comment]
+1

**Comment by adirbd** [comment]
+1

**Comment by garret** [comment]
+1

**Comment by Tiv0w** [comment]
You should try to add the `endpoint` key for the configuration of each service that doesn't respond.

https://github.com/bastienwirtz/homer/blob/main/docs/customservices.md#common-options
>```yaml
> - name: "My Service"
>  logo: "assets/tools/sample.png"
>  url: "http://my-service-link"
>  endpoint: "http://my-service-endpoint" # Optional: alternative base URL used to fetch service data is necessary.
>  useCredentials: false # Optional: Override global proxy.useCredentials configuration.
>  type: "<type>"
>```

Then many services provide a specific endpoint for health checking.
From the list I gathered:
- Nextcloud: `/status.php`
- Jellyfin: `/health`
  (https://jellyfin.org/docs/general/networking/monitoring.html)
- Subsonic, Airsonic, Navidrome,...: `/ping`

From my testing, all these work with Homer.

You can try to search in the docs of your service if they provide such an endpoint (or you may have some luck with some Google/Reddit search).

**Comment by HeyItsJono** [comment]
Hey there, thank you for this! I have been using the endpoint key successfully for other services but there are plenty of services that don't provide an endpoint for a healthcheck or heartbeat. For example, Plex does not do this. So in that regard my original request would still be helpful.

**Comment by reikolydia** [comment]
+1

Plus if you are using cloudflare dns and nginx reverse proxy, the code is 502 but still shows service as online..
