### ISSUE TITLE
Bulma-Extensions

### ISSUE THREAD

**Issue by r4b8iiiiiit** [bastienwirtz/homer#427]
Hello, would it be possible to integrate Bulma-Extensions into Homer? [](https://bulma.io/extensions/)

**Comment by Roundaround** [comment]
What for exactly? Homer is a config-based system, so I'm not sure what use it would be

**Comment by r4b8iiiiiit** [comment]
> What for exactly? Homer is a config-based system, so I'm not sure what use it would be

Ideally I'd like to implement a few toggle switches on my page

**Comment by Roundaround** [comment]
Unfortunately I don't really see a way to allow people to do that via config without significant effort or complexity in the project. If you need interact-ability then honestly your best bet is to avoid Homer and build your own dashboard from scratch
