### ISSUE TITLE
Add CI to publish project automatically to DockerHub

### ISSUE THREAD

**Issue by JesusMtnez** [bastienwirtz/homer#43]
Have you considered using a CI to build and publish the docker image automatically? There are several options:

- GitHub Actions _<- I would recommend that one_
- TravisCI
- CircleCI

It would be possible also to publish the image not only for `amd64` systems but also for `arm` ones.

**Comment by bastienwirtz** [comment]
Hi @JesusMtnez!

The docker image is already automatically build on docker hub (direct github integration). But I'll look into the arm issue soon and might consider a CI if necessary (if it can be done without it's better, #lessismore).

**Comment by nightah** [comment]
@bastienwirtz you can build arm images with direct Docker integration just takes a little magic. If you like and time permitting, I can submit a PR?

**Comment by bastienwirtz** [comment]
@nightah Of course, that would be awesome!
