### ISSUE TITLE
Footer overlaps Buttons

### ISSUE THREAD

**Issue by SHU-red** [bastienwirtz/homer#434]
If many buttons are configured or maybe homer is visited via cellphone, the lowest buttons are overlaped by the footer.
Sometimes its a big part of the button.

Seems like some space with the height of the footer could/should be added to be able to fully access all buttons.

**Comment by Roundaround** [comment]
Fixed with [6e4410d](https://github.com/bastienwirtz/homer/commit/6e4410d8f144e3ab2ff22444313f2a3c3a24c29c).
