### ISSUE TITLE
Starting at boot

### ISSUE THREAD

**Issue by trusk89** [bastienwirtz/homer#435]
Can someone point me in the directions of a tutorial of starting it at boot? I don't have docker on the machine im running it, but I do have npm and node (i'm running it now with npx). Thank you

**Comment by Roundaround** [comment]
Running it "in production" (24/7 uptime, regardless of if its just for you internally) via node/npm is not recommended. If you don't want to use docker, your best bet will be to build the dashboard with `yarn build` and host the files output in the `dist/` folder with some kind of web server like nginx (or the lighttpd service used by the docker container internally).

**Comment by trusk89** [comment]
thank you for the hints, I'll try it with yarn

**Comment by trusk89** [comment]
gave up and installed docker, thank you!
