### ISSUE TITLE
Ability to sort list or filter list by Status

### ISSUE THREAD

**Issue by dotspecialists** [bastienwirtz/homer#436]
I have more than two thousand websites I monitor using this easy-to-use awesome tool.  When I do see two sites down, it's difficult to find the sites being impacted as there seems to be no way to filter the list by up, down or paused sites.  It would nice that under Quick Stats, each stat number is a hyperlink to a filtered list showing all sites that have a matching status.

Thanks.

**Comment by Roundaround** [comment]
Is this perchance meant to be a request for [Uptime Kuma](https://github.com/louislam/uptime-kuma)? :)

**Comment by dotspecialists** [comment]
Yes, this is for uptime Kuma.  When I am in the dashboard and it says I got a few sites down, I have to scroll through the list of 2000 sites to see which one has the red tick.  It would be able to filter them somehow. Please see iamge: https://i.imgur.com/uP9VJgH.png

**Comment by Roundaround** [comment]
This is the GitHub repo for Homer, not Uptime Kuma. You'll need to make your feature request [there](https://github.com/louislam/uptime-kuma/issues/new?assignees=&labels=feature-request&template=feature_request.yaml)
