### ISSUE TITLE
Automatic Service Discovery

### ISSUE THREAD

**Issue by arunoruto** [bastienwirtz/homer#445]
If we are using a dashboard, we usually have also other services running, probably behind a reverse proxy like nginx, traefik, etc. We also configure those services for the reverse proxies using the compose files, either with environmental variables or using labels. Both of those properties can be viewed using the `docker inspect <container name>` command, hence they can be fetched. It would be quite convenient if homer could do that fetching for us and automatically create the dashboard for us. A similar implementation has been done for the [flame dashboard](https://github.com/pawelmalak/flame), but here you need to manually provide the labels for the flame config. That means I need to write down the url of the container twice, once for traefik (my reverse proxy) and then for flame too, but just reading the rule from traefik would do the trick too (most of the time).

I know it is asking a lot probably, but maybe someone likes the idea too and has the knowledge and motivation to implement it :)

**Comment by vincentDcmps** [comment]
take a look on https://github.com/calvinbui/homer-service-discovery

**Comment by wsw70** [comment]
https://github.com/calvinbui/homer-service-discovery is now archived and unmaintained

**Comment by Pro-Tweaker** [comment]
Hello @arunoruto @vincentDcmps @wsw70,
I have forked and updated homer-service-discovery [here](https://github.com/pro-tweaker/homer-service-discovery) to work with latest docker client api version.
Enjoy

**Comment by NikitaMikhailov** [comment]
If you'd rather not run a permanent daemon with docker.sock mounted next to Homer, dashsync is a one-shot CLI instead. Run it from cron or a systemd timer, it writes config.yml and exits. Nothing runs continuously.

https://github.com/NikitaMikhailov/dashsync
