### ISSUE TITLE
Feature: RSS feed

### ISSUE THREAD

**Issue by vosdev** [bastienwirtz/homer#446]
This is a feature request

I would like to see if there's people interested in having an RSS feed included in homer, and if there are developers willing to create this

You can show your interest with emojis

**Comment by bastienwirtz** [comment]
Hey @vosdev, 

So, you mean a custom that display the latest rss content title for exemple ?

**Comment by JamiePhonic** [comment]
You can technically already do this (in a roundabout way) using the Dynamic Message feature and a Node-Red flow as described in the [Tips & Tricks Doc](https://github.com/bastienwirtz/homer/blob/main/docs/tips-and-tricks.md#get-the-news-headlines-in-homer)

In theory you could also use an RSS to JSON service (like the aptly named [RSStoJSON.com](https://rss2json.com/)) and the Mapping Fields feature (also described in the Tips & Tricks Doc)

**Comment by luixal** [comment]
I think @vosdev was talking about, for example, a sidebar on the right side that shows a list of news from an RSS feed.

It could make sense if you use home as your default page on new tab. Wouldn't be so hard to implement, but it won't be a custom service as this are contained in a small card.

**Comment by vosdev** [comment]
Yes, I use homer as a default page on my new tabs. It's amazing :-)

**Comment by luixal** [comment]
IMHO, this could be a good addition, but would change the main layout (only when using the rss feature) and would need to add a dependency to query and parse RSS feeds.

I can work on this if you feel like this is a good feature @bastienwirtz .

**Comment by bastienwirtz** [comment]
Hi there, 

I'm not willing to change the layout to add a sidebar, but a custom service is possible (ideally any additional dependency would be loaded dynamically by the component if used).

**Comment by luixal** [comment]
Hi,

Then I think it is better to abandon this idea. Wouldn't make sense to integrate an rss feed just to show the news count.

Cheers!
