### ISSUE TITLE
Feature request: Multiple pages

### ISSUE THREAD

**Issue by TheRealRWJ** [bastienwirtz/homer#447]
Love your app.
Wish I found it sooner.

Categories, works great, but the list is getting too long especially on my phone

My request is using multiple pages. i.e. by using multiple config files like iot.cfg , default.cfg school.cfg
Or is there already an option to choose another config file using the url?
If so, the top menu could be used to switch

I hope I gave you some usefull ideas

Thanks in advance

RWJ

**Comment by Roundaround** [comment]
Hi RWJ!

It's not super obvious from the documentation, but if you look in the [configuration](https://github.com/bastienwirtz/homer/blob/main/docs/configuration.md) page, you should see the links section where we have a link pointing to `#page2`. If you add a link like that, and a file in the same assets directory called `page2.yml`, it'll create a new page and link to it! All of the configuration gets inherited from the main config (like the theme, header & footer, etc.) and you can define a new, separate list of services to be displayed!

**Comment by TheRealRWJ** [comment]
Ofcouse .... Already built in ....
What was I thinking ...

Got it working
Thanks for the very fast
 response
