### ISSUE TITLE
Homer with http basic auth issue after web service restarted & doesn't work in Edge android 

### ISSUE THREAD

**Issue by wy580477** [bastienwirtz/homer#456]
- I put homer behind caddy basic auth with following Caddyfile config:
```
handle {$GLOBAL_PORTAL_PATH}* {  
        redir {$GLOBAL_PORTAL_PATH} {$GLOBAL_PORTAL_PATH}/         
        uri strip_prefix {$GLOBAL_PORTAL_PATH}
        basicauth {              
                {$GLOBAL_USER} HASH
        }
        root * /workdir/homer
        file_server
}
```
- After my caddy service restarted each time, visit homer page will give this error instead of asking me for user:password.
![image](https://user-images.githubusercontent.com/98247050/170614417-854b7da5-56a1-4b46-afcd-258fe2a7fb18.png)
- I have to press F12 or Shift+F5, then the page will ask for user:password.

- On Edge android, Homer with http basic auth doesn't work at all. After login, it will show this error in a few seconds.
![image](https://user-images.githubusercontent.com/98247050/170614417-854b7da5-56a1-4b46-afcd-258fe2a7fb18.png)

**Comment by fbartels** [comment]
https://github.com/bastienwirtz/homer/pull/448 Fixed this for me

**Comment by wy580477** [comment]
> #448 Fixed this for me
> 
> edit: the edge thing is something else however

Thx for help. I will try it out.

Is there a way to disable connection check? I have little need for that.

**Comment by wy580477** [comment]
I build a release with github action from [bemble's repo](https://github.com/bemble/homer)

https://github.com/wy580477/homer/releases/latest/download/homer.zip

This fix my issues.  Edge android will ask for use:password every time when I open the page.
