### ISSUE TITLE
Feature Request: iFrame support if possible

### ISSUE THREAD

**Issue by Joeharrison94** [bastienwirtz/homer#46]
Would it be possible to allow the tabs to open in an iFrame so that I never have to leave the Homer location, obviously if it turns Homer into a resource hog or goes sluggish then please disregard this request.

**Comment by bastienwirtz** [comment]
HI @Joeharrison94!

That's a good idea but I would like to keep this page as light and simple as possible, and I know that some other full featured dashboard supports iframe and are good option for people looking for that. 
Thanks!
