### ISSUE TITLE
container: unhealthy; log: clock jumped

### ISSUE THREAD

**Issue by Alexgamer470** [bastienwirtz/homer#460]
I just wanted to setup Homer, because I thought it looks very good but it just doesn't seem to work. It's just repeatedly restarting, while repeatedly saying:
```
server started (lighttpd/1.4.64)
4147-08-20 07:32:16: (server.c.263) warning: clock jumped -68719476736 secs
4147-08-20 07:32:16: (server.c.271) attempting graceful restart in < ~5 seconds, else hard restart
1970-01-01 00:00:00: (server.c.1011) [note] graceful shutdown started
1970-01-01 00:00:00: (server.c.2077) server stopped by UID = 1000 PID = 1
```
I tried it on my raspberry with docker first and then with portainer and both didn't work.
I also have a static IP adress setup with dhcpd and maye that causes issues? I look forward to your replies!

**Comment by KptBlaubaer** [comment]
Hey 👋,
I had today the same issu while trying to update to the latest image.
If I go back to the older image everything works fine. 

In my case Homer runs on a Raspberry Pi 4 with the latest Docker version.

**Comment by bastienwirtz** [comment]
Hi there, 

Thanks for reporting this, I haven't tested the migration to lighttpd on a raspberry pi, I will look into this asap, I need to re-setup my raspberry pi. I'll keep you posted.

**Comment by Alexgamer470** [comment]
Hi, thanks for your reply!
I just restet my raspberry pi downloaded the latest image (64-bit, but I
don't think that it's necessary) and also changed the image installation
settings to disable telemetry. I don't know if that was the problem, or my
rpi was just messed up, but it works now flawlessly.

Bastien Wirtz ***@***.***> schrieb am Sa., 4. Juni 2022,
09:44:

**Comment by huddlesj** [comment]
Ran into the same issue. Ended up going back to the b4bz/homer:21.09.2  image till this is fixed.

**Comment by gstrauss** [comment]
I haven't seen such an incredibly future timestamp!
```
server started (lighttpd/1.4.64)
4147-08-20 07:32:16: (server.c.263) warning: clock jumped -68719476736 secs
4147-08-20 07:32:16: (server.c.271) attempting graceful restart in < ~5 seconds, else hard restart
1970-01-01 00:00:00: (server.c.1011) [note] graceful shutdown started
1970-01-01 00:00:00: (server.c.2077) server stopped by UID = 1000 PID = 1
```
lighttpd tries to protect embedded systems from their own forgetful selves when those embedded systems do not have persistent clocks across reboots.  If the clock changes by too much, lighttpd restarts.  Without doing so, some underlying libraries might misbehave, such as lighttpd's use of OCSP stapling in openssl, or anything else pertaining to certificates which have constrained lifetimes.  Concrete example: if you have a TLS certificate, it likely expires prior to the year 4147.  OCSP stapling files also have validity dates, almost always shorter than the certificate lifetime.

The clock jump threshold in lighttpd defaults to 1800 seconds (30 minutes) and can be configured using [server.feature-flags](https://wiki.lighttpd.net/Server_feature-flagsDetails)
`server.feature-flags += ( "server.clock-jump-restart" => 1800 )`
You can set the value to 0 to disable lighttpd server restart regardless of the skew size, but YMMV and doing so is not recommended if using TLS.

**Comment by bastienwirtz** [comment]
@gstrauss I see, Thanks for the information!
I think we can safely disable this feature, TLS is not handled in homer container and will usually be setup in a reverse proxy or something like that. I will update the config asap.
