### ISSUE TITLE
IPv6 support? Change TCP port

### ISSUE THREAD

**Issue by theotherguy2175** [bastienwirtz/homer#466]
Does homer support ipv6? 

I am using docker network ipvlan and therefor do not use dockers built in NAT. I was able to get ipv4 to work on tcp port 8080. 

How ever it would be nice to change a config or something to listen on 80 and be able to use ipv6.

**Comment by Espo02** [comment]
Hi

I'm trying to run homer behind a traefik proxy. But I would use Port 80. 
I don't know how to redirect port 80:8080 with trafik and would change the homer from 8080 to 80.

**Comment by bastienwirtz** [comment]
HI there, 

You can change Homer container internal port by using the `PORT` env variable. 
@theotherguy2175 there is no specific ipv6 support, and I don't really know what's required and could be missing. Could you explain what would it take to make it IPv6 compatible ?

**Comment by Sakoes** [comment]
Adding following lines to the lighttpd.conf file worked for me to make it IPv6 compatible:
```
server.bind = "0.0.0.0" 
$SERVER["socket"] == "[::]:8080" {  }
```
This is based on lighttpd recommended IPv6 setup documentation: https://redmine.lighttpd.net/projects/lighttpd/wiki/IPv6-Config.

**Comment by theotherguy2175** [comment]
I don't see any file in the system ' lighttpd.conf'

**Comment by bastienwirtz** [comment]
:wave: 
ipv6 support [has been merged](https://github.com/bastienwirtz/homer/pull/643) and will be released soon.

**Comment by marquesj2-ppb** [comment]
Hi 👋 

Would it be possible to make IPV6 configuration optional?

With the latest changes it started crashing
```bash
Starting webserver
2023-05-15 15:33:49: (network.c.387) socket: Address family not supported by protocol
```

**Comment by bastienwirtz** [comment]
@marquesj2-ppb @smandon Sorry about that! I should be able to add an env var to enable or not ipv6, I'll look into it asap !
