### ISSUE TITLE
Homer shows "You're Offline Friend" after 30 seconds

### ISSUE THREAD

**Issue by rarick** [bastienwirtz/homer#468]
# My setup
- traefik as a reverse proxy & domain controller
- [thomseddon/traefik-forward-auth](https://github.com/thomseddon/traefik-forward-auth) as my forward auth provider
- auth0 as my oauth provider
  - All my domains and wildcards are entered in auth0 for CORS/origins

# The issue
Homer is behind the authorization proxies. I am seeing "You're offline friend" after 30 seconds on homer. I'm not offline, and I can always reload the page without issue (hard reload as well). I see that the request is to `mydomain.com?t=<unix timestamp>`. This is receiving a 500 error, but I don't know where this response is coming from.

I see the request callstack starts with `checkOffline`.

Any ideas why this is happening?

**Comment by bastienwirtz** [comment]
Hi @rarick

Hum, that's weird. The connectivity check request (which can be disabled) if an `HEAD` request, maybe traefik block this kind of request? Can you tell if the request hit the container or not?
Is there a message associated with the 500 error ? Can you also check the container logs?

**Comment by zhenry9** [comment]
I have a nearly identical issue. 

Setup:

 - traefik2
 - thomseddon/traefik-forward-auth
 - Google oauth

I also get the "offline friend" message after 30 seconds, which is solved by refreshing. You mentioned the connectivity check could be disabled. How do you do this?

**Comment by Fratt** [comment]
Same problem here

**Comment by vincentvriends** [comment]
I have the same issue, but instead of traefik I use the Explicit Proxy build into a FortiGate firewall.
When I check the developer tools in my browser I see that a request is made to the following URL: http://dashboard.int.mydomain.be//index.html?t=1660243712402

So with 2 // instead of 1, this request gives back a 504 gateway timeout.

**Comment by bastienwirtz** [comment]
Thanks for the feedback, @zhenry9. Disabling the connectivity checker will workaround this issue.
@rarick @Fratt @vincentvriends Have you tried that?

That being said, the connectivity checker should work, it just periodically send a request to the server and execpt either an http response code in the  200-299 range OR a redirection (to handle auth proxy redirection, il this case the whole page reload and follow the redirection). If you don't need that, you should disable it anyway.

**Comment by c0pper** [comment]
Hi, where exactly do you find this connectivity check option? my config.yml only has things that should or hould not appear on the html page and theme related stuff... Thanks
