### ISSUE TITLE
Request for Help: font awesome support with docker?

### ISSUE THREAD

**Issue by issmirnov** [bastienwirtz/homer#47]
Hey @bastienwirtz - I love the project, and have been happily hacking away on a home server page. I've noticed that while developing locally everything is perfect, but for some reason when I deploy the dashboard remotely my Font Awesome images don't render.

Any thoughts? I've looked into potential issues with service workers, etc, but have no leads.

Details:
- Using simple config file (from README) + docker: `docker run -d -p $PORT:8080 -v $(pwd)/config.yml:/www/config.yml -v $(pwd)/webfonts:/www/webfonts -v $(pwd)/vendors:/www/vendors -v $(pwd)/assets:/www/assets b4bz/homer:latest`
- Result: http://162.243.159.167:8090/ 

Screenshot:

![image](https://user-images.githubusercontent.com/5771615/81036165-e5145980-8e52-11ea-82c9-bcc5081f8130.png)

I can confirm that the asset files are exactly from the repo:

```
$ tree                     
.
├── assets
│   ├── favicon.png
│   ├── logo.png
│   └── tools
│       ├── calendar.png
│       ├── elastic.png
│       ├── grafana.png
│       ├── habitory.png
│       ├── jenkins.png
│       ├── kibana.png
│       ├── monica.png
│       ├── monit.png
│       ├── netdata.png
│       ├── notes.png
│       ├── pingdom.png
│       ├── rabbitmq.png
│       ├── todoist.png
│       ├── ynab.jpg
│       └── ynab.png
├── config.yml
├── run.sh
└── vendors
    ├── bulma.min.css
    ├── font-awesone.min.css
    ├── js-yaml.min.js
    └── vue.min.js
```

Any thoughts? Am I incorrectly mounting the docker folder, or is there some funky caching issue? Maybe the async css load is messing things up?

I've spent an evening on this to try and debug, but at this point I'm stuck :(

**Comment by fbartels** [comment]
Hi,

your site wants to load http://162.243.159.167:8090/assets/homer.png, but  there is no homer.png in your file listing above.

Not sure though why the fonts are not displayed. The fontfile seems to be downloaded and the key used for e.g. heartbeat looks correct as well.

**Comment by issmirnov** [comment]
Hey,

Agreed on `homer.png`, that's expected. I copy pasted the README example as is to make it easier to repro. 

Any thoughts on the fonts? They seem to show up locally, and I can also clone the repo and serve the `index.html` directly. It only seems to be a problem with docker on remote machines.

**Comment by fbartels** [comment]
Ah, looking over your command you are mounting the font dir into the container `v $(pwd)/webfonts:/www/webfonts` maybe that folder is empty? its also not in your folder listing above. I think unless you are adding own fonts you can skip mounting it.

**Comment by issmirnov** [comment]
Whoops! You are absolutely correct. The `vendors` and `webfonts` directories did not need to be mounted. That was a leftover from some early iteration.

Final command that works: `docker run -d -p $PORT:8080 -v $(pwd)/config.yml:/www/config.yml -v $(pwd)/assets:/www/assets b4bz/homer:latest`
