### ISSUE TITLE
docker didnt start well and stuck at restarting.  

### ISSUE THREAD

**Issue by Timsto** [bastienwirtz/homer#470]
Latest version didnt start. version from 2 months ago work well.  same startup command. 

any idea? and what info should i provide for better troubleshooting?

**Comment by wy580477** [comment]
My homer container (latest version) won‘t listen to 80 port after several restarts.

Here is the test which I did inside the container.

~ $ wget 127.0.0.1:80
Connecting to 127.0.0.1:80 (127.0.0.1:80)
wget: can't connect to remote host (127.0.0.1): Connection refused
~ $ ps
PID   USER     TIME  COMMAND
    1 lighttpd  0:00 /bin/sh /entrypoint.sh
    6 lighttpd  0:00 lighttpd -D -f /lighttpd.conf
 1096 lighttpd  0:00 sh
 1104 lighttpd  0:00 ps

**Comment by papegaai** [comment]
I have the same issue. I tried deploying it via Portainer and it seems to start successfully but won't assign the network ports and I cant seem to connect to the terminal in any way. I keep getting an error that says the service is still restarting.

**Comment by bastienwirtz** [comment]
HI there, 

It's probably a permission issue. I've added a section in the troubleshooting documentation to cover this: https://github.com/bastienwirtz/homer/blob/main/docs/troubleshooting.md#my-docker-container-refuse-to-start--is-stuck-at-restarting. 

Can you check it out and see if it works for you ?

**Comment by Timsto** [comment]
yes it works! thanks a lot
