### ISSUE TITLE
Service text gets truncated when using ping type

### ISSUE THREAD

**Issue by Tooa** [bastienwirtz/homer#477]
Hi :wave:, 

on smaller screens and in the column view the service name gets truncated because of the custom service indicator message. 

The following tile shows the problem when using `columns: "4"` in config.yml:

![before](https://user-images.githubusercontent.com/5375334/175822423-72e48ac8-29be-404e-8b1a-a2b41ea4a100.png)

I suggest to place the custom service indicator messages in the upper right corner instead.

**Comment by mbentley** [comment]
I've noticed that this is something I've found to be a bit of an annoyance as I wouldn't expect that this would truncate text like for the subtitle:

![screenshot 2022-11-18 at 5 24 19 PM](https://user-images.githubusercontent.com/414445/202813254-79a226a3-f6ec-4eb4-b698-fa0aa76c515c.png)

It would be great if there was a way to adjust the location like the @Tooa's PR had done, especially considering many of the other custom services have very simple indicators like numbers in the upper right hand corner.  I'd personally be good with just a green or red ball to show status in the upper corner; I don't even really want text.
