### ISSUE TITLE
defaults: layout: columns not working

### ISSUE THREAD

**Issue by user9931** [bastienwirtz/homer#481]
If i'm understand correctly, those two options was added on same time
```
....
defaults:
  layout: columns # Either 'columns', or 'list'
  colorTheme: dark # One of 'auto', 'light', or 'dark'
...
```
For some mysterious reason, colorTheme works, but default layout (on browser's private window) are still "list". Button to swith between layouts is working...

**Comment by departet** [comment]
Can confirm this. Wanted to set the default layout and it didn't work for me either.

**Comment by bastienwirtz** [comment]
Hi there, 

Can you try in private nav or after a clear cache & storage ? 
If you used the layout button in the navbar before, you preferred layout is stored in your browser (local storage) and the default layout configured will not be applied. The `colorTheme` does have the "auto" setting to unset the preference, because it make sense as the browser have an "auto" mode.

**Comment by departet** [comment]
Ah dang now i feel stupid, tested another browser but didn't test a private window.
Private window works as expected.

**Comment by minghaoL1** [comment]
> If i'm understand correctly, those two options was added on same time
> 
> ```
> ....
> defaults:
>   layout: columns # Either 'columns', or 'list'
>   colorTheme: dark # One of 'auto', 'light', or 'dark'
> ...
> ```
> 
> For some mysterious reason, colorTheme works, but default layout (on browser's private window) are still "list". Button to swith between layouts is working...

I tested the default layout(the same as above) with several browsers ( Chrome, Edge, Firefox, Safari), unfortunately it still did not work even in private windows : (

**Comment by minghaoL1** [comment]
> > If i'm understand correctly, those two options was added on same time
> > ```
> > ....
> > defaults:
> >   layout: columns # Either 'columns', or 'list'
> >   colorTheme: dark # One of 'auto', 'light', or 'dark'
> > ...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > For some mysterious reason, colorTheme works, but default layout (on browser's private window) are still "list". Button to swith between layouts is working...
> 
> I tested the default layout(the same as above) with several browsers ( Chrome, Edge, Firefox, Safari), unfortunately it still did not work even in private windows : (

docker version: v23.02.2
