### ISSUE TITLE
Search field custom css

### ISSUE THREAD

**Issue by Tuetenk0pp** [bastienwirtz/homer#483]
I am creating a Dracula theme for Homer (see [this repo](https://github.com/Tuetenk0pp/homer) and [this issue](https://github.com/dracula/dracula-theme/issues/732)).

I can't find a way to modify the blue border around the active search field (see [this issue](https://github.com/Tuetenk0pp/homer/issues/1)). Any hints on how that would work?

![grafik](https://user-images.githubusercontent.com/55783419/177059588-02bf7eaa-f198-423a-b9ff-fc876123751a.png)

**Comment by bastienwirtz** [comment]
Hey @Tuetenk0pp, 

Very nice theme ! 
I think you need to change the `focus-visible` style, like: 

```css
input:focus-visible {
  outline: 4px dashed darkorange;
}
```

Best,

**Comment by Tuetenk0pp** [comment]
Thank you @bastienwirtz ! That did it.

**Comment by Tuetenk0pp** [comment]
@bastienwirtz thank you again for your support. The theme is now live on https://draculatheme.com/homer

If you have any thoughts or ideas, feel free to get in touch.
