### ISSUE TITLE
Service worker breaks reverse proxy

### ISSUE THREAD

**Issue by drrlvn** [bastienwirtz/homer#486]
After updating to v22.07.2 I noticed that links to reverse proxy paths no longer work but instead give an empty page with "Homer" as the title.
I didn't quite know how to identify the issue, but I noticed that unregistering the service worker solved the issue until it re-registered.
Reverting to an older version after unregistering solves the issue entirely.
Sorry this is light on details. I would be happy to provide more information that could help debugging.

**Comment by ben-pearce** [comment]
Yeah, same issue here.

I have services like Sonarr & Radar behind reverse proxy under path like `/sonarr` and visiting these after registering service worker yields 200 response from service worker  with blank page or Homer "You're offline friend" message.

Started happening after recent update.

**Comment by bastienwirtz** [comment]
Hi there, 

Sorry to here that. 
The latest update included a major upgrade and the service worker registration changed a lot. I'm gonna need some time to setup something similar and investigate the issue. 
Thanks for reporting this.

**Comment by bastienwirtz** [comment]
Hey there, 

Sorry for the early closing of your issue, GitHub has done it automatically following [my last push](https://github.com/bastienwirtz/homer/commit/9371c1537c421b76be1a641a2c66fc199e6a073a), which should fix the issue :) 
Let me know if that works for you (release not tagged yet, only available in `:latest`)

**Comment by pungorandras** [comment]
Its working, thanks!
