### ISSUE TITLE
Tautulli not working

### ISSUE THREAD

**Issue by GBT55** [bastienwirtz/homer#487]
Configured like this on my config.yml, but it does not work.

```
 - name: "Plex"
        logo: "assets/icons/plex.svg"
        #icon: "fab fa-film"
        #subtitle: "The one place to find and access all the media that matters to you"
        #tag: "app"
        url: "http://192.168.1.50:32400/web"
        target: "_blank" # optional html tag target attribute
        endpoint: "http://192.168.1.50:8181" # Tautulli
        type: "Tautulli"
        apikey: "myApiKey"
```

![image](https://user-images.githubusercontent.com/76950842/179405448-2613b0ce-5c54-45e4-8805-803c04c9136b.png)

**Comment by saschabrockel** [comment]
Your configuration looks strange @GBT55. As @bastienwirtz said I also guess you have the CORS problem that the most of us have. I can really recommend https://github.com/imjacobclark/cors-container or if you need it as a Docker container I'm working on it and already running it for myself https://hub.docker.com/repository/docker/saschabrockel/cors-container.

My config with cors-container on Docker:

```
      - name: "Tautulli"
        logo: "assets/tools/tautulli.png"
        subtitle: "Monitoring for Plex"
        tag: "plex"
        url: "http://192.168.178.29:3002/http://192.168.178.29:8181"
        type: "Tautulli"
        apikey: "<key>"
        target: "_blank"
```

**Comment by Ashkaan** [comment]
Since so many people have CORS issues, is there a way to make Homer's docker container more compatible with popular reverse proxies without adjustment?

I run over 40x apps in docker, all through a reverse proxy, and have never seen a CORS issues.
