### ISSUE TITLE
Option to specify internal port

### ISSUE THREAD

**Issue by grubeli** [bastienwirtz/homer#489]
If I understand correctly currently we can only map 8080 to any port on the host machine.
it would we useful we could also specify internal (8080) port, similar to what cloud-torrent does and have 8080 as default value:
https://github.com/jpillora/cloud-torrent/blob/master/README.md?plain=1#L71

**Comment by ChrHan** [comment]
Specifying internal port can be done by using `PORT` environment variable, example from docker command:

```
docker run -d \
  -p 8080:9091 \
  -v <full-path-to-local-assets>:/www/assets \
  --restart=always \
  --env PORT=9091 \
        --name homer \
  b4bz/homer:latest
```

This command would run `homer` with internal port of `9091`, exposing to `8080` of public network:
```
docker ps
CONTAINER ID   IMAGE                    COMMAND                  CREATED         STATUS                   PORTS                              NAMES
5725da3c9896   b4bz/homer:latest        "/bin/sh /entrypoint…"   2 minutes ago   Up 2 minutes (healthy)   8080/tcp, 0.0.0.0:8080->9091/tcp   homer
```

and `homer` would be accessible on port `8080`
