### ISSUE TITLE
Logos not appearing

### ISSUE THREAD

**Issue by rhpeZ** [bastienwirtz/homer#490]
I've been trying to set up a custom dashboard using Homer and have been having issues with adding logos to services on the dashboard. I have followed all the documentation and guidance on how to set it up correctly, have created a location in my home directory called homer/assets and binded that with the www/assets folder for Homer as instructed but when putting images into the tools folder and in the config.yml I've pointed them to the image png but it just is blank. It might also be worth mentioning that I did have issues with the container starting relating to permissions but following the help on the troubleshooting doc sorted that issue.

I am new to this so any help is appreciated, I have also linked some images below to show the various areas and how I have it configured.

https://gyazo.com/f8db79725da1d830c3d2fa302ef4a322
https://gyazo.com/21080d1cd650e3c05c1f5ba2d07d6a73
https://gyazo.com/0a38166202d94dea9ea6afc927ace837
https://gyazo.com/1542ffa74f7a783291ffdc05890620ee

**Comment by Japhys** [comment]
@rhpeZ You closed this one but didn't mention a solution. I am running into the same problem. All seems fine though. What caused this on your installation?

**Comment by rhpeZ** [comment]
@Japhys it was an issue with the icons, after having a look in the readme.md in the icons it says that they recommend converting the png or svg to a favicon package using a favicon generator. Then place them in the assets/tools folder. Below is a link to the instructions I followed. 

https://github.com/bastienwirtz/homer/blob/main/public/assets/icons/README.md

**Comment by Japhys** [comment]
Wonderful! I missed that one. Thanks for helping me

**Comment by Shokyuxx** [comment]
Hi! I am totally new to this. Is there a guide how to do this with the favicon generator? I have tried it but it ended with various icon options and I have just no idea...
