### ISSUE TITLE
Question about Custom Services

### ISSUE THREAD

**Issue by tucker19** [bastienwirtz/homer#492]
I have been looking at the wiki about Custom Services like Sonarr or Weather. Would those go in the Services Section of my config or like a message? Would it be possible to create a more scoped config file outlining different sections or how to utilize custom services?

**Comment by bastienwirtz** [comment]
Hi @tucker19, 

I will improve the documentation on that. In the meantime: Custom service goes in `items` list of the `service` section of the [config](https://github.com/bastienwirtz/homer/blob/main/docs/configuration.md) file, just like any classic item. they just have more options described [here](https://github.com/bastienwirtz/homer/blob/main/docs/customservices.md).

Hope it helps.

**Comment by tucker19** [comment]
Thank you. I am trying to do like PiHole and not having any luck.

**Comment by bastienwirtz** [comment]
Make sure to check the [troubleshooting guide](https://github.com/bastienwirtz/homer/blob/main/docs/troubleshooting.md) !
