### ISSUE TITLE
Sabnzbd Stats Support

### ISSUE THREAD

**Issue by fmunteanu** [bastienwirtz/homer#494]
Thank you for the great and simple product, do you plan adding support for Sabnzbd Stats?

**Comment by ochompsky** [comment]
No, if you wan't crap like that get Heimdall.  We don't need to add bloat to this.

**Comment by mbentley** [comment]
I just added a PR for SABnzbd support to show the number of slots occupied (number of downloads).

**Comment by mbentley** [comment]
I'd add more metrics but I figured that I could start with some the basics as just a simple download queue number was easy enough.  More data could be scraped, probably without too much trouble but I am not great as CSS formatting so that might be a bit harder for me.

**Comment by fmunteanu** [comment]
Nice job, thank you for the quick fix!

**Comment by mbentley** [comment]
I also just added another change to add an optional interval to update the value after looking at the qTorrent custom service.  I might be able to re-use some code from the qTorrent example to get the download speed from SABnzbd but I might not be able to get to that until next week.

**Comment by fmunteanu** [comment]
@bastienwirtz when do you plan to release the new version, including the merged changes?

**Comment by bastienwirtz** [comment]
You got it @fmunteanu :) https://github.com/bastienwirtz/homer/releases/tag/v22.11.2

**Comment by fmunteanu** [comment]
@mbentley thank you for the beautiful work. I installed the v22.11.2 and everything works as expected. Do you have any planned improvements?

**Comment by mbentley** [comment]
I had been messing around with a few things locally, such as getting the download speed but I was struggling with where exactly to put it.  The nice thing is that you get quite a bit of useful information from the same API call.  My question would be what information, outside of download speed, may be useful, if anything.

**Comment by mbentley** [comment]
Yeah, that would be the most likely location.  I hadn't taken the time to look at what anything else was doing outside of qBittorrent though.

**Comment by fmunteanu** [comment]
If you just copy the qBittorrent style, it would be easy to implement, I think. Anything else might be overkill, number of downloads and speed is perfect.

**Comment by 1337Reaper** [comment]
I was really hoping Homer would offer these types of "at a glance" details such as download speed, how much is in queue, etc, so it could be a viable alternative to Heimdall.

**Comment by mbentley** [comment]
I was playing with this a bit this morning and I am not sure about implementing it the same way as qBittorrent.  At least for me, I have text under each service.  I am not sure if @bastienwirtz would be OK with an implementation like this but it's fairly basic to be able to put the speed in another corner like this:

4 colums:
<img width="441" alt="screenshot 2023-06-24 at 10 29 12 AM" src="https://github.com/bastienwirtz/homer/assets/414445/72a15ff5-8b10-435f-a614-6c94c4b19deb">

3 columns:
<img width="321" alt="screenshot 2023-06-24 at 10 28 46 AM" src="https://github.com/bastienwirtz/homer/assets/414445/9b5afb74-7fd5-46d6-b33b-54e78948af04">

I was also thinking of adding a config option to disable the speed:
```
rateDisabled: true
```

Which then it would just look as it is today:
<img width="321" alt="screenshot 2023-06-24 at 10 33 15 AM" src="https://github.com/bastienwirtz/homer/assets/414445/fd00f41e-480c-42a8-a609-60b1c27e3a49">

**Comment by mbentley** [comment]
I created https://github.com/bastienwirtz/homer/pull/661 for at least getting feedback.
