### ISSUE TITLE
Feature request: dashy’s icon fetcher

### ISSUE THREAD

**Issue by mybuntu-git2** [bastienwirtz/homer#501]
Hi, I just moved to Homer from Dashy and want to suggest to use dashy’s icon finder code: basically dashy finds the icon of the item for the user, and/or searches it. having some clunky cli command that tires to fetch icons for config.yml items and/or via user input, could be a huge timesaver and improve ux without affecting performance (runs once if the modification date of config file is more recent than icons, and runs only for icons for which it finds no corresponding file).

by the way, very nice app and impressively lightweight!

**Comment by bastienwirtz** [comment]
Hi @mybuntu-git2 ! 
Thanks for the feedback :) 

Are you talking about the `icon: favicon` feature ? or the fetch from API like [allesedv.com](https://favicon.allesedv.com/) or [Icon.Horse](https://icon.horse/) ?

**Comment by mybuntu-git2** [comment]
Hi, It was the api fetch yes

**Comment by luixal** [comment]
Hi,

Didn't know these services, they are great! :)

Not sure, but I think this covers edge cases:

- No `logo` field --> show no icon. Stays the same.
- Custom urls in `logo` fields --> show linked icon. Stays the same.
- Values `allesedv.com`or `icon.horse` in the `logo` field --> parse `url` field to get the domain and build the favicon url with it.

what do you think?

**Comment by mybuntu-git2** [comment]
Hi,
Not a fan of urls in config, prefer files due to speed and lack of dependencies.
I worked some edge cases with Logo links.
Still, would be nice to cannibalize dashy code to have a standalone tool that fetches the icons required for first config.
