### ISSUE TITLE
Service UptimeKuma shows "All Systems Operational" when all sites are down

### ISSUE THREAD

**Issue by felihommen** [bastienwirtz/homer#503]
Service UptimeKuma shows
  - "All Systems Operational" when all sites are up. This id fine.
  - "Partially Degraded Service" when some sites are up and some are down. This is fine.
  - "All Systems Operational" when all sites are down. This last message should be "Degraded Service" or something like that

**Comment by bastienwirtz** [comment]
Hey @felihommen, 

Good catch! thanks for reporting it. It's [fixed](https://github.com/bastienwirtz/homer/commit/5418c6291a39d27aeee471673adba742080e1ccb) on `latest`, it should be better.
