### ISSUE TITLE
FEATURE REQUEST: Ability to run file or command on the machine running homer, from the dashboard

### ISSUE THREAD

**Issue by lauridshub** [bastienwirtz/homer#506]
Been looking around and could not find an easy solution for this. I would like to send Wake-on-LAN packets to a machine, but it would be nice to do from the dashboard. So either being able to run a bashscript or a command would be nice!

**Comment by virtadpt** [comment]
Maybe enable cgi-bin on your webserver, write a shell script that will run the necessary command (like etherwake or wakeonlan), and add the URL to the cgi-bin script as an entry on your dashboard?

**Comment by lauridshub** [comment]
There's maybe several workarounds, but it would still be nice to have a more streamlined option :) Thanks for the suggestion, will look into it

**Comment by bastienwirtz** [comment]
Hi @lauridshub :wave: 

Homer is strictly client side (static HTML) and will never be able to that by itself. If you find a server side service / API that could do that, we can create a custom component in Homer to interact with the service.

**Comment by luixal** [comment]
Something like this would do the trick, but I feel these things to be really unsecure...

https://github.com/msoap/shell2http
