### ISSUE TITLE
Webserver gets stuck on clock jump

### ISSUE THREAD

**Issue by dequeues** [bastienwirtz/homer#508]
docker-compose.yml
```yaml
version: "2"
services:
  homer:
    image: b4bz/homer:latest
    #To build from source, comment previous line and uncomment below
    #build: .
    container_name: homer
    volumes:
      - ./assets:/www/assets
    ports:
      - 8880:8880
    user: 1000:1000
    environment:
      - INIT_ASSETS=1 # default
```

Docker logs
```yaml
Starting webserver
4147-08-20 07:32:16: (server.c.1568) server started (lighttpd/1.4.64)
4147-08-20 07:32:16: (server.c.263) warning: clock jumped -68719476736 secs
```

**Comment by gstrauss** [comment]
Why do you think it is getting stuck?  If lighttpd is not restarting after such a large jump in time, check lighttpd.conf to verify your setting for `"server.clock-jump-restart"` in `server.feature-flags` (https://wiki.lighttpd.net/Server_feature-flagsDetails)

Also, why do you think the year 4147 is sane for today, which is in the year 2022 as I write this?

**Comment by dequeues** [comment]
I'm pretty sure that the server is borked. I've had issues with Docker too, so I'm going to try and reinstall the OS and we'll see. I'll close this for now.

**Comment by gstrauss** [comment]
Following what you posted from the lighttpd error log, did lighttpd report in the error log that lighttpd will attempt a graceful restart in < ~5 sec?  I am a lighttpd developer and if that is not working as expected, I would like to know so that I can fix it.  Thanks.

BTW, the current lighttpd release is lighttpd 1.4.66.

Also, I am still interested in why the image running under Docker is providing a time with the year 4147.  Is that intentional?

**Comment by dequeues** [comment]
> Following what you posted from the lighttpd error log, did lighttpd report in the error log that lighttpd will attempt a graceful restart in < ~5 sec? I am a lighttpd developer and if that is not working as expected, I would like to know so that I can fix it. Thanks.

Nope. That's all it ever showed and nothing more. 

> 
> BTW, the current lighttpd release is lighttpd 1.4.66.
> 
> Also, I am still interested in why the image running under Docker is providing a time with the year 4147. Is that intentional?

Yeah, I think the whole system was borked.
