### ISSUE TITLE
host ip included when adding link to the config

### ISSUE THREAD

**Issue by erlend0** [bastienwirtz/homer#513]
After adding the wanted ip address under URL in the config file the ip address for Homer is included. The example under will give the link "http://192.168.68.111:8902/192.168.68.111:1010" thus making the link useless 
    items:                                                                                                                              
      - name: "PiHole"                                                                                                                  
        logo: "assets/tools/pihole.png"                                                                                                 
        subtitle: "Bookmark example"                                                                                                    
        tag: "app"                                                                                                                      
        keywords: "PiHole"                                                                                                              
        url: "192.168.68.111:1010"

**Comment by fbartels** [comment]
Hi @erlend0,

you have to add the protocol to the beginning of your url. So instead of `192.168.68.111:1010` it needs to be `http://192.168.68.111:1010`.

**Comment by bastienwirtz** [comment]
I think this is resolved :) 
Feel free to reopen if anything.
