### ISSUE TITLE
Request: Proxmox Status

### ISSUE THREAD

**Issue by CreationGuy** [bastienwirtz/homer#516]
Hi- is it possible to have a custom service to check the status of Proxmox VMs? Maybe if they how many are on out of VMs, or CPU/Disk Space, etc?

**Comment by CreationGuy** [comment]
Great, I'll give it a try- thanks for sharing.

2 questions:
1) Does it matter where I place this script?
2) Assuming that a standard PVE user would be fine for the SSH in the script or what do you recommend?

**Comment by jordantrizz** [comment]
> Does it matter where I place this script?

No as long as you can execute the scripts.

> Assuming that a standard PVE user would be fine for the SSH in the script or what do you recommend?

any user that has ssh access should be able to run qm, this was for a homelab so root is what I used.

**Comment by CreationGuy** [comment]
Thanks again. I hate to ask this, looking at the script, do I replace PROXMOX_USER with the actual username?

**Comment by jordantrizz** [comment]
No worries at all, definitely need feedback on documentation. Yes, the PROXMOX_USER is the proxmox host ssh user you're going to use to run the qm command.

**Comment by CreationGuy** [comment]
Thank you for the updated directions. I'm some-what new to docker. 

I've placed 
pve-env.cfg & proxmox-report.sh in /docker/homer-scripts/
pm_status.html in /docker/homer/assets/tools

I tried to manually run the script:
`/docker/homer-scripts$ sudo sh proxmox-report.sh 
proxmox-report.sh: 2: Bad substitution
proxmox-report.sh: 7: [[: not found
Error: can't find config at /docker/homer-scripts/pve-env.cfg
`
Snippet from proxmox-report:
`SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
CONFIG="$SCRIPT_DIR/pve-env.cfg"`

**Comment by jordantrizz** [comment]
No worries, substitute sh with bash ;) or chmod u+x proxmox-report.sh and simply run sudo ./proxmox-report.sh

**Comment by CreationGuy** [comment]
Alright, I ran that and cam back with some basic info, what your script was supposed to query I'm assuming. My PVE password is pretty long. How does the cron job run with out the PW specified?

**Comment by jordantrizz** [comment]
It's a work in progress, and I just created it last week so it's all I have right now and just put it up on GitHub for you otherwise it wouldn't have seen the light of day.

Use an SSH key?

**Comment by CreationGuy** [comment]
I appreciate your effort on this- My Proxmox is down right now, I'm in the process of migrating it. I'll give it another shot at that point. I've subscribed and will keep in touch- Again- thank you for your help.

**Comment by CreationGuy** [comment]
Running the command works if I enter in the PW from shell. I don't know how to use a SSH key so I did this: 
config:
PROXMOX_PASSWORD="password"

.sh file:
eval "ssh ${PROXMOX_USER}@${PROXMOX_HOST}$@{PROXMOX_PASSWORD}"

but it doesn't work

**Comment by CreationGuy** [comment]
I modify the sh to 
	eval "ssh ${PROXMOX_USER}@${PROXMOX_HOST}@${PROXMOX_PASSWORD}"

cfg to
PROXMOX_PASSWORD="mypw"

running  sudo ./proxmox-report.sh
ssh: Could not resolve hostname mypw: Name or service not known
ssh: Could not resolve hostname mypw: Name or service not known
ssh: Could not resolve hostname mypw: Name or service not known
<div id="pm_status" style="color: white;"><pre>
Host: 
Uptime: 
ID     Name                      Status       Network

**Comment by fbartels** [comment]
@CreationGuy the way you have modified the command ssh is now using the value of `PROXMOX_PASSWORD` as the destination server, since it comes after the last `@`.

You cannot pass a password to ssh (it better to do key auth anyways). I had a quick look at the script and it offers the ability to pass the password with sshpass in https://github.com/jordantrizz/homer-scripts/blob/70360545f7f365221c0e0efa97accf7152b932e2/proxmox-report.sh#L20 instead.

But just to have it said. all the script seems to do is dump output into a text file (along with some html elements) so you could serve it from a webserver.

**Comment by jordantrizz** [comment]
So I just added sshpass support so you can use a password @CreationGuy if you look at the env.cfg.example file. You should really use an SSH key if you can.

@fbartels indeed, it's a text file, so you don't have to serve it from a web server on the Proxmox host.

**Comment by CreationGuy** [comment]
I got it going with the SSH Keys, it works nice and appreciate the effort. I'm not comfortable with the SSH keys so I reverted back. I'd like to have something more like the Portainer status where it shows just a # of running containers, paused, etc. I realize it's probably not possible since Proxmox doesn't have an API key gen.

**Comment by jordantrizz** [comment]
@CreationGuy all good, I hacked this together for my own use just to see what instances I had running. 

Proxmox does have an API and I've started working with that but it will be a while until I get it going. You can see some of it here https://github.com/jordantrizz/homer-scripts/blob/main/proxmox-report-api.sh

Still going to see what I can do with the API and homer.

**Comment by luixal** [comment]
Hi!

Just having a look at this and I think it can be done without using any scripts. The only thing is it would need to use local storage to save the auth api key, which doesn't sound good from a security pov.

**Comment by jordantrizz** [comment]
> I'll keep an eye on it, I think what you did is pretty neat- it's just too much for me now at my current learning stage. :)

It will get easier with the API, and prettier!

> The only thing is it would need to use local storage to save the auth api key, which doesn't sound good from a security pov.

Yea, the API ticket gets regenerated every 24 hours, so it would need to be stored somewhere temporarily.

**Comment by luixal** [comment]
Hi,

I just got it working using not the ticket, by the API token, which can be set to not expire. It can be placed in the yaml config for the Proxmox service.

Everything is working as expected, the only thing is that, due to the size of Homer cards, very little information can be shown. This is what I have so far:

![image](https://user-images.githubusercontent.com/615268/194705783-5d656dae-6ce8-4882-b35a-3c29db278a83.png)

This shows my home server, which has only 1 node and 2 qemu vms (2/2 means two vms running of a total of 2).

I'm just looking around the API to see if there's kind of an "overall status" endpoint or errors to show.

¿Which info do you think is best to show up?

**Comment by luixal** [comment]
I finally end up having something like this (showing vms running and disk, memory and cpu used):

![image](https://user-images.githubusercontent.com/615268/194709178-690a1271-a91a-4e24-9134-32f16692f99d.png)

Values for danger/warning colors and API token are configurable in the yaml file.

If it makes sense, I can PR this.

**Comment by CreationGuy** [comment]
I think that both look great! Is it possible to show 4 / 10 (on vs off) as well? Either way, these look great!

**Comment by luixal** [comment]
I sure. I made a PR with the last version, but I can add the 4/10 (on/off). This is for qemu vms, I haven't add LCX containers as I don't have any right now, but would be easy to add. Not so sure about space in the card, but maybe making what to show/hide configurable would be the way to go.

Anyway, I try to update the PR with the on/off vms.
