### ISSUE TITLE
Missing Favicon on Tab

### ISSUE THREAD

**Issue by defsix** [bastienwirtz/homer#517]
Running [docker.io/b4bz/homer:latest] (http://10.0.1.10:9000/#!/2/docker/images/docker.io~2Fb4bz~2Fhomer%3Alatest)

I am missing my favicon from the tab in my browser. This used to be present but am unable to repair or locate. Is it just me?
![Screenshot 2022-09-28 130435](https://user-images.githubusercontent.com/6899823/192774717-d4dc578b-a25b-4deb-9b10-dd00a251e670.jpg)

`
title: "Whisper Net"
subtitle: "Dashboard"
logo: "logo.png"
icon: "icon.png"

header: true
footer: false #'<p>Theme made with <span class="has-text-danger">❤️</span> by <a href="https://github.com/WalkxCode">Walkx</a></p>' # Set false if you want to hide it.

stylesheet:
  - "assets/custom.css"
  `

**Comment by defsix** [comment]
Hi, ok, I realised I was missing the favicon.ico from my /assets/icons/ folder I recreated the icon, and all is working now. No idea what happened to the original.

**Comment by grandmastermarco** [comment]
hi! i am having the same issue. I moved my dockerized homer to a new host. 
Everything migrated just fine except for the favicon. 
attached is the content of icons folder. any idea?
![favicon](https://user-images.githubusercontent.com/84290653/216287216-82cc49f6-c3fb-4e98-a4a7-8ed8e0830b8b.PNG)

**Comment by defsix** [comment]
I got it working by manually adding the icon file to the directory. I can't remember specifically because I tried a few things. Basically adding various versions of the icon file to both directories.
