### ISSUE TITLE
[Question] Add modals and tooltips

### ISSUE THREAD

**Issue by luixal** [bastienwirtz/homer#521]
Hi @bastienwirtz ,

How would you feel about using modals and or popovers in Homer?

Seeing that this project uses Bulma, [modals should be supported](https://bulma.io/documentation/components/modal/)  but [tooltips](https://wikiki.github.io/elements/tooltip/) are an extension to Bulma, not included by default.

I think they could be useful in some cases. Fro example, the proxmox custom service could have an icon/button on the indicator slot to show a modal with a list of the VMs/containers running on a Node.

Would you feel confortable with using these components in your project?

Thanks!

**Comment by tobidemski** [comment]
I would love to see such a feature because the tiles aren't that big and if you put to much information (for example the data from proxmox in the current state) it could be looking a bit squeezed. To fix this a model with dedicated Information listed in the modal would show it neat and we could put more stuff in it.

**Comment by luixal** [comment]
Yes, i tried the modal (using the bulma docs) to show a modal with the list and stats of the VMs. It rendered well, but when moving the mouse, it flickered. I think it was the overlay bulma puts behind the modal to make the rest of page darker while the modal is shown.

Maybe some CSS conflict, but i'm not that good at chasing frontend bugs.

I can reproduce it in a branch of my fork if you want to have a look :)

I think it could be useful for other services like uptime-kuma, docker, etc...

**Comment by bastienwirtz** [comment]
Hi there!

I agree the cards are small, but Homer is more a portal than a full featured dashboard. I thinks it's better to keep it simple and make possible to see the essential information very quickly. 
Sorry guys.
