### ISSUE TITLE
"Add to homescreen" on Android points to the wrong address

### ISSUE THREAD

**Issue by agilly1989** [bastienwirtz/homer#536]
After navigating to the correct address (in my case `https://home.gil.ly`) the page appears correctly in Chrome on my phone. I then "Add to Homescreen" and after it goes through the motions, I tap on the icon it made and it comes up with a phishing warning.

After some investigating, it seems to be making a shortcut to `https://home.gil.ly/assets/` even though I am on `https://home.gil.ly`

And if you are curious, I am running self-signed certs and I have installed them onto my phone so that is not the issue.

(note, this domain is a my network only domain via some fun dnsmasq stuff on my router)

**Comment by BonexP** [comment]
same to me.
i download release and host it using caddy.it works.
but when i install it.it doesnt work.

**Comment by fbartels** [comment]
I can reproduce this on a new system as well.

**Comment by bastienwirtz** [comment]
Hi there, thanks for reporting this, [the fix](https://github.com/bastienwirtz/homer/pull/548) has been merged, it should be better now :+1:

**Comment by agilly1989** [comment]
Upgraded to docker image [v22.11.1](https://hub.docker.com/layers/b4bz/homer/v22.11.1/images/sha256-4db1f87fe09890a430451994b7fb9def7f0b6e7c305c8dbe26640bc4f7ba6c95?context=explore) and it seems to install as an app instead of a web shortcut now (Chrome on Android and on PC) but is still pointing to ./assets/

![image](https://user-images.githubusercontent.com/50060406/201323491-1eabafcc-b21a-4a11-a37a-385e129c7e78.png)

**Comment by nikkopt** [comment]
I just tried this and am also getting a 403 forbidden error. Works fine in the browser.

**Comment by nikkopt** [comment]
Proof:
![1](https://github.com/bastienwirtz/homer/assets/2060960/82030c64-5410-44ce-bee6-8dc9fd2c5bf2)
![Screenshot_20230906-203614](https://github.com/bastienwirtz/homer/assets/2060960/9ff66671-4d9d-4e03-b08d-225d4e3fbfe2)

Using latest docker image as of this day.
