### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by confused-Techie** [bastienwirtz/homer#54]
Hey when trying to initially set up Homer my installation gets stuck on 
`darkhttpd/1.12, copyright (c) 2003-2016 Emil Mikulic`
I have tried a few times, removing the image and downloading again to no avail.
Since the default port of 8080 is in use on my machine I am using 
`sudo docker run -p 6200:6200 --name=homer -v /path/to/pre-created/config.yml:/www/config.yml -v /same/path/with-nested/assets/:/www/assets b4bz/homer:latest`
Using Portainer I attempted to check the logs but the logs only contain the same copyright message.
Any ideas?

**Comment by bastienwirtz** [comment]
Hi @confused-Techie, 
In order to use the port 6200 on your machine you have to map it to the 8080 in the docker, like this:
```
sudo docker run -p 6200:8080 --name=homer -v /path/to/pre-created/config.yml:/www/config.yml -v /same/path/with-nested/assets/:/www/assets b4bz/homer:latest
```

**Comment by confused-Techie** [comment]
Hey I appreciate the quick response! Unfortunately I am still seeming to have the same issue. Whats interesting is when I run this command and it gets stuck on the copyright message, once I quit the setup I get
`^Clistening on: http://0.0.0.0:8080/`
Maybe its having issues if another docker container is using the internal port 8080, or would this more likely be a file permissions issue of the config file?

For completeness the folder structure is
/home/server1/filerun/config.yml
/home/server1/filerun/assets/

And I am on Ubuntu 18.04.4 LTS.

**Comment by confused-Techie** [comment]
So while the issue here is fixed, in all honesty I'm not sure what did it. Later on starting the same container from Portainer web UI, it just worked, no errors at all. So while unsure of what changed from starting it from there, I;m assuming it must have been some issue with resources on the system like free memory or something along those lines. But appreciate the help!
