### ISSUE TITLE
PiHole custom service not working (NPM)

### ISSUE THREAD

**Issue by JordyEGNL** [bastienwirtz/homer#543]
Hi, Im trying to get the PiHole service to work but it is giving me some errors. I already fixed the CORS error in my NPM config.

This is what I get in the F12 network tab.
![image](https://user-images.githubusercontent.com/65036298/198234470-5d5ed776-30b0-498e-a489-aa54bb8f8430.png)

And this is my NPM config.
![image](https://user-images.githubusercontent.com/65036298/198234563-dcf2bb55-2be9-414c-8eab-eb8451b9eca4.png)

**Comment by bastienwirtz** [comment]
Hi there, 

Congrats on the CORS fixing :+1: It seems the custom service is not able to parse PiHole response. I think your screenshot shows the console tab, you can check the network tab to see the http response code of the request as well as the response content. 

I also would suggest testing the pihole api with `curl` on the `/api.php` endpoint to see if the API works.

**Comment by JordyEGNL** [comment]
Hi, thanks for your reply!

`https://pi-hole.<domain>/admin/api.php` would not give me any feedback but `http://<ip>/admin/api.php` would. So I made `pi-hole.<domain>` redirect to `<ip>/admin`

So I can access the api over `https://pi-hole.<domain>/api.php` now but it does not display anything in my homer yet.
This is a screenshot of my NPM config
![image](https://user-images.githubusercontent.com/65036298/199335093-b2c426e6-ff4d-438c-b9e0-43504ffc636e.png)

And this of the network tab, it shows CORS error but only in the response field.
![image](https://user-images.githubusercontent.com/65036298/199335227-24f85a3f-8b29-4f2f-9598-ea58c28ce57b.png)

And this 
![image](https://user-images.githubusercontent.com/65036298/199335503-db5a7ab1-f9b7-4b82-a533-4878acec4a34.png)

**Comment by JordyEGNL** [comment]
![image](https://user-images.githubusercontent.com/65036298/199337281-54ddfccf-e028-4e3e-9282-8c1d52f82db2.png)

**Comment by PedroC1999** [comment]
Did you manage to fix this?

**Comment by JordyEGNL** [comment]
> Did you manage to fix this?

Unfortunately not, the pihole api now requires and api key and I haven't got it working before that change.. I switches to to "ping" service instead of pihole.

**Comment by bastienwirtz** [comment]
Hello,

Indeed, CORS issue is expected when homer and the target services are on different domain. You will require either that:

- All services are exposed on the same domain as homer (mydomain.tld/pihole, mydomain.tld/proxmox), avoiding any cross domain request issues (CORS).
- All services accept cross site requests (= send the necessary CORS headers, either set directly in the service configuration if possible, or using a proxy to set the headers)

It's a well know issue, and as a fully front end app, Homer cannot do anything about it. 
Regarding piHole specific configuration, you can dig into the closed issue, there is many information.
