### ISSUE TITLE
403 Forbidden error when opening from Android homepage

### ISSUE THREAD

**Issue by sk7tp** [bastienwirtz/homer#544]
Hello, I'm getting a 403 Forbidden error when opening my Homer dashboard from a shortcut on the Android launcher in both Brave Browser and Google Chrome.  Both browsers can access the URL (http://192.168.0.20:8078/) with no issues when accessing the address from within the browser.  However, when I Add to Home Page the launcher shortcut doesn't work and a 403 Forbidden error is displayed.

I have another dashboard, Heimdall, which works with no issues as above and I haven't encountered this error with any other application on my home server.  I'm not sure why only the launcher shortcut doesn't work, can you help?

**Comment by loudcricketts** [comment]
I am having the same issue on the same platform. Accessing the portal is fine in every scenario other than the "Add to Home Page" shortcut on Android.

**Comment by fbartels** [comment]
Do you have some kind of authentication in front of your homer? I am running my Homer in an instance of "surfer", which adds auth. Whenever auth through surfer expires i am getting a login mask through it and need to log back in (which is for me the expected behavior).

**Comment by wipash** [comment]
I'm having the same issue. It works fine in both Chrome and Firefox on my android, but when 'installing' as a desktop app from either of those browsers I get a 403 error when trying to open Homer. No authentication between my phone and the Homer container.
