### ISSUE TITLE
Is it possible to order cards horizontally? 

### ISSUE THREAD

**Issue by ohitstom** [bastienwirtz/homer#547]
I would assume this could be done with css somehow, but i was unable to achieve this. I understand this is quite an unorthodox usage for homer but i thought it'd be cool to bundle my aboutme with it! 

![image](https://user-images.githubusercontent.com/22730962/199873520-061cd84f-e20f-4c94-a655-744e7745f893.png)
```
>>>>>
```
![image](https://user-images.githubusercontent.com/22730962/199873526-4967224a-e428-4275-939c-aefa8a274ffa.png)

**Comment by fbartels** [comment]
Hi @ohitstom,

the button left to the search bar does exactly this.

There is also a configuration option to select the default:

```
# Set the default layout and color scheme
defaults:
  layout: columns # Either 'columns', or 'list'
```

**Comment by ohitstom** [comment]
> Hi @ohitstom,
> 
> the button left to the search bar does exactly this.
> 
> There is also a configuration option to select the default:
> 
> ```
> # Set the default layout and color scheme
> defaults:
>   layout: columns # Either 'columns', or 'list'
> ```

That's perfect thank you very much ♥️
