### ISSUE TITLE
Response contained invalid HTTP headers

### ISSUE THREAD

**Issue by c0ball** [bastienwirtz/homer#553]
Hello,

I am running homer in a docker container with the default configuration.
While everything is working fine in Firefox, when I am trying to access my dashboard via Safari or Edge 
I receive an ERR_INVALID_HTTP_RESPONSE and the dashboard won't load.

Is there a solution on how to fix this error?

**Comment by c0ball** [comment]
I still receive this error, after updating to the newest version. 
Does anyone know, what to do?

**Comment by bastienwirtz** [comment]
Hello @c0ball, 

Sorry for the delay, are you running Homer on a raspberry pi ? You might be facing this issue: https://github.com/bastienwirtz/homer/issues/491#issuecomment-1298326118, the link in this comment will point you to the solution (reinstall `libseccomp`)

Let me know if that works for you!

**Comment by c0ball** [comment]
Thanks for your help. I guess that this was my problem because after updating I am able to access the dashboard on my other browsers.
