### ISSUE TITLE
Helm chart

### ISSUE THREAD

**Issue by djjudas21** [bastienwirtz/homer#562]
Hi there, thanks for this excellent app. Since k8s@home deprecated their Helm charts, I adopted a few of their charts including the one for Homer. I subscribe to updates from the homer repo and I update the chart 

If you like, you could include a section in your README about installing via Helm

* https://github.com/djjudas21/charts/tree/main/charts/homer
* https://djjudas21.github.io/charts/

Example:

```console
helm repo add djjudas21 https://djjudas21.github.io/charts/
helm repo update djjudas21

# install with all defaults
helm install homer djjudas21/homer

# install with customisations
wget https://raw.githubusercontent.com/djjudas21/charts/main/charts/homer/values.yaml
# edit values.yaml
helm install homer djjudas21/homer -f values.yaml
```

**Comment by bastienwirtz** [comment]
Awesome @djjudas21 ! Thanks for adopting the charts. 
I just updated the installation doc :+1: 

cc @replicadse !

**Comment by replicadse** [comment]
awesome!
