### ISSUE TITLE
Qbittorrent Service not showing stats (403 forbidden or 401 unauthorized)

### ISSUE THREAD

**Issue by kim3k** [bastienwirtz/homer#576]
Im running qBittorrent in Docker, and i receive 403 "forbidden" after i fix the  "Access-Control-Allow-Origin" error. i guess its because its missing authentication somehow. this is a screenshot from the web console displaying the error message.

![Uten navn](https://user-images.githubusercontent.com/57409441/208542808-ecdb71cc-f07d-4bf4-9a09-9b1a1c32082e.png)

or i can get " 401 unauthorized" if i enable CSRF.

![image](https://user-images.githubusercontent.com/57409441/208545133-b3056a3e-5cd1-4cb4-afa9-176998ff77a0.png)

**Comment by bastienwirtz** [comment]
Hello,

I don't use qBittorrent and don't know how it works but do you have any authentication option regarding the API on the qBittorent side? The current implementation in homer does not support authentication.   

Maybe @Shagon94 could help!

**Comment by Shagon94** [comment]
I used:

```
Bypass authentication for clients on localhost
Bypass authentication for clients in whitelisted IP subnets 
```

Under options > Web UI to get around authentication, as for CORS, I set that up through the same options menu (`Access-Control-Allow-Origin: *`).

**Comment by kim3k** [comment]
strange.. i have no clue.. i have done a tone of research without any luck, 
this is my setup in config.yml and qBittorrent: 

![strange](https://user-images.githubusercontent.com/57409441/208813237-0927a7ef-b444-4c11-b023-d28e7aea0e13.png)

**Comment by D3an1el** [comment]
Same, seems to be related to credentials

![qbittorrent2](https://user-images.githubusercontent.com/96570135/209091427-be1a88c9-9618-40c4-bf5f-dfccda4449ab.jpeg)
![qbittorrent1](https://user-images.githubusercontent.com/96570135/209091430-41928e7b-12a1-4262-9310-89aac6c295aa.jpeg)

**Comment by Zen3515** [comment]
I fixed it by adding CSRF to my reverse proxy. (I use traefik)
On path `/api/v2/transfer/info` and `/api/v2/torrents/info`.

Then disable `CSRF Protection` and `Host Header Validation` in the WebUI.
Now it works :)

If you doesn't use reverse proxy, I think you could try disable `CSRF Protection` and/or `Host Header Validation`

```yml
        - traefik.http.middlewares.cors-header.headers.accesscontrolallowmethods=GET,OPTIONS,PUT
        # add more domain like this https://home.example.com,https://example.org
        - traefik.http.middlewares.cors-header.headers.accesscontrolalloworiginlist=${TRAEFIK_CORS_HEADER_DOMAINS}
        # TOOD: I may need to check accessControlAllowHeaders if I uses with authelia
        - traefik.http.middlewares.cors-header.headers.accessControlAllowHeaders=X-Api-Key, Origin, Authorization
        - traefik.http.middlewares.cors-header.headers.accessControlAllowCredentials=true
        - traefik.http.middlewares.cors-header.headers.accesscontrolmaxage=100
        - traefik.http.middlewares.cors-header.headers.addvaryheader=true

        - traefik.http.routers.qbittorrent-homer-https.rule=Host(`${QBITTORRENT_DOMAIN?Variable not set}`) && PathPrefix(`/api/v2/`, `/{topic:transfer|torrents}/`,`/info`)
        - traefik.http.routers.qbittorrent-homer-https.entrypoints=https
        - traefik.http.routers.qbittorrent-homer-https.tls=true
        - traefik.http.routers.qbittorrent-homer-https.tls.certresolver=le
        - traefik.http.routers.qbittorrent-homer-https.middlewares=cors-header@docker
```

**Comment by kim3k** [comment]
i actually started using Traefik 2 days ago, so im really new to Traefik. Where are you putting those labels? inside docker-compose for qbittorrent? do u mind sharing your docker compose if that's the case? I haven't figured out how to access the webui yet through traefik (i can access every other services through traefik but not qbittorrent yet).. THANK YOU for the answer btw, i really appreciate it! 💯

**Comment by kim3k** [comment]
> 

i actually started using Traefik 2 days ago, so im really new to Traefik. Where are you putting those labels? inside docker-compose for qbittorrent? do u mind sharing your docker compose if that's the case? I haven't figured out how to access the webui yet through traefik (i can access every other services through traefik but not qbittorrent yet).. THANK YOU for the answer btw, i really appreciate it! 💯

**Comment by kim3k** [comment]
> I fixed it by adding CSRF to my reverse proxy. (I use traefik) On path `/api/v2/transfer/info` and `/api/v2/torrents/info`.
> 
> Then disable `CSRF Protection` and `Host Header Validation` in the WebUI. Now it works :)
> 
> If you doesn't use reverse proxy, I think you could try disable `CSRF Protection` and/or `Host Header Validation`
> 
> ```yaml
>         - traefik.http.middlewares.cors-header.headers.accesscontrolallowmethods=GET,OPTIONS,PUT
>         # add more domain like this https://home.example.com,https://example.org
>         - traefik.http.middlewares.cors-header.headers.accesscontrolalloworiginlist=${TRAEFIK_CORS_HEADER_DOMAINS}
>         # TOOD: I may need to check accessControlAllowHeaders if I uses with authelia
>         - traefik.http.middlewares.cors-header.headers.accessControlAllowHeaders=X-Api-Key, Origin, Authorization
>         - traefik.http.middlewares.cors-header.headers.accessControlAllowCredentials=true
>         - traefik.http.middlewares.cors-header.headers.accesscontrolmaxage=100
>         - traefik.http.middlewares.cors-header.headers.addvaryheader=true
> 
>         - traefik.http.routers.qbittorrent-homer-https.rule=Host(`${QBITTORRENT_DOMAIN?Variable not set}`) && PathPrefix(`/api/v2/`, `/{topic:transfer|torrents}/`,`/info`)
>         - traefik.http.routers.qbittorrent-homer-https.entrypoints=https
>         - traefik.http.routers.qbittorrent-homer-https.tls=true
>         - traefik.http.routers.qbittorrent-homer-https.tls.certresolver=le
>         - traefik.http.routers.qbittorrent-homer-https.middlewares=cors-header@docker
> ```

i actually started using Traefik 2 days ago, so im really new to Traefik. Where are you putting those labels? inside docker-compose for qbittorrent? do u mind sharing your docker compose if that's the case? I haven't figured out how to access the webui yet through traefik (i can access every other services through traefik but not qbittorrent yet).. THANK YOU for the answer btw, i really appreciate it! 💯

**Comment by chumbazoid** [comment]
> If you doesn't use reverse proxy, I think you could try disable `CSRF Protection` and/or `Host Header Validation`

Disabling Cross-Site Request Forgery protection did it for me. (Already had Host Header validation disabled per default settings.)

Thank you!!

**Comment by kim3k** [comment]
i got it working by routing Homer Dashboard and qBittorrent through config.yml (inside traefik folder). thank you all for the help :)

**Comment by paulo-erichsen** [comment]
related and reason why disabling CSRF is needed

https://github.com/qbittorrent/qBittorrent/issues/17598
