### ISSUE TITLE
Tab Bar Title

### ISSUE THREAD

**Issue by AlexanderEDavis** [bastienwirtz/homer#58]
Is there a way to remove or customise the Homer title in the tab bar?

![image](https://user-images.githubusercontent.com/9097891/82600238-84508500-9ba5-11ea-89a7-8c5f201b110e.png)

**Comment by fbartels** [comment]
There is a fork that implements a feature to configure this, not quite sure why the author of it did not (yet?) make a pr with it. I have pulled it into my local copy a few days ago and it seems to work without problems.

https://github.com/sylv-io/homer/commit/1ba17a9b2c2fef58a566e4850d40620f03e9f0e8

CC @sylv-io

**Comment by sylv-io** [comment]
oh sure i can do it :+1:

**Comment by bastienwirtz** [comment]
👋
Good idea! Thanks!
