### ISSUE TITLE
[Feature Request] Edit configuration yaml through front end?

### ISSUE THREAD

**Issue by TommySharpNZ** [bastienwirtz/homer#585]
I've installed Homer on a machine running DietPi which is super simple.
It would be fantastic to have a way to edit the configuration yaml through the main UI....

**Comment by t3dium** [comment]
There’s a fork? (“heavily inspired project”) called bender which does that

**Comment by TommySharpNZ** [comment]
Thanks, any chance of a URL to check it out?

**Comment by bastienwirtz** [comment]
Hi there !

Homer itself will always be a static html dashboard without any "intelligence". That way it's very low maintenance and fast. 
We could have another optional app on the side to do that, but I'm afraid there is no plan to add a configuration UI right now (no time / need on my side).

Best,
