### ISSUE TITLE
CORS-error

### ISSUE THREAD

**Issue by P-Tibor** [bastienwirtz/homer#587]
Okay so to begin with, I run openmediavault on rpi4, I installed docker and portainer through OMV, and I have homer deployed through portainer.

Now my problem is, I can't get any custom services to work. 
With Pi-Hole I don't get any error messages, status code says OK, but still no information on the web ui.
With qBittorrent I get status code 401, probably cors error?
With Portainer I get CORS error, 405 method not allowed.

I spent the whole day trying to fix it, but I just can't seem to find a solution.
Help would be greatly appreciated
Portainer web browser error:
`Request URL: http://192.168.0.200:9000/api/endpoints
Request Method: OPTIONS
Status Code: 405 Method Not Allowed
Remote Address: 192.168.0.200:9000
Referrer Policy: strict-origin-when-cross-origin
Content-Length: 0
Date: Sat, 14 Jan 2023 21:08:58 GMT
Accept: */*
Accept-Encoding: gzip, deflate
Accept-Language: en-GB,en-US;q=0.9,en;q=0.8,hu;q=0.7
Access-Control-Request-Headers: x-api-key
Access-Control-Request-Method: GET
Cache-Control: no-cache
Connection: keep-alive
Host: 192.168.0.200:9000
Origin: http://192.168.0.200
Pragma: no-cache
Referer: http://192.168.0.200/
Sec-Fetch-Mode: cors
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36`

qBittorrent web browser error:
`Request URL: http://192.168.0.200:8081/api/v2/transfer/info
Request Method: GET
Status Code: 401 
Referrer Policy: strict-origin-when-cross-origin
connection: keep-alive
content-length: 12
content-security-policy: default-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; script-src 'self' 'unsafe-inline'; object-src 'none'; form-action 'self'; frame-ancestors 'self';
content-type: text/plain; charset=UTF-8
date: Sat, 14 Jan 2023 21:08:58 GMT
referrer-policy: same-origin
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block
Accept: */*
Accept-Encoding: gzip, deflate
Accept-Language: en-GB,en-US;q=0.9,en;q=0.8,hu;q=0.7
Cache-Control: no-cache
Connection: keep-alive
DNT: 1
Host: 192.168.0.200:8081
Origin: http://192.168.0.200
Pragma: no-cache
Referer: http://192.168.0.200/
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36`

UPDATE: Pihole works if I remove the password for the web ui, anyway to get it work with password?

**Comment by P-Tibor** [comment]
So I checked the api responses in the browser:

qBittorrent:
`{"connection_status":"connected","dht_nodes":344,"dl_info_data":61357257092,"dl_info_speed":0,"dl_rate_limit":0,"up_info_data":4428343660,"up_info_speed":0,"up_rate_limit":0}`
and
`[{"added_on":1673639810,"amount_left":0,"auto_tmm":false,"availability":-1,"category":"","completed":12810969679,"completion_on":1673640521,"content_path":"/downloads/The.Banshees.of.Inisherin.2022.1080p.WEBRip.DD+5.1.x264.HuN-No1","dl_limit":0,"dlspeed":0,"download_path":"","downloaded":12825869918,"downloaded_session":12825869918,"eta":8640000,"f_l_piece_prio":false,"force_start":false,"hash":"face41a957e68bff36857cf33fc979c547053e72","infohash_v1":"face41a957e68bff36857cf33fc979c547053e72","infohash_v2":"","last_activity":1673720581,"magnet_uri":"magnet:?xt=urn:btih:face41a957e68bff36857cf33fc979c547053e72&dn=The.Banshees.of.Inisherin.2022.1080p.WEBRip.DD%2b5.1.x264.HuN-No1&tr=http%3a%2f%2ft.ncore.sh%3a2710%2f9a0e18126db106f7c1a47ae5fc2f89a5%2fannounce&tr=http%3a%2f%2ft.ncore.pro%3a2710%2f9a0e18126db106f7c1a47ae5fc2f89a5%2fannounce","max_ratio":-1,"max_seeding_time":-1,"name":"The.Banshees.of.Inisherin.2022.1080p.WEBRip.DD+5.1.x264.HuN-No1","num_complete":278,"num_incomplete":10,"num_leechs":0,"num_seeds":0,"priority":0,"progress":1,"ratio":0.0212192443662674,"ratio_limit":-2,"save_path":"/downloads","seeding_time":94171,"seeding_time_limit":-2,"seen_complete":1673734174,"seq_dl":false,"size":12810969679,"state":"stalledUP","super_seeding":false,"tags":"","time_active":94881,"total_size":12810969679,"tracker":"http://t.ncore.sh:2710/9a0e18126db106f7c1a47ae5fc2f89a5/announce","trackers_count":2,"up_limit":0,"uploaded":272155268,"uploaded_session":272155268,"upspeed":0},{"added_on":1673438269,"amount_left":0,"auto_tmm":false,"availability":-1,"category":"","completed":13374945548,"completion_on":1673438970,"content_path":"/downloads/The.Menu.2022.1080p.MA.WEBRip.DDP5.1.Atmos.H.264.HUN.ENG-PTHD","dl_limit":0,"dlspeed":0,"download_path":"","downloaded":13380915283,"downloaded_session":13380915283,"eta":8640000,"f_l_piece_prio":false,"force_start":false,"hash":"3cdc36af07bfb6f56d59c671452920b7e822a124","infohash_v1":"3cdc36af07bfb6f56d59c671452920b7e822a124","infohash_v2":"","last_activity":1673728929,"magnet_uri":"magnet:?xt=urn:btih:3cdc36af07bfb6f56d59c671452920b7e822a124&dn=The.Menu.2022.1080p.MA.WEBRip.DDP5.1.Atmos.H.264.HUN.ENG-PTHD&tr=http%3a%2f%2ft.ncore.sh%3a2710%2f9a0e18126db106f7c1a47ae5fc2f89a5%2fannounce&tr=http%3a%2f%2ft.ncore.pro%3a2710%2f9a0e18126db106f7c1a47ae5fc2f89a5%2fannounce","max_ratio":-1,"max_seeding_time":-1,"name":"The.Menu.2022.1080p.MA.WEBRip.DDP5.1.Atmos.H.264.HUN.ENG-PTHD","num_complete":2010,"num_incomplete":19,"num_leechs":0,"num_seeds":0,"priority":0,"progress":1,"ratio":0.2094264896483016,"ratio_limit":-2,"save_path":"/downloads","seeding_time":295722,"seeding_time_limit":-2,"seen_complete":1673734601,"seq_dl":false,"size":13374945548,"state":"stalledUP","super_seeding":false,"tags":"","time_active":296420,"total_size":13374945548,"tracker":"http://t.ncore.sh:2710/9a0e18126db106f7c1a47ae5fc2f89a5/announce","trackers_count":2,"up_limit":0,"uploaded":2802318116,"uploaded_session":2802318116,"upspeed":0},{"added_on":1673376780,"amount_left":0,"auto_tmm":false,"availability":-1,"category":"","completed":17863516194,"completion_on":1673377509,"content_path":"/downloads/Bullet.Train.2022.1080p.BluRay.DDP7.1.x264.HUN-PTHD","dl_limit":0,"dlspeed":0,"download_path":"","downloaded":17873627976,"downloaded_session":17873627976,"eta":8640000,"f_l_piece_prio":false,"force_start":false,"hash":"6c9f77bf34a142406b2c4f26e6c2e78ed055c11a","infohash_v1":"6c9f77bf34a142406b2c4f26e6c2e78ed055c11a","infohash_v2":"","last_activity":1673729730,"magnet_uri":"magnet:?xt=urn:btih:6c9f77bf34a142406b2c4f26e6c2e78ed055c11a&dn=Bullet.Train.2022.1080p.BluRay.DDP7.1.x264.HUN-PTHD&tr=http%3a%2f%2ft.ncore.sh%3a2710%2f9a0e18126db106f7c1a47ae5fc2f89a5%2fannounce&tr=http%3a%2f%2ft.ncore.pro%3a2710%2f9a0e18126db106f7c1a47ae5fc2f89a5%2fannounce","max_ratio":-1,"max_seeding_time":-1,"name":"Bullet.Train.2022.1080p.BluRay.DDP7.1.x264.HUN-PTHD","num_complete":2117,"num_incomplete":10,"num_leechs":0,"num_seeds":0,"priority":0,"progress":1,"ratio":0.07239570996652146,"ratio_limit":-2,"save_path":"/downloads","seeding_time":357183,"seeding_time_limit":-2,"seen_complete":1673734292,"seq_dl":false,"size":17863516194,"state":"stalledUP","super_seeding":false,"tags":"","time_active":357912,"total_size":17863516194,"tracker":"http://t.ncore.sh:2710/9a0e18126db106f7c1a47ae5fc2f89a5/announce","trackers_count":2,"up_limit":0,"uploaded":1293973987,"uploaded_session":1293973987,"upspeed":0},{"added_on":1673198056,"amount_left":0,"auto_tmm":false,"availability":-1,"category":"","completed":2164844600,"completion_on":1673198340,"content_path":"/downloads/Uncharted.2022.BDRip.x264.HuN-No1","dl_limit":0,"dlspeed":0,"download_path":"","downloaded":2167899410,"downloaded_session":0,"eta":8640000,"f_l_piece_prio":false,"force_start":false,"hash":"534b2f5d5c0d0c931a7866ac10faa016b2b34d65","infohash_v1":"534b2f5d5c0d0c931a7866ac10faa016b2b34d65","infohash_v2":"","last_activity":1673383274,"magnet_uri":"magnet:?xt=urn:btih:534b2f5d5c0d0c931a7866ac10faa016b2b34d65&dn=Uncharted.2022.BDRip.x264.HuN-No1&tr=http%3a%2f%2ft.ncore.sh%3a2710%2f9a0e18126db106f7c1a47ae5fc2f89a5%2fannounce&tr=http%3a%2f%2ft.ncore.pro%3a2710%2f9a0e18126db106f7c1a47ae5fc2f89a5%2fannounce","max_ratio":-1,"max_seeding_time":-1,"name":"Uncharted.2022.BDRip.x264.HuN-No1","num_complete":6059,"num_incomplete":257,"num_leechs":2,"num_seeds":0,"priority":0,"progress":1,"ratio":0.009001037552752505,"ratio_limit":-2,"save_path":"/downloads","seeding_time":536336,"seeding_time_limit":-2,"seen_complete":1673734427,"seq_dl":false,"size":2164844600,"state":"stalledUP","super_seeding":false,"tags":"","time_active":536620,"total_size":2164844600,"tracker":"http://t.ncore.sh:2710/9a0e18126db106f7c1a47ae5fc2f89a5/announce","trackers_count":2,"up_limit":0,"uploaded":19513344,"uploaded_session":19513344,"upspeed":0},{"added_on":1673444824,"amount_left":0,"auto_tmm":false,"availability":-1,"category":"","completed":17234648451,"completion_on":1673445531,"content_path":"/downloads/Wrath.of.Man.2021.1080p.BluRay.DD+5.1.x264.HuN-No1","dl_limit":0,"dlspeed":0,"download_path":"","downloaded":17245638621,"downloaded_session":17245638621,"eta":8640000,"f_l_piece_prio":false,"force_start":false,"hash":"ebcbe05aa5591c9a2a06b307a9f7a713ab8fe069","infohash_v1":"ebcbe05aa5591c9a2a06b307a9f7a713ab8fe069","infohash_v2":"","last_activity":1673445531,"magnet_uri":"magnet:?xt=urn:btih:ebcbe05aa5591c9a2a06b307a9f7a713ab8fe069&dn=Wrath.of.Man.2021.1080p.BluRay.DD%2b5.1.x264.HuN-No1&tr=http%3a%2f%2ft.ncore.sh%3a2710%2f9a0e18126db106f7c1a47ae5fc2f89a5%2fannounce&tr=http%3a%2f%2ft.ncore.pro%3a2710%2f9a0e18126db106f7c1a47ae5fc2f89a5%2fannounce","max_ratio":-1,"max_seeding_time":-1,"name":"Wrath.of.Man.2021.1080p.BluRay.DD+5.1.x264.HuN-No1","num_complete":682,"num_incomplete":23,"num_leechs":0,"num_seeds":0,"priority":0,"progress":1,"ratio":0,"ratio_limit":-2,"save_path":"/downloads","seeding_time":289161,"seeding_time_limit":-2,"seen_complete":1673731807,"seq_dl":false,"size":17234648451,"state":"stalledUP","super_seeding":false,"tags":"","time_active":289868,"total_size":17234648451,"tracker":"http://t.ncore.sh:2710/9a0e18126db106f7c1a47ae5fc2f89a5/announce","trackers_count":2,"up_limit":0,"uploaded":0,"uploaded_session":0,"upspeed":0},{"added_on":1673196484,"amount_left":0,"auto_tmm":false,"availability":-1,"category":"","completed":2218177419,"completion_on":1673196571,"content_path":"/downloads/Bullet.Train.2022.BDRip.x264.HuN-CRLS","dl_limit":0,"dlspeed":0,"download_path":"","downloaded":0,"downloaded_session":0,"eta":8640000,"f_l_piece_prio":false,"force_start":false,"hash":"eb1b9c808f1da3bc9ced1e4545698733ecc58a26","infohash_v1":"eb1b9c808f1da3bc9ced1e4545698733ecc58a26","infohash_v2":"","last_activity":1673543672,"magnet_uri":"magnet:?xt=urn:btih:eb1b9c808f1da3bc9ced1e4545698733ecc58a26&dn=Bullet.Train.2022.BDRip.x264.HuN-CRLS&tr=http%3a%2f%2ft.ncore.sh%3a2710%2f9a0e18126db106f7c1a47ae5fc2f89a5%2fannounce&tr=http%3a%2f%2ft.ncore.pro%3a2710%2f9a0e18126db106f7c1a47ae5fc2f89a5%2fannounce","max_ratio":-1,"max_seeding_time":-1,"name":"Bullet.Train.2022.BDRip.x264.HuN-CRLS","num_complete":9888,"num_incomplete":549,"num_leechs":1,"num_seeds":0,"priority":0,"progress":1,"ratio":0.007767024338281752,"ratio_limit":-2,"save_path":"/downloads","seeding_time":538191,"seeding_time_limit":-2,"seen_complete":1673734559,"seq_dl":false,"size":2218177419,"state":"stalledUP","super_seeding":false,"tags":"","time_active":538127,"total_size":2218177419,"tracker":"http://t.ncore.sh:2710/9a0e18126db106f7c1a47ae5fc2f89a5/announce","trackers_count":2,"up_limit":0,"uploaded":17228638,"uploaded_session":17228638,"upspeed":0},{"added_on":1673196463,"amount_left":0,"auto_tmm":false,"availability":-1,"category":"","completed":8301465281,"completion_on":1673196548,"content_path":"/downloads/Top.Gun.Maverick.2022.IMAX.1080p.AMZN.WEB-DL.DD+5.1.Atmos.H.264.HuN-No1","dl_limit":0,"dlspeed":0,"download_path":"","downloaded":0,"downloaded_session":0,"eta":8640000,"f_l_piece_prio":false,"force_start":false,"hash":"924cd87f8a957b70ef82d7460ae97930dd7e77a3","infohash_v1":"924cd87f8a957b70ef82d7460ae97930dd7e77a3","infohash_v2":"","last_activity":1673453974,"magnet_uri":"magnet:?xt=urn:btih:924cd87f8a957b70ef82d7460ae97930dd7e77a3&dn=Top.Gun.Maverick.2022.IMAX.1080p.AMZN.WEB-DL.DD%2b5.1.Atmos.H.264.HuN-No1&tr=http%3a%2f%2ft.ncore.sh%3a2710%2f9a0e18126db106f7c1a47ae5fc2f89a5%2fannounce&tr=http%3a%2f%2ft.ncore.pro%3a2710%2f9a0e18126db106f7c1a47ae5fc2f89a5%2fannounce","max_ratio":-1,"max_seeding_time":-1,"name":"Top.Gun.Maverick.2022.IMAX.1080p.AMZN.WEB-DL.DD+5.1.Atmos.H.264.HuN-No1","num_complete":4301,"num_incomplete":168,"num_leechs":1,"num_seeds":0,"priority":0,"progress":1,"ratio":0.008633561133362524,"ratio_limit":-2,"save_path":"/downloads","seeding_time":538185,"seeding_time_limit":-2,"seen_complete":1673734527,"seq_dl":false,"size":8301465281,"state":"stalledUP","super_seeding":false,"tags":"","time_active":538185,"total_size":8301465281,"tracker":"http://t.ncore.sh:2710/9a0e18126db106f7c1a47ae5fc2f89a5/announce","trackers_count":2,"up_limit":0,"uploaded":71671208,"uploaded_session":23154307,"upspeed":0}]`

Pihole:
`{"domains_being_blocked":166381,"dns_queries_today":2486,"ads_blocked_today":0,"ads_percentage_today":0,"unique_domains":3345,"queries_forwarded":1690,"queries_cached":792,"clients_ever_seen":8,"unique_clients":4,"dns_queries_all_types":2486,"reply_UNKNOWN":375,"reply_NODATA":636,"reply_NXDOMAIN":80,"reply_CNAME":786,"reply_IP":484,"reply_DOMAIN":47,"reply_RRNAME":78,"reply_SERVFAIL":0,"reply_REFUSED":0,"reply_NOTIMP":0,"reply_OTHER":0,"reply_DNSSEC":0,"reply_NONE":0,"reply_BLOB":0,"dns_queries_all_replies":2486,"privacy_level":0,"status":"enabled","gravity_last_updated":{"file_exists":true,"absolute":1673186649,"relative":{"days":6,"hours":8,"minutes":8}}}`

Portainer:
`{"message":"A valid authorisation token is missing","details":"Unauthorized"}`

This might help

**Comment by KuSi833** [comment]
I don't understand why does Homer have so many issues with CORS-errors, while Homarr PING statuses work out of the box without any need to add `add_header Access-Control-Allow-Origin *;`?

Some services work for me without the need to mess around in NPM (Bazarr and JellyFin), some finally managed to work by adding the header (NextCloud, JelySeerr), while others simply won't work (PhotoPrism, Radar...).

There's just far too much trouble. I don't understand how a fix for one doesn't for the other.


The way I managed to get Bazarr and JellyFin to work were the following steps done in the Nginx Proxy Manager:
For each proxy host configuration:

1. Custom Locations -> Add Location -> Press the icon
2. Add the following to the text field: `add_header Access-Control-Allow-Origin *;`
4. Fill in / as the location, and the same ip and port as on the details screen

**Comment by P-Tibor** [comment]
I gave up at this point.
This gentleman made an API for homer and it works perfectly. Its basically 30 rows of code and works without a problem:
https://www.reddit.com/r/selfhosted/comments/ng2ktw/homer_dashboard_stats_widget/

I don't understand either why homer has so many problems with this, when someone can solve it so easily.

**Comment by bastienwirtz** [comment]
Hi there. 
There is a simple reason for this: Homer is a purely static, **HTML only** (no server side language of any sort) app and it always will be. Therefore Homer cannot workaround CORS restrictions by itself. 

Homer is designed that way to be as low maintenance as possible, as light as possible, as simple as possible. There are plenty of great alternative using a server component (python, nodejs, php, ... anything) to avoid having to deal with CORS. 

You either have to: 
- Setup the headers correctly. 
- Use a CORS proxy. 

As described in the [documentation](https://github.com/bastienwirtz/homer/blob/main/docs/troubleshooting.md#my-custom-service-card-doesnt-work-nothing-appears-or-offline-status-is-displayed-pi-hole-sonarr-ping-).
