### ISSUE TITLE
Possible security risk: config.yml is downloadable right from within the browser

### ISSUE THREAD

**Issue by vxrtns** [bastienwirtz/homer#589]
**Describe the bug**
If you go to http://your-domain/assets/config.yml, the file is downloaded. I think this shouldn't be possible.

**Expected behavior**
If you go to the mentioned location, the access to config.yml should be forbidden instead of downloading it.

**Comment by bastienwirtz** [comment]
Hi @vxrtns, 

the `config.yml` is an essential file for homer to build the dashboard, if this file is not accessible, the dashboard will be empty.
As mentioned in the [documentation](https://github.com/bastienwirtz/homer/blob/main/docs/customservices.md) :

> Note that config.yml is exposed at /assets/config.yml via HTTP and any apikey included in the configuration file is exposed to anyone who can access the homer instance. Only include an apikey if your homer instance is secured behind some form of authentication or access restriction.

There is plenty of authentication solution out there to address this. Alternatively you could proxify the request which would handle (and hide) authentication information. 

Any of this is required, many people just don't put any sensitive information in there.
I'm closing the issue but feel free to ask if you have any question.
