### ISSUE TITLE
Raspberry Pi Docker standard_init_linux.go:211: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by ferdinandmudjialim** [bastienwirtz/homer#59]
Running on Raspberry Pi Model 3B+ V1.3 with: 
`docker run --name=homer -d --restart=unless-stopped -p 8080:8080 -v /home/pi/homer/config.yml:/www/config.yml -v /home/pi/homer/assets:/www/assets b4bz/homer:latest-arm64v8`

produces the error: 
`standard_init_linux.go:211: exec user process caused "exec format error"`
in docker logs.

I suspect this may have something to do with the architecture, but I thought that the Raspberry Pi was supported through the ARM64v8 Docker image. Any thoughts on why this is happening?

**Comment by bastienwirtz** [comment]
Hi @ferdinandmudjialim !

Thanks for opening the issue. ARM support has been added recently, but something might be wrong, I'll look into it asap!

**Comment by GlennToms** [comment]
@ferdinandmudjialim What OS are you running on Raspberry Pi?
Can you run `dpkg --print-architecture`
Did you try the 32 Image? [Dockerfile.arm32v7](https://github.com/bastienwirtz/homer/blob/master/Dockerfile.arm32v7)

Let me know how you get on

**Comment by ferdinandmudjialim** [comment]
@GlennToms 
Running `dpkg --print-architecture` yields `armhf`

From neofetch: 
OS: Raspbian GNU/Linux 9.11 (stretch) armv7l
Model: Raspberry Pi 3 Model B Plus Rev 1.3
Kernel: 4.19.66-v7+ 
CPU: ARMv7 rev 4 (v7l) (4) @ 1.4GHz

I've not tried the 32 image. I will sometime today.

**Comment by GlennToms** [comment]
AHH.  Now I see..  You're running the 32bit image.  I'm sure you'll get it working with the 32 bit version.

Have fun

**Comment by ferdinandmudjialim** [comment]
Wow, that was embarrassing. You are totally right. The 32 bit version worked. For some reason I was thinking I was running on a 64-bit architecture. Note to self: armhf / armv7 means 32-bit! Thanks, I'll close this now.
