### ISSUE TITLE
[Feature request] Loading of status message from endpoint

### ISSUE THREAD

**Issue by hypervtechnics** [bastienwirtz/homer#6]
For me it would be useful to have the status message and its properties loaded from an api to be more dynamic. So as an alternate you could provide an URL to the endpoint and every client will make the call to the api to get the message and its state (success and so on) then.

**Comment by bastienwirtz** [comment]
Hi @hypervtechnics!

Thanks for reaching out, sounds like a good idea. I can add an optional `url` property in the `config.yml` under the `message` key and automatically perform a GET request if filled. The API could respond a json like: 

```json
 {
  "style": "is-warning"
  "title": "Lorem ipsum"
  "content": "Lorem ipsum dolor sit amet, ....."
}
```

Would that be ok?

**Comment by hypervtechnics** [comment]
Yeah that would be cool! Thank you for this wonderful piece of software! 😄 

An additional ideas for maybe some other users out there: Maybe use the additional fields `style`, `title`, `content` as overwrites for the api response? So if the API does or does not provide the given values you can use them as replacement ^^ Just as an idea.

**Comment by bastienwirtz** [comment]
Here you go @hypervtechnics : https://github.com/bastienwirtz/homer/pull/7
It would be awesome if you could test the branch and give me some feedbacks before I merge it to master! Feel free to ask if you have any question.

**Comment by hypervtechnics** [comment]
I will take a look in the next days as I first have to adapt my service providing the values :D

**Comment by bastienwirtz** [comment]
You're welcome!
Anytime for the testing, no rush. I'm merging the PR now but I will update it based on your feedback if necessary :)

**Comment by hypervtechnics** [comment]
Hi, finally got to test this! It's working! Thank you! 😄 

One thing I noticed during upgrading: Maybe reuse the title from the config in the HTML as title of the whole page (in the browser tab). Also it may be useful to make the colours configurable to really only need to make changes to the config.yml. Makes updates more easy :)

**Comment by bastienwirtz** [comment]
Thanks for the feedback! Easy colors & title are in my todo list!
