### ISSUE TITLE
configuration not read if named `*.yaml` instead of `*.yml`

### ISSUE THREAD

**Issue by AdamJel** [bastienwirtz/homer#602]
**Describe the bug**
Configuration is not loaded if the config name is `.yaml` instead of `.yml`.

* `assets/config.yaml`

**Expected behavior**
Both variants should work.

**Comment by bastienwirtz** [comment]
Hi @AdamJel ! 

I understand your point but unfortunately as a client side only app that would mean to perform multiple requests to check which configuration file is available, and I prefer not to perform unnecessary requests. 
The configuration file name is well documented and I believe there no limitation related to that.

Unless there is a strong limitation or value to add by supporting the variant, Homer will keep his current configuration file name.
