### ISSUE TITLE
Linebreak in message

### ISSUE THREAD

**Issue by TopicsLP** [bastienwirtz/homer#61]
Hey,

just wanted to ask is there a way to make linebreaks in the "message" box to get some order.
I wanted to Provide a small text like:

> "Hey Welcome on the Landingpage.
> 
> Planed Maintenance:
> -- Server Number 1"

![QoKEFQ4 1](https://user-images.githubusercontent.com/9019121/82682075-f5984280-9c4e-11ea-9c2e-252c7111010b.png)

**Comment by bastienwirtz** [comment]
Hi @TopicsLP!

Thanks for this good suggestion! I integrated full html support in this pull request https://github.com/bastienwirtz/homer/pull/62 (among a lot of other stuff that needs some testing to make sure everything is ok).

I'll keep you updated!

**Comment by bastienwirtz** [comment]
@TopicsLP I just merged it, you should be able to do it! 
If you installed homer manually, there is a new installation step (build) to take care of, otherwise (with docker) it's seemless.
