### ISSUE TITLE
Move to/Support another Docker registry other than Docker Hub

### ISSUE THREAD

**Issue by jacroe** [bastienwirtz/homer#618]
**Is your feature request related to a problem? Please describe.**
Based on the issues described in [this blog post](https://blog.alexellis.io/docker-is-deleting-open-source-images/), Docker Hub is, perhaps, no longer a safe provider of Docker images. Unless the project is willing to pay.

**Describe the solution you'd like**
Support a different Docker registry, in combination or not, with [GHCR.io](https://ghcr.io/) or [Quay](https://quay.io/).

**Describe alternatives you've considered**
N/A

**Additional context**
Quite a bit of additional context can be seen in [Hacker News](https://news.ycombinator.com/item?id=35166317) and this [/r/selfhosted post](https://www.reddit.com/r/selfhosted/comments/11ryub1/fyi_docker_is_deleting_open_source_organisations/).

**Comment by bastienwirtz** [comment]
Hello @jacroe, 

Thanks for your concern. Homer is not at risk as it's not relying on the organization feature. I know this move from Docker is a hotly debated topic in the open source community, but I don't want to break users conf and homer upgrade without having the need to. I prefer to leave it on docker hub for now.

**Comment by bastienwirtz** [comment]
All right, you convinced me @gabe565 !
