### ISSUE TITLE
Bug Report: Auto reload after installation via tarball

### ISSUE THREAD

**Issue by Ceecker51** [bastienwirtz/homer#620]
**Describe the bug**

Automatic reload of homer in the browser after startup using the 'npx serve' command.

**Environemnt**

- OS: Windows 10 Home 22H2 (64 Bit)
- Node: 18.15.0
- npm: 9.6.2
- serve: 14.2.0
- Google Chrome: 111.0.5563.65 (Offizieller Build) (64-Bit)
- Homer: v23.02.2

**Reproduction**

Execute the steps under the chapter `Using the release tarball (prebuilt, ready to use)` in the README file.

**Expected behavior**

No reloading in the browser

**Screenshots**

https://user-images.githubusercontent.com/40306809/226197259-78cb7fa7-ef5f-4186-8d74-e9ff34caf22f.mp4

**Comment by toxicfirefly** [comment]
I ran onto this issue with Debian 11, npm `9.6.7`, nodejs `18.7.0`. If I use python3 to host I don't have this problem.

The command I ran was `python3 -m http.server 8010` instead of `npx serve`
