### ISSUE TITLE
SpeedtestTracker Docs unclear

### ISSUE THREAD

**Issue by jscmidt** [bastienwirtz/homer#627]
**Describe the bug**
The docs about the speedtest tracker service don’t make clear that the service is meant to work together with the [speedtest project](https://github.com/alexjustesen/speedtest-tracker). I thought it’s a build-in speedtest…

**Expected behavior**
Just one sentence or maybe a link to the speedtest project to prevent misunderstanding.

**Comment by bergpb** [comment]
I was able to get this service up and running here.
A PR was opened to improve the documentation on how to use the SpeedtestTracker custom service.
