### ISSUE TITLE
Dockerfile simplification

### ISSUE THREAD

**Issue by 87594589-7087-4f7c-b204-e84312ae374c** [bastienwirtz/homer#63]
The Dockerfile can be make way more simple using something like this:

## Dockerfile

```
FROM busybox

COPY ./ /www/

EXPOSE 8080/tcp

ENTRYPOINT [ "httpd", "-f", "-v", "-u", "1000", "-h", "/www", "-p", "8080" ]
```

## Docker run

```
docker run -d -p 80:8080 --cap-drop=ALL --cap-add=SETGID --cap-add=SETUID homer
```

This removes the need for:

- Many unneeded CAPs
- Alpine
- darkhttpd

## Stats
Memory: 500Kib
Image Size: 4.55MB

I have not created a PR for this, as I need to do more end-to-end testing for different ARCHs and complex homer configs.

**Comment by 87594589-7087-4f7c-b204-e84312ae374c** [comment]
One other options, to remove the need to create a Dockerfile is to do something like this:

```
docker run \
    --detach \
    --volume /Users/swind/Playground/homer:/www \
    --workdir /www \
    --publish 80:8080 \
    --name homer \
    --cap-drop ALL \
    caddy:2 \
    caddy file-server --listen :8080
```

I like this option overall, as it is very clean, but it does leave the user having to git clone the repo to use it vs having it packages in a docker image.

## Stats

Memory: ~11MB
Image Size: 40.4MB

**Comment by bastienwirtz** [comment]
Hi there!

Alpine is the docker recommendation and it's already really slim. Unless there is a particular issue with it, I prefer to stick with it!

**Comment by bastienwirtz** [comment]
@87594589-7087-4f7c-b204-e84312ae374c that's not really an option anymore, I just added a build system that require a build stage, so the docker file is a bit more complex today.
