### ISSUE TITLE
Add Wanted count to Arrs

### ISSUE THREAD

**Issue by SenorSmartyPants** [bastienwirtz/homer#638]
**Is your feature request related to a problem? Please describe.**
Display a count of wanted items from Sonarr/Radarr/Lidarr etc. 

Sonarr: /api/v3/wanted/missing
Lidarr: /api/v1/wanted/missing
Radarr is a bit different, see https://github.com/linuxserver/Heimdall-Apps/pull/592 for details

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by royto** [comment]
Merge Request created: https://github.com/bastienwirtz/homer/pull/680
