### ISSUE TITLE
You're offline friend on firefox mobile

### ISSUE THREAD

**Issue by johannes-z** [bastienwirtz/homer#641]
**Describe the bug**
This only happens on Firefox Mobile on Android. When opening homer in Firefox, the page just says 'You're offline friend'. All other browsers (kiwi, chrome, ...) open the page correctly. Neither IP nor domain work for Firefox mobile.

On desktop all browsers work, including Firefox.

**Expected behavior**
Firefox Mobile should also work.

**Logs & errors**
I cannot access the browser console on mobile.

Homer is hosted in an LXC on Proxmox. I access it using Caddy reverse proxy and a self signed certificate for my internal domain `media.lan`. The cert and CA are created using `mkcert`, that's why the HTTPS connection is secured (no validation error).

**Screenshots**
![Screenshot_20230509_120944_Firefox](https://github.com/bastienwirtz/homer/assets/9069888/c0fe6b60-b4a1-462d-aee9-e50fa9f98025)

**Configuration**
-

**Comment by bastienwirtz** [comment]
Hello, 

That's weird :thinking: 
Do your have any extension activated ? can you try in a private navigation tab ?

**Comment by johannes-z** [comment]
I was using an internal domain `*.lan` and that seems to cause problems on android.
