### ISSUE TITLE
OpenWeatherMap displays error

### ISSUE THREAD

**Issue by whydakk** [bastienwirtz/homer#644]
**Describe the bug**
When the OWM is added in services then the "Data could not be retrieved" error is displayed and when hoverring the mouse over the error the link is invalid: https://openweathermap.org/city/null
Config is set the same as written in https://github.com/bastienwirtz/homer/blob/main/docs/customservices.md#openweathermap
Other items in services are working correctly.

**Expected behavior**
The weather should be displayed

**Logs & errors**
"Data could not be retrieved" error is displayed.
Link target is https://openweathermap.org/city/null

**Screenshots**
![obraz](https://github.com/bastienwirtz/homer/assets/12054513/77a4d4cc-760b-4a39-a359-5859ab2c2a34)

**Configuration**
The same as in https://github.com/bastienwirtz/homer/blob/main/docs/customservices.md#openweathermap

**Comment by whydakk** [comment]
Dunno why but today it's working correctly.

**Comment by nasmi3** [comment]
I had the same issue and I think that it comes from the open weather side. 
The API token does not work straight away. If the account has just been created, after a few minutes/hours the API key will become active and it should start working properly.
