### ISSUE TITLE
latest image tag different from release tag?

### ISSUE THREAD

**Issue by javydekoning** [bastienwirtz/homer#647]
**Describe the solution you'd like**t

**Describe alternatives you've considered**
Why do `:latest` and `:v23.05.1` have different digests?

https://github.com/users/bastienwirtz/packages/container/homer/92995954?tag=v23.05.1

**Additional context**
I would expect the `latest` tag to map to the latest release (v23.05.1), but the container digests are different.

**Comment by bastienwirtz** [comment]
Hello!

Latest can include some unreleased changes. It's build each time something is pushed on the main branch. I usually wait a few days or weeks   in case any issues comes up before creating a release.

**Comment by javydekoning** [comment]
Thanks, then I'll pin to the versioned tag. 

IMHO `development` or `main` might be a more suitable and is more commonly used. 

Typically, `:latest` is a mutable stable tag which points to the latest "stable" version.

Like this:

![animation](https://stevelaskerblog.files.wordpress.com/2018/03/stabletaggingwithupdates.gif)

**Comment by mrclschstr** [comment]
I would very much appreciate it if the use of the `latest` tag is adapted. I also intuitively assumed that this would point to the latest stable release. This probably caused me to fall for a problem with the rebuilding of the theming, see: https://github.com/bastienwirtz/homer/issues/565#issuecomment-2265217952

**Comment by bastienwirtz** [comment]
Hi there, this has been fixed, thanks for pointing that out :pray:
