### ISSUE TITLE
Feature request: Option to disable ipv6

### ISSUE THREAD

**Issue by broizter** [bastienwirtz/homer#648]
Contiunation of https://github.com/bastienwirtz/homer/issues/466#issuecomment-1549170476

Currently the homer docker container won't start unless the host system has ipv6 enabled.
```
homer  | 2023-05-18 14:21:17: (network.c.387) socket: Address family not supported by protocol
```

**Comment by hwwilliams** [comment]
Saw this recently when I disabled ipv6 on a VM since I don't use it, took me a moment to realize it was an issue with the image and not some kind of issue with docker.

**Comment by rrrluk** [comment]
This please, I have some k8s workers where ipv6 is not configured correctly and cant run homer on these.

**Comment by iambricegg** [comment]
A workaround is to disable IPv6 listening in the lighttpd config file and mount it in the homer container : 
```
# /lighttpd.conf

include "/etc/lighttpd/mime-types.conf"

server.port            = env.PORT
# $SERVER["socket"] == "[::]:" + env.PORT {  }  <--- comment the line
server.modules         = ( "mod_alias" )
server.username        = "lighttpd"
server.groupname       = "lighttpd"
server.document-root   = "/www"
alias.url              = ( env.SUBFOLDER => "/www" )
server.indexfiles      = ("index.html")
server.follow-symlink  = "enable"
server.feature-flags  += ( "server.clock-jump-restart" => 0 )
```

It's the same thing as using the `lighttpd.conf` of the v23.02.2

**Comment by gstrauss** [comment]
FYI: lighttpd 1.4.72 will issue a warning if IPv6 is not available and will continue without listening on that socket.
