### ISSUE TITLE
Homer Config File

### ISSUE THREAD

**Issue by raadms** [bastienwirtz/homer#656]
**Describe the bug**
I use Pi 4 with PI OS Lite 64-Bit. I installed Homer via Portenier template used from this url (  https://raw.githubusercontent.com/Qballjos/portainer_templates/master/Template/template.json)

**Expected behavior**
when I browse to Homer it says (No configured service found!

Check out the documentation to start building your Homer dashboard.) 

I tried to edit the Config.yml file but no reflection when I made changes to the file.  seeking support on resolving my issue, 

**Screenshots**

![HomerPage](https://github.com/bastienwirtz/homer/assets/124711113/7c6ccb58-3145-47d5-9c25-a999fc544b27)
![LS](https://github.com/bastienwirtz/homer/assets/124711113/66ab7870-5347-4592-94e4-98b8712d3114)
![Config](https://github.com/bastienwirtz/homer/assets/124711113/33c0be5b-ffe7-4431-9e26-a1dffcd465ea)

Thank  you,

**Comment by rod7760** [comment]
Why was this closed? I am having a similar issue
