### ISSUE TITLE
Docker: problems with permissions of assets folder

### ISSUE THREAD

**Issue by klejejs** [bastienwirtz/homer#66]
When I copy files from github to my assets folder and launch homer through Docker, I get error "assets/manifest.json 403 (Forbidden)". Any suggestions?

**Comment by klejejs** [comment]
Also I don't know why, but Chrome doesn't find a service worker when I use Docker :(

**Comment by bastienwirtz** [comment]
Hi @klejejs! 
Thanks for reporting this, I just pushed a big update that refactored all the project, that's probably a side effect, I'll look into it asap.

**Comment by klejejs** [comment]
Thank you very much! Keep up the awesome work.

**Comment by bastienwirtz** [comment]
Hi @klejejs!
I tried to reproduce, without luck so far, could you provide more information? 
Thanks!

**Comment by bastienwirtz** [comment]
That should be all good now, feel free to reopen the issue is anything wrong!
