### ISSUE TITLE
How do I remove the "Created with love" text?

### ISSUE THREAD

**Issue by scotrod** [bastienwirtz/homer#669]
Pardon me, but I searched and removed that text ANYWHERE I could find it. Could you please tell me how do I remove this text from the application?

Thank you.

![image](https://github.com/bastienwirtz/homer/assets/45900128/340a0dcb-23c1-404d-af05-8a8cb09e2f5c)

**Comment by royto** [comment]
This is configurable using the `footer` key in the config.yml file

Use 
```yaml
footer: false
```

**Comment by bastienwirtz** [comment]
Hi there, 

Indeed, as pointed out by @royto, the `footer` configuration key is here for that. 
I'm closing the issue, feel free to reopen if anything.
