### ISSUE TITLE
Errors are not shown to the user

### ISSUE THREAD

**Issue by DusterTheFirst** [bastienwirtz/homer#67]
After changing the site's config.yml, the page goes blank. There are no errors in the docker logs, but

    Service worker event waitUntil() was passed a promise that rejected with 'Error: bad-precaching-response :: [{"url":"https://homer.dusterthefirst.com/assets/tools/sample.png?__WB_REVISION__=2310e486d38639bd762c521ecfff5673","status":404}]'.

shows up in the web console.

**Comment by DusterTheFirst** [comment]
I found the cause, my yaml was malformatted. I am not going to close this issue since errors should be handled more gracefully, such as showing a page that the yml config is invalid or missing

**Comment by bastienwirtz** [comment]
Hi @DusterTheFirst!

Thanks for openning the issue, I finally added error handling on the config file! 
Let me know if it works for you!
