### ISSUE TITLE
Status on server side

### ISSUE THREAD

**Issue by DeWolfRobin** [bastienwirtz/homer#676]
I love this tool, however, there are two problems:
1: I have to configure cors on every single application that I want to have included, which is not always suported.
2: The status does not work for local services, which are not externally reachable. E.g. my pihole is not externally reachable, but I would like t see the status anyway.

These could be solved by getting the information on the server side. Cors won't be needed and it can do the requests from inside the correct network.

**Comment by bastienwirtz** [comment]
Hi there,
Homer goal it to stay a static html page, that requires no maintenance, can live without update and without security issue. So no server code will be added. However, another component (a cors proxy for exemple) can act as homer server side component, and make possible to avoid all cors issues. 
I think there is multiple options out there regarding cors proxy. 

Good luck!
