### ISSUE TITLE
[Feature Request] Edit config.yml from web

### ISSUE THREAD

**Issue by Synt3x** [bastienwirtz/homer#68]
I guess I'm being a bit lazy and don't want to ssh into my server to edit my config.yml file. So if it's possible I would like it being on the webpage. Might be silly, but who knows?

update 200603: For me it doesn't have to be that fancy as frederickbeulieu is showing.

**Comment by frederickbeaulieu** [comment]
+1

Would like to be able to modify the file like with [DashMachine.](https://registry.hub.docker.com/r/rmountjoy/dashmachine/)

![image](https://user-images.githubusercontent.com/16929592/83685548-d8506600-a5b6-11ea-8ea9-236e46a23a1d.png)

**Comment by JamiePhonic** [comment]
You could setup [Code-Server](https://github.com/cdr/code-server) and use that to edit your config.
If you're running homer in docker, you can setup a Code-Server container and pass your homer config directory into that.
It would have the added benefit of providing syntax checking!

Reezpatel has created a [Pull Request](https://github.com/bastienwirtz/homer/pull/51) that would allow loading config.yml from a remote location which would be another solution

**Comment by stephane-j** [comment]
That would be nice, I will setup VS Code in the mean time.

**Comment by frederickbeaulieu** [comment]
I use Code-Server at work, unfortunally I also have the bug where I can't link my [config file from outside the docker](https://github.com/bastienwirtz/homer/issues/50). So I couldn't pass the file to Code-Server.

**Comment by JamiePhonic** [comment]
@stephane-j As a bonus, Code-Server puts the "current folder" as a parameter in the URL bar, so you could add a `links:` entry that points to your code-server instance with the directory pre-filled for essentially 1 click editing!

For example: 
```yml
links:
  - name: Edit config
    icon: fas fa-cog
    url: https://vscode.example.net/?folder=/config/appdata/homer
    target: "_blank" # optional html tag target attribute
```
where the path after `?folder=` is the path to the folder where you mounted your homer config INSIDE the container (in my case, /config/appdata/homer)

**Comment by bastienwirtz** [comment]
Hi there!

Glad you found a solution! I agree it would be interesting to have an editor, but what I wanted with Homer is to have a full static, no backend required, really light and simple solution. 
That not on my priorities but I'll look if I could add a very simple editor, maybe separated and optional. 

I just setup a [gitter chat](https://gitter.im/homer-dashboard/community) if you want to talk about it (or just say hi, or anything!)
