### ISSUE TITLE
[Question] Change Design & add widgets

### ISSUE THREAD

**Issue by FuckingToasters** [bastienwirtz/homer#703]
Hello, i just watched this video and liked the design of it, relativly at the beginning he says that it's Homer so i just switched from dashy to Homer. [https://www.youtube.com/watch?v=5YgWaeq07As](url)

Now after installing  Homer and configuring it a bit via config.yml my Homer looks like this:
![LDTHA3K](https://github.com/bastienwirtz/homer/assets/94435104/44c30592-a986-45ba-b652-f00aff7035e6)

As you can see, it look different plus there are no widgets from added services.

Anyone can explain me, how i can set it up like on the Youtube Video i included above?

**Comment by fbartels** [comment]
Looking at the video description he is using https://github.com/ajnart/homarr and not Homer

**Comment by FuckingToasters** [comment]
> Looking at the video description he is using https://github.com/ajnart/homarr and not Homer
Ah mb i should've read the Description instead of only hearing what was being said. Thank you for the info tho.
