### ISSUE TITLE
Installing homer with yarn produces wrong manifest.json file

### ISSUE THREAD

**Issue by klejejs** [bastienwirtz/homer#71]
When I run `yarn install` and `yarn build` I get links to images from manifest json as "./img/icons/\*" not "./icons/\*". Changing this might also fix https://github.com/bastienwirtz/homer/issues/66#issuecomment-636931288 as changing the manifest.json fixes it when run without Docker.

**Comment by bastienwirtz** [comment]
Hi @klejejs 
The fix as been merged, the path should be good now!

Thanks!
