### ISSUE TITLE
Mealie Custom Service is not working

### ISSUE THREAD

**Issue by DevFreezing** [bastienwirtz/homer#721]
**Describe the bug**
Mealie Custom Service is not working, Homer does not connect to the API. 

**Expected behavior**
Should show the number of recipes Mealie is keeping organized or the planned meal for today if one is planned

**Logs & errors**
I suspect that is s due to the URLs of the API are not properly set in the file src/components/services/Mealie.vue
For example at line 47 is calling /api/meal-plans/today/ but if we look at the mealie [API documentation ](https://nightly.mealie.io/api/redoc/)the URL is api/groups/mealplans/today

**Screenshots**

**Configuration**
My yml for mealie is:
 `  - name: "Applications"
    icon: "fas fa-cloud"
    items:
      - name: "Mealie"
        logo: "assets/icons/mealie.png"
        type: "Mealie"
        keywords: "self hosted recipe manager "
        url: "http://10.10.1.102:9000"
        target: "_blank" # optional html a tag target attribute
        apikey: "XXXX"`

```

**Comment by bobonthenet** [comment]
I'm experiencing issues with this too. I tried changing the urls to match the api docs, but it still isn't working.

**Comment by bobonthenet** [comment]
Turns out my Nginx config had issues too which is why changing the urls initially didn't work. I've created a PR to update those urls.

**Comment by JohWQ** [comment]
I'm also experiencing issues with this.

The Homer docker logs don't even mention anything to do with Mealie.

Inside of the docker container i can reach the domain with nslookup: mealie.domain.xyz.
