### ISSUE TITLE
subtitle in several lines

### ISSUE THREAD

**Issue by SerhiiZahuba** [bastienwirtz/homer#724]
I'm sorry, I didn't find a place where you can simply ask questions about this project, so I'm writing here.

I am looking for an option to add a description (subtitle) to a category in several lines.

![image](https://github.com/bastienwirtz/homer/assets/36307887/9b7da0b1-b9de-4a58-b64a-4a2c77d196ee)

In my version, it is necessary to specify that this project has the following projects and specify it as a comment in several terms. Because now it is one term that is not shown in its entirety.

If there is an opportunity to do this, it would be possible to indicate
several subtitles
subtitle_1
subtitle _2
etc. which will be placed under the name of the main project. Grateful in advance. thank you

**Comment by bastienwirtz** [comment]
Hello there, 

It's not possible for the moment. Cards have to have a fixed size to get both the vertical and horizontal layout aligned and look nice. 

That being said, you can use the custom CSS option to allow multiple lines 

```css
body app#main-section .subtitle {
  white-space: initial;
  text-overflow: initial;
}
```

I'm closing the issue, feel free to reopen it if anything.
