### ISSUE TITLE
Create static pages

### ISSUE THREAD

**Issue by sips4711** [bastienwirtz/homer#725]
**it would be a benefit to have static pages**
Static pages would be a a nice feature to instead of running on lighttpd. Static Pages can be copied to GitLab Pages as well. 

Would it be possible to generate static pages right now? Otherwise I'll suggest this as a feature.

What I did so far:

```
mkdir -p homer/data

chmod -R 777 homer

git clone https://github.com/bastienwirtz/homer.git homer/sources

cd homer



podman run --rm   -v $(pwd)/sources:/app --workdir=/app   docker.io/node:lts-alpine yarn install --frozen-lockfile
podman run --rm   -v $(pwd)/sources:/app --workdir=/app   docker.io/node:lts-alpine yarn build

ls -lah sources/dist

```

**Comment by fbartels** [comment]
Yes, Homer is fully static. You just need to grab the release asset and extract it to your webserver.

https://github.com/bastienwirtz/homer#using-the-release-tarball-prebuilt-ready-to-use

**Comment by sips4711** [comment]
That's the Aanswer I need. Thank you!!! :-)
