### ISSUE TITLE
[Question] How to change text for own translations?

### ISSUE THREAD

**Issue by schleudertrauma** [bastienwirtz/homer#738]
Hey friends,

i'm running Homer via docker container.
Sorry for the maybe stupid question but i am not that familiar on coding and stuff.

I tried to translate text passages in the code but homer does not show any changes.
I changed text in `/www/resources/Emby-66df1d8b.js` e.g. as follows:

`methods:{fetchServerStatus:async function(){this.fetch("/System/info/public").then(t=>{if(t.Id)this.status="running";`
into 
`methods:{fetchServerStatus:async function(){this.fetch("/System/info/public").then(t=>{if(t.Id)this.status="Funktional";`

But Homer still shows "running" on the dashboard, even after restarting the container.

Is it possible to translate the given text into another language and how to do it? Do i have to change more files to make the translation work?

greetings
Schleudi

**Comment by bastienwirtz** [comment]
Hi there, 
Translation is not supported for now, it's not possible.
