### ISSUE TITLE
[Feature request] Open in new tab

### ISSUE THREAD

**Issue by wizel10** [bastienwirtz/homer#74]
May be there is already a way, but can't find. I like to keep "homer" tab as first on my browser, so i can come back at any time to open my next application. Unfortunately, link opens in same tab and I always forget to press CTRL or mid-mouse-button.

**Comment by fbartels** [comment]
That is already possible you just have to specify https://github.com/bastienwirtz/homer/blob/c712d7c780a4e8d1ef2b67dc56b42ad979c36925/public/config.yml.dist#L71 for each link.

**Comment by wizel10** [comment]
Thanks, I initially thought that was the way to go, but added the "target: _blank" as part of the url. This clearly failed as expected.
Adding as suggested works perfect.
I close this now.

**Comment by marviiind** [comment]
Hey, is it possible to use target: "_blank" in more than one item? If i try to use it on multiple items in one service, my Homer Website is crashing.

**Comment by fbartels** [comment]
Hi @marviiind,

what do you mean with “crashing”? In your email you write that when you create a service “only the first one works”. Can you post an example of your config?


```
target: &target
  target: "_blank
```

And then I'm using ` <<: *target ` on each item that should be opened in a new tab.
