### ISSUE TITLE
Update docker

### ISSUE THREAD

**Issue by sayem314** [bastienwirtz/homer#753]
Latest version is missing on https://hub.docker.com/r/b4bz/homer/tags

**Comment by zc-devs** [comment]
On [GHCR](https://github.com/bastienwirtz/homer/pkgs/container/homer) either.

**Comment by sayem314** [comment]
@bastienwirtz any update?

**Comment by bastienwirtz** [comment]
Hello
There, the armv6 build seems to be broken, not sure why :thinking: 
I might disable it for now
