### ISSUE TITLE
custom services

### ISSUE THREAD

**Issue by AhmedThe13thUser** [bastienwirtz/homer#754]
in the [docs](https://github.com/bastienwirtz/homer/blob/main/docs/customservices.md) it mentions the custom services, but what if I have my own api key?

is there a way to integrate?

if yes then, how to integrate?

**Comment by bastienwirtz** [comment]
Hello, 

Several service requires an API which is specific to you. In this case, as described on the page you mentioned,  you can use the `apikey` configuration option to use it.
