### ISSUE TITLE
docker image does not recognise timezone appropriately

### ISSUE THREAD

**Issue by instantdreams** [bastienwirtz/homer#767]
**Describe the bug**
I am passing a timezone environment variable and mounting timezone and localtime as volumes in the docker container, but all times reported by the container are in UTC.

**Expected behavior**
I run the following commands on the container:

```
$ docker exec homer date
Mon Apr 15 17:30:27 UTC 2024

$ docker exec homer cat /etc/timezone
America/Edmonton
```

The container can see the timezone but is not recognising it.

**Logs & errors**
Perhaps the container image could include `tzdata` to allow this to work.

**Screenshots**
n/a

**Configuration**
n/a

**Comment by baumheld** [comment]
Would love that too, please add `tzdata` package

**Comment by baumheld** [comment]
Seems fixed. Can be closed

![image](https://github.com/user-attachments/assets/c98e289d-3e09-4e90-b2a4-f43a873790aa)

**Comment by instantdreams** [comment]
Indeed!

```
$ date
Wed 18 Dec 2024 01:35:32 PM MST
$ docker exec homer date
Wed Dec 18 13:35:35 MST 2024
```
