### ISSUE TITLE
Clarify docs for config.stylesheet. There's strange behavior when given a string

### ISSUE THREAD

**Issue by librick** [bastienwirtz/homer#774]
**Is your feature request related to a problem? Please describe.**

If users assign a string to `config.stylesheet` rather than an array, the stylesheet doesn't load and it's confusing to debug. I think either the docs should be improved to explicitly mention that users MUST use an array, or some validation should be added to tell the user that they used a bad value for `config.stylesheet`. This was really confusing when I tried to configure Homer to use a custom stylesheet.

In `config.yml` I had `stylesheet: assets/custom.css` (broken, don't copy this!). This wasn't working and I had to look at the Homer source code to learn why, specifically [this part of App.vue](https://github.com/bastienwirtz/homer/blob/9cd822b5c4122786c481c35c108b71dc93df26e2/src/App.vue#L227) where the code loops over the values in `config.stylesheet`. That led me to look at my dashboard's `style` tag, which showed this weird code:

![image](https://github.com/bastienwirtz/homer/assets/106356608/f6f2413f-b927-4142-8c6f-8c6f3cbd1b58)

Basically, because I used `stylesheet: assets/custom.css` (broken, don't copy this!), **when it was looped over in App.vue, it looped over the characters of the string, treating each one as a stylesheet to import**.

I also probably could've been tipped off by these weird 404'd requests:
![image](https://github.com/bastienwirtz/homer/assets/106356608/6385190e-806f-4a2a-b119-702c57d5fbb4)

**Describe the solution you'd like**
In the [docs for config.yml](https://github.com/bastienwirtz/homer/blob/9cd822b5c4122786c481c35c108b71dc93df26e2/docs/configuration.md?plain=1#L43), maybe add another comment to warn users that the value MUST be an array, not a string. I could've just read the docs more carefully but I'm guessing I'm not the only one to be tripped up by this.

**Describe alternatives you've considered**
You might also consider adding a more obvious failure mode (either show an error, fail to build, etc.) if `config.stylesheet` is provided but is not an array of strings.

**Additional context**
N/A. Thanks for working on a great project and contributing to open source!

**Comment by bastienwirtz** [comment]
Hello @librick, 

Thanks for reporting this. The option now support a single stylesheet using a string or multiple using an array, and a [theming section](https://github.com/bastienwirtz/homer/blob/main/docs/theming.md) has been added to the documentation.

**Comment by librick** [comment]
Thanks! Great project, thanks for contributing to open source software 😊
