### ISSUE TITLE
IIS Configuration

### ISSUE THREAD

**Issue by AvocatDuDiable** [bastienwirtz/homer#776]
Hello, 

I just discover the project thanks to Korben article. 
The solution works fine and I love the concept and how you manage that with the config file. Thanks a lot for this. 

I create this topic if someone would like to install Homer on a IIS Server (yes, I know, not the best web server solution but ... no choice on my side )
A quick configuration is mandatory : add the YML format on Mime Types 

![image](https://github.com/bastienwirtz/homer/assets/9076502/2fb0c804-af5d-435e-b50e-9330b95bbd85)

Regards, 

Allan

**Comment by bastienwirtz** [comment]
Thanks @AvocatDuDiable !
I'm closing the issue but it will still shows up if anyone search for this :+1:
