### ISSUE TITLE
Wrong result of annotatePeaks.pl

### ISSUE THREAD

**Issue by kai333334** [bastienwirtz/homer#787]
Hello,

I am currently working on annotating a narrowPeak file using the annotatePeaks.pl command. However, I have encountered discrepancies in the gene annotations. For example, in IGV, peak_21610 is located in the 3'UTR of the RPL4 gene. Despite this, the result from annotatePeaks.pl indicates that peak_21610 is in the 3'UTR of the snapc5 gene.

To troubleshoot, I ensured that my GTF file was unified in both HOMER and IGV. Despite this, the annotation results remain incorrect. I also tried using ChIPseeker for annotation, but encountered the same issue. Upon examining the annotation files, I noticed that the start and end locations for the genes provided by both HOMER and ChIPseeker do not encompass the start and end locations of the peaks.
![figure1](https://github.com/bastienwirtz/homer/assets/156998873/66039a37-269f-4a11-b69d-fbfebbfcc1bd)
![image](https://github.com/bastienwirtz/homer/assets/156998873/7c9a99eb-e25d-4a83-84b2-86cc921423bb)

Here are the relevant details for reference:

peak_21610: Start - 64,178,423, End - 64,178,617
snapc5 gene: Start - 64,179,274, End - 64,183,132
RPL4 gene: Start - 64,173,375, End - 64,178,666
RPL4 3'UTR: Start - 64,178,442, End - 64,178,666

As shown, peak_21610 falls within the RPL4 gene’s range, specifically within its 3'UTR, yet the annotations incorrectly associate it with snapc5. The start and end locations from ChIPseeker also do not match the gene ranges correctly.

I would appreciate your insights or suggestions on resolving this annotation issue.

Thank you for your assistance.

Best regards,
  WANG

**Comment by bastienwirtz** [comment]
Hello @kai333334, 

I think your are looking for another Homer ! This repo basically contain a tool used do display links (a dashboard or web portal), kind of like bookmarks. Nothing to do with http://homer.ucsd.edu/homer/index.html

Good luck with your gene annotation!

**Comment by thisisamirv** [comment]
Lol this is so embarrassing XDDDD
