### ISSUE TITLE
1rst result no longer open when searching

### ISSUE THREAD

**Issue by BlueCobbleStone** [bastienwirtz/homer#790]
**Describe the bug**
When I use the search bar and press enter it sends me back to homer "current" page.
I'm using the lastest image of homer.

**Expected behavior**
It used (yesterday) to open the first result of the search when enter was pressed

**Comment by bastienwirtz** [comment]
Hello @BlueCobbleStone 

I just tested on the demo (https://homer-demo.netlify.app/), i wasn't able to reproduce, it seems to work. Which browser do you use ? Could you open you browser console and see if any error appear when you press enter ? Thanks.

**Comment by BlueCobbleStone** [comment]
I used brave, also tested with a fresh install of google chrome and firefox on windows on the demo and I still have the problem.
Here's a screenshoot of the console:
![image](https://github.com/bastienwirtz/homer/assets/107225155/623c20ba-b348-4284-8bf6-1891a3257ae3)
Not sure if it's related to the problem

**Comment by bastienwirtz** [comment]
Thanks for the details @BlueCobbleStone, it's [now fixed](https://github.com/bastienwirtz/homer/commit/6c438298f2c21b9bd101d4dedc0462e8e8410d17#diff-54e324578058624757e9429beb10ee4e113df7ea65035018343fcfe5c56ac072) :+1:
