### ISSUE TITLE
Ping working on Firefox without needing a CORS proxy or Access-Control-Allow-Origin: *

### ISSUE THREAD

**Issue by tryolly** [bastienwirtz/homer#830]
I'm very confused and know very little about the topic. I've just set up the Ping card for my instance of Homer on my local only home server. When using Microsoft Edge on my main computer to check the dashboard all my services have the Ping as offline which is what I expect since I am not using a proxy or have a set the Access-Control-Allow-Origin: * in the header for each of my services.

However, when I use Firefox on the same computer as Edge everything just works, they all show as online, I don't get it. When I check Firefox on another computer in the house it shows as offline, just like Edge does, which is what I would expect. Does anyone know why Firefox on my main computer seems to be ignoring the issue with CORS? 

I thought that maybe it was one of my extensions, but I turned them off and no change. I also thought it might of been the strict tracking protection, nope again. I am slightly concerned that this is happening as it may be a security leak with my Firefox browser, or alternativily maybe I stumbled upon some way to solve the CORS issue without a proxy, Access-Control-Allow-Origin: *, or requiring same domain/port.

Perhaps I have edited some security option in about:config, but I can see nothing. Does anyone here have any idea about what is going on?

**Comment by tryolly** [comment]
When I try a fetch command in the webtools to one of the services on my server I get the following

```
fetch('http://192.168.20.2:7878')
Promise { <state>: "pending" }
​
<state>: "fulfilled"
​
<value>: Response { type: "cors", url: "http://192.168.20.2:7878/", redirected: false, … }
​​
body: ReadableStream { locked: false }
​​​
locked: false
​​​
<prototype>: ReadableStreamPrototype { cancel: cancel(), getReader: getReader(), pipeThrough: pipeThrough(), … }
​​
bodyUsed: false
​​
headers: Headers(4) { "cache-control" → "no-cache, no-store", "content-type" → "text/html", expires → "-1", … }
​​​
<entries>
​​​
<prototype>: HeadersPrototype { append: append(), delete: delete(), get: get(), … }
​​
ok: true
​​
redirected: false
​​
status: 200
​​
statusText: "OK"
​​
type: "cors"
​​
url: "http://192.168.20.2:7878/"
```

with Firefox on the other computer in my house it shows the state as rejected

**Comment by tryolly** [comment]
So I worked out what was happening. Firefox has an option in its Settings > Privacy & Security > HTTPS-Only Mode. The setting is either

- Enable HTTPS-Only Mode in all windows
- Enable HTTPS-Only Mode in private windows only
- Don’t enable HTTPS-Only Mode

I have mine set to Enable HTTPS-Only Mode in all windows. With this setting enabled the Ping works. Switch to Don’t enable HTTPS-Only Mode and now the Ping doesn't work and all services show as offline.

So the question is why is this happening? I am not using http on my network.

**Comment by tecspda** [comment]
I 

> So I worked out what was happening. Firefox has an option in its Settings > Privacy & Security > HTTPS-Only Mode. The setting is either
> 
>     * Enable HTTPS-Only Mode in all windows
> 
>     * Enable HTTPS-Only Mode in private windows only
> 
>     * Don’t enable HTTPS-Only Mode
> 
> 
> I have mine set to Enable HTTPS-Only Mode in all windows. With this setting enabled the Ping works. Switch to Don’t enable HTTPS-Only Mode and now the Ping doesn't work and all services show as offline.
> 
> So the question is why is this happening? I am not using HTTPS on my network.

I have disabled. But problem stay.

**Comment by tryolly** [comment]
So you have "Don’t enable HTTPS-Only Mode" activated and the services are showing as offline? If so, this is what I get. I only get the services showing as online when "Enable HTTPS-Only Mode in all windows" is activated.

**Comment by bastienwirtz** [comment]
Hello,

Indeed, CORS issue is expected when homer and the target services are on different domain. For the ping cards (or any other service integration) to works, you will require either that:

- All services are exposed on the same domain as homer (mydomain.tld/pihole, mydomain.tld/proxmox), avoiding any cross domain request issues (CORS).
- All services accept cross site requests (= send the necessary CORS headers, either set directly in the service configuration if possible, or using a proxy to set the headers)

It's a well know issue, and as a fully front end app, Homer cannot do anything about it. 

For the `ping` service in particular, you can use [httpGoPing](https://github.com/MuratovAS/httpGoPing#httpgoping), made by @MuratovAS !

**Comment by tryolly** [comment]
No, unless I'm mistaken somewhere, I'm saying Firefox is different and the troubleshooting page refering to the well know Ping issue is wrong.

> - Host all your target service under the same domain & port.
> - Modify the target server configuration so that the response of the server included following header- Access-Control-Allow-Origin: * (https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#simple_requests). It might be an option in the targeted service, otherwise depending on how the service is hosted, the proxy or web server can seamlessly add it.
> - Use a cors proxy server like [cors-container](https://github.com/imjacobclark/cors-container), [cors-anywhere](https://github.com/Rob--W/cors-anywhere) or many others.

none of those 3 apply to me.

1. I am not using the same domain and port. domain yes (a local one) but every port is different.
2. I have not set Access-Control-Allow-Origin: * on any of the services
3. I am not using a CORS proxy server or any proxy server.

Now, despite not doing any of those three, I have the ping fuctioning perfectly through firefox, but only when the "Enable HTTPS-Only Mode in all windows" is checked in the firefox settings. For some reason, the Ping issue titled "My service card doesn't work, nothing appears or offline status is displayed (pi-hole, sonarr, ping, ...)" does not apply to Firefox when the HTTPS-Only Mode is activated and when using a local only server. In Firefox it just works, which I consider a good thing, but I wonder why it works.

**Comment by bastienwirtz** [comment]
Yeah that's weird, it's not supposed to work 🤔
You might find more information in the browser  web console, network tab, to inspect request headers details.

**Comment by tryolly** [comment]
Web console doesn't reveal much. No errors in the console when I reload the page.

I did try to ping an external site using the web console though. That returned a Cross-Origin Request Blocked error so it only seems to be a loophole with the local network.

Very weird indeed.
