### ISSUE TITLE
incomplete sentence in custom services doc

### ISSUE THREAD

**Issue by meonkeys** [bastienwirtz/homer#834]
`docs/customservices.md` says (verbatim):

> Using smart cards will probably requires
> If you experiencing any issue...

Just pointing out that first sentence is incomplete. Not sure what it was going to be. Probably something about CORS?

**Comment by bastienwirtz** [comment]
Indeed! Thanks for letting me know, it should be better: https://github.com/bastienwirtz/homer/commit/7909bd10547f78f1e7de8551fd673356e1dbc8bf
