### ISSUE TITLE
docker-compose.yml link not valid in readme

### ISSUE THREAD

**Issue by TFhdKi95ae8L** [bastienwirtz/homer#836]
**Describe the bug**
When clicking on the link to the docker-compose.yml, a 404 is returned.
https://github.com/bastienwirtz/homer/blob/main/docker-compose.yml

**Expected behavior**
Direct link to docker compose file is expected, if available

**Logs & errors**
Link:
https://github.com/bastienwirtz/homer/blob/main/docker-compose.yml

**Screenshots**
![image](https://github.com/user-attachments/assets/7784146c-ff67-4cb5-9ff6-da7a03ffb8ab)

```

**Comment by bastienwirtz** [comment]
Good catch @TFhdKi95ae8L, Thanks :pray: 
The file has been removed, replaced with an inline example to copy/paste (cf https://github.com/bastienwirtz/homer?tab=readme-ov-file#using-docker).
