### ISSUE TITLE
This docker repo is a mess

### ISSUE THREAD

**Issue by BodingClockchian** [bastienwirtz/homer#86]
Great work keeping this up but its a total mess.
Manually copying the config files from the localmachine? The dockerfile should be configured to do this.

**Comment by bastienwirtz** [comment]
Hi @BodingClockchian, 
I would not qualify this particular issue a "total mess" (unless I miss something else?). But anyway, that's planned, I will fix that after https://github.com/bastienwirtz/homer/pull/87 is merged.

**Comment by GlennToms** [comment]
@BodingClockchian Hopefully my merge has made Homer with docker easier for you to use.  Could you close this issue if your happy? Many thanks.
