### ISSUE TITLE
Missing favicon

### ISSUE THREAD

**Issue by simonporte** [bastienwirtz/homer#88]
Favicon used to work before, and pinning the site as an app in chrome (android or desktop) showed an icon.
I don't see the favicon anymore.
Did anything change ? The path is still the same ?
I have a favicon.png in assets folder.
Thanks.

**Comment by AlexanderEDavis** [comment]
I'm having the same issue. In one of the recent commits (a23914d573841f9088cc9cd69bce24c28f432acf) requires app icons. I'm trying those to see if it works

**Comment by AlexanderEDavis** [comment]
Fast fix is:
Move favicon to assets/icons/ then rename favicon to favicon-32x32.png

**Comment by simonporte** [comment]
It does work, thanks @AlexanderEDavis 
@bastienwirtz could you please add the necessary donut favicon by default in docker image, or at least put all the default images in the src/assets folder in the repository ?

**Comment by bastienwirtz** [comment]
Hi there, 

@simonporte Thanks for opening the issue. I just pushed an update to remove the duplicated favicon and set the in `favicon-32x32.png` in the `assets/icons/` as the default. 
That should works fine now.

**Comment by simonporte** [comment]
Hello,
Thanks for the update.
I notice when I remove the assets/logo.png mentioned in config.yml or comment the line, there is no default incon but a text placeholder.
As for the favicon, if I remove assets/icon folder, it is created on container creation.
It is a hamburger ||| icon.
Could you provide the donnut icon ?
It is much more attractive.
Or maybe it is a deliberate choice ?
Thanks anyway for your actions.

**Comment by bastienwirtz** [comment]
If you remove the `assets/logo.png` you will have a broken image, but if you comment the line in the `config.yml`, or set it to none (`~`) you not have the test place holder. 
```yaml
#logo: "logo.png"
OR
logo: ~
``` 
Regarding the favicon and other icons, that the hamburger one was kind of a temporary icon, I hadn't the original donut in the proper size. But I just brought it back! not exactly the same, but close. Hope you like it!

Note that the default icons are copied at docker start only when they are missing, and you can customise call icons. I updated the documentation about that: https://github.com/bastienwirtz/homer/blob/master/docs/configuration.md#pwa-icons. You can generate all the icons from a single image file and replace everything.

**Comment by simonporte** [comment]
I tested again.
In fact it is as you say : I modified a backup file and not the proper file when I tested commenting the logo.png, my bad...
Thanks for the new logo. Homer with a donut is so much more homerish!
Could you make it so that it pulls the logo.png like the favicon if it does not exist ?
As for the new logo, it feels different
Il like purple, but on blue background it is not the best. Maybe it would be better without gradient?
Icing sugar is a good addition, the missing bite from previous icon was good also.
Why could you not get the previous icon back? Quality was not sufficient on big sizes?
If you add support for themes, it could be a good idea to propose different icons to match with it.

**Comment by bastienwirtz** [comment]
Thanks for the feedback @simonporte ! Yeah the old one was small and more importantly, wasn't free to use. The new one is based on one of the great logo of https://thenounproject.com. I will work on it, there is definitely room for improvements!

**Comment by bastienwirtz** [comment]
(I'm closing the issue as the favicon issue is solved, but feel free to reopen if anything!)
