### ISSUE TITLE
Service worker does not properly cache fonts

### ISSUE THREAD

**Issue by fbartels** [bastienwirtz/homer#9]
Hi @bastienwirtz,

I have been playing around with your start page a bit and in my test environment I am actually running it in a subdir (I have opened https://github.com/bastienwirtz/homer/pull/8 to fix some code related to that).

Once thing I am unable to fix myself is the following:

When switching in the dev console to offline mode, all externally added fonts are missing. Which means for example the font awesome icons, but also the title looks different (which is a google font as far as I can see). I have found https://stackoverflow.com/questions/39432717/how-can-i-cache-external-urls-using-service-worker which sounds like it could help to improve, but I am not sufficient enough with Javascript to actually implement the solution.

**Comment by bastienwirtz** [comment]
Hi Felix, 
Thanks for reporting that, I'll look into it very soon :+1:

**Comment by fbartels** [comment]
Hi Bastien,

thanks. In of of the forks of the repo has added these resources locally, which means it could be easier to add them to the manifest.

**Comment by bastienwirtz** [comment]
Hi @fbartels!
This should do the trick: https://github.com/bastienwirtz/homer/pull/11

**Comment by fbartels** [comment]
Almost. I have commented the pull request.

Thanks so far!
