### ISSUE TITLE
Mutiple Column Layouts

### ISSUE THREAD

**Issue by AlexanderEDavis** [bastienwirtz/homer#91]
One of the recent prs allowed us to change the number of columns and/or set it to auto which allowed a different number of columns throughout the page. Is there a way to allow this feature to be configurable? For example, 4 columns on row 1, 2 columns on row 2 and 3 columns on row 3.

**Comment by JamiePhonic** [comment]
Just to clarify, you're looking for an option that would allow different numbers of colums for each section in list mode?

I beleive this option was more intended for the "Table" view rather than the "List" view, even though it apples to both.

**Comment by AlexanderEDavis** [comment]
In the table view, my Homer installation has 4 sections in the top row and 3 in the middle row.

**Comment by bastienwirtz** [comment]
Hi @AlexanderEDavis 

Thanks for your issue!
I like the idea, I think not for each row, but I would be very nice for each group. I'll look at that.

**Comment by bastienwirtz** [comment]
Hi there,

I'm closing this one. I will work on different layout on the future, but it's not the immediate priority. 
Best,
