### ISSUE TITLE
[Feature Request] Edit Links from Web

### ISSUE THREAD

**Issue by ashwin-pc** [bastienwirtz/homer#92]
The ability to edit the links from the startpage directly would be amazing!

I know https://github.com/bastienwirtz/homer/issues/68 already partially addresses this and I agree a full editor is definitely not what Homer is meant to be. But setting up `code-server` and messing around with YAML is far too cumbersome for just dynamically adding and deleting links.

Im currently setting up and modifying my NAS setup pretty often, but I also see my self using this start page for my daily workflow. Editing inks on the fly becomes really useful then. Heimdall does this really well and it is frankly the only reason im still using it. Would love to see Homer have such a feature (Can also jump in and help if needed)

**Comment by Synt3x** [comment]
I agree with @ashwin-pc on this. I also thought that the comments in thread (#68) talked about a different thing then my original post.

**Comment by bastienwirtz** [comment]
Hi there!

I want Homer to stay purely static, so I won't include an editor in it. But I like the idea, and we could have a separate "homer-editor" project that would make that possible. I'll think about it!

**Comment by ashwin-pc** [comment]
@bastienwirtz I agree. This was a big enough issue for me that I literally made a start page myself. You can have a look at how I've solved editing links and still keeping it as a static website. ([Demo](https://test.designedbyashw.in/hiccup/))([Code](https://github.com/ashwin-pc/hiccup))

I essentially store the edits in local storage and expose the config so that moving it around is as simple as copy pasting it directly in browser. No 3rd party app needed. I also still use the `config.json` file as my source of truth when the localstorage cache is cleared

**Comment by bastienwirtz** [comment]
Well done @ashwin-pc! Nice start page :)

**Comment by bastienwirtz** [comment]
Closing this for now, as said it would be in a separate, yaml editor app and not be done here.
