### ISSUE TITLE
Alignment of FA icons with different widths

### ISSUE THREAD

**Issue by AlexFullmoon** [bastienwirtz/homer#93]
Right now they are left-aligned, and varying widths are noticeable. For example, fa-code and fa-code-branch have around 20 pixels difference.

Can they be made center-aligned?

**Comment by gabe565** [comment]
Probably not the best long-term solution, but I've been adding `fa-fw` to all of my icon entries and that will make then all match in width.

More long term, `fa-fw` should probably be added to all icons by default.
