### ISSUE TITLE
[PWA] start_url in manifest.json points to /assets path

### ISSUE THREAD

**Issue by CoordSpace** [bastienwirtz/homer#99]
## Expected Behavior
When adding an instance of homer to the homescreen of a mobile device, the default starting URL should point to the root address. (e.g. domain.tld if homer is set as the root homepage)

## Actual Behavior
For home screen links created in iOS 13 and Android 10 using Safari and Chrome respectively, the URL for the homer service instead defaults to domain.tld/assets

Similarly using Chrome's desktop dev tools, the Start URL for a homer instance is "." which upon clicking will take you to the /assets path.

This is due to an undefined scope causing the default URL to map to the directory where manifest.json is located. From [web.dev's nice run down on manifest documents:](https://web.dev/add-manifest/)

> If you don't include a scope in your manifest, then **the default implied scope is the directory that your web app manifest is served from.**

## Steps to Reproduce the Problem

  1. Open up Chrome web browser and navigate to a homer instance.
  1. Open the developer tools (ctrl+shift+i) and switch to the Application tab.
  1. In the Manifest section, click on the Start URL value and see where it takes you.

## Possible Solution

1. Add a "scope" property to manifest.json with a value of "/" to set the root of the PWA 
2. Change "start_url" to "/" to be more explicit.

## Specifications

  - Version: Release v20.06.1 using the Dockerfile included in the repo to build the Docker image
  - Platform: Ubuntu 20.04 & Docker 19.03.8
  - Subsystem: Traefik 2.2.1 as a reverse proxy

**Comment by fbartels** [comment]
Explicitly setting the start_url to / would break use cases where Homer is served from a subdirectory, though.

**Comment by CoordSpace** [comment]
> 
> 
> Explicitly setting the start_url to / would break use cases where Homer is served from a subdirectory, though.

I've swapped "start_url" from . to / as a test on my local instance and I'm not seeing that behavior at all, even though I run my instance on a subdomain (homer.domain.tld). Though my reverse proxy setup might be different than yours.

[Here's a screenshot of what Chrome's devtools are telling me](https://i.imgur.com/D37HQwa.png) and I get the same fixed result on my iPhone if I attempt to add it to my home screen.

Looking over some of the documentation, a forward slash "will always point to the root of the origin." Possibly that origin can be a root TLD _or_ a subdomain depending on how homer is routed?

**Comment by fbartels** [comment]
Yes, but I am talking about a sub directory and not a sub domain. My homer is not running at homer.domain.com, but domain.com/homer. Therefore the root of the origin would not be my homer installation.

**Comment by fbartels** [comment]
The start_url could be set relatively. I have a branch at https://github.com/fbartels/homer/tree/start_url, but due to Github issues I cannot make a pr at the moment

**Comment by CoordSpace** [comment]
That solves it for me.
Thanks for your quick work!

**Comment by AlexanderEDavis** [comment]
#100 You need to set the URL to .. instead of .

**Comment by fbartels** [comment]
@AlexanderEDavis yes that is roughly the thing that the pr does.

**Comment by bastienwirtz** [comment]
Good catch @CoordSpace! Thanks for opening the issue. @fbartels PR has been merged, it should be all good now!

**Comment by bastienwirtz** [comment]
(I'm closing the issue, but feel free to reopen if anything wrong)
